seek-oss/braid-design-system

lib/components/Alert/Alert.js
lib/components/Box/Box.js
lib/components/Checkbox/Checkbox.js
lib/components/ChecklistCard/ChecklistCard.js
lib/components/Divider/Divider.js
lib/components/FieldMessage/FieldMessage.js
lib/components/Radio/Radio.js
lib/components/Reset/Reset.js
lib/components/Strong/Strong.js
lib/components/Text/Text.js
lib/components/ThemeProvider/ThemeProvider.js
lib/components/icons/ChevronIcon/ChevronIcon.js
lib/components/icons/Icon/Icon.js
package.json

The use of both `...props` and `this.props` seems to be causing issues with Babel somehow, thinking that we have duplicate declarations of "props". This is more of a quick fix, since this isn't technically an issue with our code, but I'm keen to get this fix released ASAP. It doesn't hurt that this is arguably a better notation, anyway.
This only happens during `sku build`, which is why it wasn't picked up in tests, so to catch issues like this in the future, we now run `sku build` on CI as part of `npm test`.

fix(build): Use '...restProps' instead of '...props'

---

package.json
release.config.js

semantic-release [allows the configuration](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/configuration.md#configuration) either via `package.json` values or `release.config.js` values.
`package.json` values can not be commented, and without context it can be unintuitive why certain configurations have been chosen.
This change helps document the release process, helping with any further changes that may be made.
Confirmed after this change no success plugins are loaded still:

build: Seperate out and document release configuration

---

package.json
yarn.lock

Cleaning the `dist` folder is no longer required with the latest version of sku (thanks @chardos!  🙌🏻)

chore(deps): Update sku to v5.10.1

---

.pullapprove.yml

We removed the explanation when migrating to v3 PullApprove. The functionality has been restored under the `pullapprove_conditions` section now, so reinstating the behaviour.

ci(PullApprove): Add `explanation` for invalid PR titles

---

docs/src/App/App.js

The `/playroom` link doesn't work on GitHub pages because it doesn't honour the `braid-design-system` base href, instead taking you to `https://seek-oss.github.io/playroom`. Swapping out the `<a>` tag for a React Router `<Link>` ensures that the same base href logic is applied.

docs(playroom): Fix Playroom link in production

---

docs/src/App/ComponentProps/ComponentProps.js
docs/src/App/ComponentRoute/ComponentRoute.js

In preparation for supporting parsing of typescript type interfaces from components, extracting the prop renderer on the docs site to it's own component.

docs(ComponentRoute): Extract prop renderer

---

lib/componentDocs/generateComponentDocs.js
lib/componentDocs/globsToReactDocgen.js

I forgot how to javascript and never held on to the array returned from `concat`, which meant the component doc generation script was always returning an empty array.
Also took the opportunity to remove project opinions from from `globsToReactDocgen` which is likely to become it's own external module in the future.

docs(site): Fix generate-component-docs script

---

lib/components/Checkbox/Checkbox.js
lib/components/Radio/Radio.js
lib/themes/jobStreet/atoms/border/borderWidth.css.js
lib/themes/seekAnz/atoms/border/borderWidth.css.js
lib/themes/seekAsia/atoms/border/borderWidth.css.js
lib/themes/utils/columnSpacingForCssRule.js
lib/themes/utils/fontSizeRulesForTokens.js
lib/themes/utils/rowSpacingForCssRule.js
lib/themes/utils/sizeRulesForTokens.js
lib/themes/utils/toUnit.js
lib/themes/utils/toUnit.test.js
lib/themes/wireframe/atoms/border/borderWidth.css.js

Adding a `toUnit` until and implementing `px`. Consolidates all the unit concatenation template strings, allowing the code to focus on the calculation.

fix: Add `toUnit` util

---

package.json
yarn.lock

This should (hopefully) make sure that Renovate sends us PRs for minor updates too.

chore(deps): Pin Playroom to exact versions

---

lib/components/private/examplesForIcon.js
lib/themes/jobStreet/tokens/tokens.ts
lib/themes/utils/__snapshots__/fontSizeRulesForTokens.test.js.snap
lib/themes/utils/__snapshots__/sizeRulesForTokens.test.js.snap
lib/themes/utils/__snapshots__/transformForTokens.test.js.snap

The contrast between `large` and `standard` text is much stronger in the `jobStreet` theme compared to the others. We'll need to investigate a bit more to understand where this discrepancy is coming from, but for now we're reverting back to the previous values.

fix(Text): Align JobStreet large text with other themes

---

package.json

In production mode, the CSS can end up in the wrong order due to tree shaking. Normally this isn't a problem, but the order of imports is actually important within the theme directories because we need to ensure that the CSS reset is imported first. Without this, the CSS reset can actually be moved below other rules in the resulting CSS file.

fix: Add ‘themes’ directory to package ‘sideEffects’ list

---

lib/components/Checkbox/Checkbox.tsx
lib/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
lib/components/ChecklistCard/ChecklistCard.docs.tsx
lib/components/ChecklistCard/__snapshots__/ChecklistCard.test.tsx.snap
lib/components/Radio/Radio.tsx
lib/components/Radio/__snapshots__/Radio.test.tsx.snap

This is to fix an issue where the error border wasn't very visible against the background colour when a checkbox is checked:
Instead, we now show the error border around the entire row:

fix(ChecklistCard): Show error border on entire row

---

lib/components/ChecklistCard/ChecklistCard.docs.tsx
lib/components/ChecklistCard/ChecklistCard.tsx

Note: This introduces a double border between checkboxes when multiple error states are stacked, but this is being treated as the lesser of two evils for now.

fix(ChecklistCard): Ensure divider doesn’t cover error border

---

lib/components/Box/Box.tsx
lib/components/Heading/Heading.tsx
lib/components/Text/Text.tsx
lib/components/icons/Icon/Icon.tsx
lib/themes/theme.d.ts

Cleaning up all the type names, we had inconsistent naming around the pluralisation and use of the word `Variant(s)` and it just adds a lot of noise really. So making the naming a bit tidier.

style(types): Clean up naming

---

lib/components/Checkbox/Checkbox.css.js

fix(Checkbox): Fix tick rendering issue in IE11

---

package.json

This package is needed by consumers, so we need to move it from `devDependencies` to `dependencies`.

fix(deps): Add ‘polished’ to dependencies

---

docs/src/App/ComponentRoute/ComponentRoute.tsx
docs/src/types.d.ts
lib/components/Checkbox/Checkbox.docs.tsx
lib/components/Radio/Radio.docs.tsx
lib/components/TextField/TextField.docs.tsx
lib/stories/all.stories.tsx

Fixes the server/client mismatch error caused by the differences in the handler instances between build render and client render. As a bonus it now hands the docs render functions a dummy handler which can be easily consumed in all components

docs: Fix console error for event handlers

---

lib/atoms/makeBoxShadows.ts
lib/components/Button/Button.tsx

Fix the importing of types in `Button` by using relative paths. This meant the component was functional in braid but broken for consumers. Also found the same issue in the `makeBoxShadow` atom.

fix(Button): Use relative path for type imports

---

docs/src/App/Home/Home.css.js
docs/src/App/Home/Home.css.js.d.ts
docs/src/App/Home/Home.tsx
docs/src/render.tsx

Fixes (hopefully) the playroom link is broken when deployed to ghpages site. Unfortunately can't test outside of ghpages deployment at this stage, but logic seems sound.
Also addresses the orphaned text that occurs on certain resolutions on the subtitle of the home page.

docs: Fix playroom link

---

docs/src/App/App.tsx

Since introducing the home route on the docs site the `/icons` route was not catered for — only `/components`. Might merge these urls under `/components` in the future, for now just fixing the routes.

docs: Fix icons component routes

---

lib/components/Button/Button.css.js
lib/components/Button/Button.css.js.d.ts
lib/components/Checkbox/Checkbox.tsx
lib/components/FieldMessage/FieldMessage.tsx
lib/components/Radio/Radio.tsx
lib/components/TextLinkRenderer/TextLinkRenderer.css.js
lib/components/private/FieldOverlay/FieldOverlay.tsx
lib/components/private/Overlay/Overlay.css.js
lib/themes/theme.d.ts

To support upcoming `Field` refactor, I'm breaking out a couple of clean ups:
- Hoisting up the `FieldTone` to be a global type to be shared amongst all the fields.
- Make `Overlay`s transparent by default, simplifying consumer styles.
- Add `hover` support to `FieldOverlay`.
All are internal changes, so recommending this as a `refactor` that we release with the upcoming `Field` work.

refactor: Hoist FieldTone type & default Overlay to transparent

---

lib/components/TextArea/TextArea.tsx
lib/components/private/Field/Field.tsx

The usage of the `HTMLFormElement` type in `Field` was incorrect and being exposed incorrectly on the docs site too. This fixes it for all consumers of `Field`.
```diff
Options
value
-    Type: any (Required)
+    Type: string | number | string[] (Required)
onChange
-    Type: any (Required)
+    Type: ((event: FormEvent<HTMLFormElement>) => void)
onBlur
-    Type: any
+    Type: ((event: FocusEvent<HTMLFormElement>) => void)
onFocus
-    Type: any
+    Type: ((event: FocusEvent<HTMLFormElement>) => void)
```

fix(Field): Resolve native types correctly

---

lib/atoms/color/makeColors.ts
lib/components/Dropdown/Dropdown.tsx
lib/components/TextArea/TextArea.tsx
lib/components/TextField/TextField.tsx
lib/components/private/Field/Field.tsx

Refactored `Field` to allow consuming components to control their own form value and event handlers, as these are not the same for every field, eg. `checked` vs `value` etc.
The `HTMLFormElement` type was too generic, so pulling back to allow the fields to extend their own native props.

refactor(Field): Consumers control their own value & event interface

---

lib/atoms/normalizeAtoms.ts
lib/components/FieldMessage/FieldMessage.docs.tsx

When introducing `min-height` support to `Box` the atom mapping was [incorrectly mapped to `height`](https://github.com/seek-oss/braid-design-system/pull/138/files#diff-1ad626edbafbfdbc7f791bd37d6efa65R173). This resulted in `FieldMessage` (our only usage of `minHeight` atom, to enforce `height` rather than `min-height` — causing text overflow issues for consumers.
Fixed the mapping and added a long message to the docs site to catch this category of problem in a screenshot contract.

fix(FieldMessage): Map minHeight atom correctly to fix wrapping messages

---

docs/src/App/Home/Home.css.js
docs/src/App/Home/Home.css.js.d.ts
docs/src/App/Home/Home.tsx
lib/components/Button/Button.tsx

Improve the tab navigation on the homepage, previously there was a double tab for each button and confusion from a screen reader perspective between the link and button elements.
Also change the document order to put the link to github source last with a nicer focus state.

docs(a11y): Fix tab navigation and visual outlines

---

docs/src/App/Home/Home.tsx
lib/components/Actions/Actions.docs.tsx
lib/components/Button/Button.docs.tsx
lib/components/Button/Button.tsx

In making `onClick` a required prop (like our form fields) the oversight here was changing the contract of a submit button with it's form — i.e. using the `onSubmit` of a form without providing an `onClick`.
Rolling back the required aspect of the click handler and also rolling it back out of the docs to keep the code examples terse.

fix(Button): Make onClick optional to support form submit

---

lib/components/FieldMessage/FieldMessage.tsx

The icons used for critical and positive `FieldMessage`s were way too large, turns out they were not using the `inline` icon variants — designed for use along side text.
- [Current Playroom](https://braid-design-system--f60166d05d5c062eb1ab0163810c36011a2cbdf2.surge.sh/playroom/#?code=PENhcmQ-CiAgPFRleHRGaWVsZAogICAgaWQ9ImlkIgogICAgdG9uZT0icG9zaXRpdmUiCiAgICB2YWx1ZT0iWWVzIgogICAgbGFiZWw9IkRvIHlvdSBsaWtlIEJyYWlkPyIKICAgIG1lc3NhZ2U9Ik5pY2Ugb25lISIKICAvPgogIDxUZXh0RmllbGQKICAgIGlkPSJpZCIKICAgIHRvbmU9ImNyaXRpY2FsIgogICAgdmFsdWU9Ik5vIgogICAgbGFiZWw9IkRvIHlvdSBsaWtlIEJyYWlkPyIKICAgIG1lc3NhZ2U9Ildyb25nIGFuc3dlciIKICAvPgo8L0NhcmQ-Cg)
- [Proposed change](https://braid-design-system--aa2ee3791c9ee8a1454bad31756ebcf6d57074f8.surge.sh/playroom/#?code=PENhcmQ-CiAgPFRleHRGaWVsZAogICAgaWQ9ImlkIgogICAgdG9 …

fix(FieldMessage): Use inline icons

---

lib/components/icons/Icon/Icon.treat.ts
lib/components/icons/Icon/Icon.tsx
lib/hooks/typography/index.ts
lib/hooks/typography/typography.treat.ts

Missed adding `small` support to inline icons because the icons were hard coded. This refactors the icons to be generated from the theme definition for text which should prevent this in the future. Also made the font weights generated from the theme and cleaned up the touchableSpace rules.

fix(Icon): Add 'small' Icon size, tidy up typography

---

lib/themes/makeTreatTheme.ts

This change crept through during [a previous refactor](https://github.com/seek-oss/braid-design-system/pull/211/files#diff-0256d23f06104babde10661fdd7dd085L1) where we originally consolidated the treat theme definition into another file before pulling it back out again and not updating this reference. During this time consumers were not able to infer types generated from the theme as the treat theme override definition was not be imported.
Will look at how best to guard against this in a separate PR.

fix(types): Import theme def override before createTheme

---

lib/components/Checkbox/Checkbox.docs.tsx
lib/components/Checkbox/Checkbox.tsx
lib/components/Dropdown/Dropdown.tsx
lib/components/FieldMessage/FieldMessage.docs.tsx
lib/components/FieldMessage/FieldMessage.tsx
lib/components/Radio/Radio.docs.tsx
lib/components/Radio/Radio.tsx
lib/components/TextArea/TextArea.tsx
lib/components/TextField/TextField.tsx
lib/components/private/Field/Field.tsx
lib/components/private/InlineField/InlineField.tsx

This cleans one of the longstanding quirks of our component API. Rather than having a `message` prop that accepts a string, but also accepts `false` to disable the message, we've separated them into two props: `message`, which is only ever a string, and `reserveMessageSpace`, which is a boolean.
So, rather than writing `<TextField message={false} />`, you now write `<TextField reserveMessageSpace={false} />`.
This also cleans up some other form element API issues, which are documented below.
- `message={false}` no longer works on form fields. Use `reserveMessageSpace={false}` instead.
- `Checkbox` and `Radio` components no longer support `positive` tone. They can only be `critical` or `neutral`.
- `Radio` no longer supports `message` prop, since it can't be used in isolation. If you want …

fix(fields): Use 'reserveMessageSpace={false}', not 'message={false}'

---

lib/components/FieldMessage/FieldMessage.treat.ts
lib/components/FieldMessage/FieldMessage.tsx
lib/themes/wireframe/tokens.ts

BREAKING CHANGE: Reduces the padding below `FieldMessage`. Please validate your app was not depending on this.
This PR brings `FieldMessage` into line with the regional style guides as a better starting point. This will allow for more gradual adoption of form field components while keeping the experience consistent.
Changes include:
- Remove additional white space beyond the default reserved message space
- Make copy and icon `small` rather than `standard`
- `FieldMessage` no longer extends `Text` component api, which was incorrect and did not yield expected result.
- Update wireframe small text definition

fix(FieldMessage): Align size and spacing with other style guides

---

lib/components/FieldMessage/FieldMessage.tsx

We had a slight (single grid row) regression in the min height of a message that was lost amongst [a larger change](https://github.com/seek-oss/braid-design-system/pull/216/files#diff-7921ba9130897fd0697602ce645013eaR62). Result was a slight change in vertical height when a message appears.
Also making the icon conditional to only render when a message is present.

fix(FieldMessage): Correct min height & only render icon with message

---

lib/stories/all.stories.tsx

This should greatly reduce our Chromatic snapshot usage, while also streamlining the review process.
Each component example has a minimum height of `300px`, which should solve the biggest issue with combined screenshots where updates to components higher in the page can cause cascading diffs to the rest of the components.
We're also rendering a divider line below each components so that we can catch differences in surrounding white space, which is otherwise invisible.
I've also removed the `wireframe` theme, since it's not a production theme and any accidental breakages wouldn't really be a big deal.

test(chromatic): Merge snapshots into a single story per component

---

lib/components/private/FieldGroup/FieldGroup.tsx

The `id` is used to associate the field message to the field's in the group but expected behaviour should also apply this `id` to the root element returned — in this case the `fieldset`

fix(FieldGroup): Apply `id` to element

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Button/Button.tsx
lib/components/Dropdown/Dropdown.tsx
lib/components/FieldLabel/FieldLabel.tsx
lib/components/FieldMessage/FieldMessage.tsx
lib/components/Heading/Heading.migration.md
lib/components/Secondary/Secondary.tsx
lib/components/Text/Text.migration.md
lib/components/Text/Text.tsx
lib/components/TextLinkRenderer/TextLinkRenderer.tsx
lib/components/Textarea/Textarea.tsx
lib/components/icons/Icon/Icon.tsx
lib/components/private/InlineField/InlineField.tsx
lib/hooks/typography/index.ts
lib/hooks/typography/typography.treat.ts
lib/themes/makeTreatTheme.ts
lib/themes/seekAnz/tokens.ts
lib/themes/seekAsia/makeTokens.ts
lib/themes/wireframe/tokens.ts
site/src/App/Components/ComponentRoute.tsx

- Text `color` prop is now `tone`.
- Icon `fill` prop is now `tone`.
- `black` and `white` tones have been removed.
```diff
-<Text color="positive">
+<Text tone="positive">
-<TickCircleIcon fill="positive" />
+<TickCircleIcon tone="positive" />
-<Text color="black">
+<Text tone="neutral">
```

feat: Rename color/fill to tone on Text/icons, remove black/white tones

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Alert/Alert.tsx
lib/components/Box/BackgroundContext.ts
lib/components/Box/Box.docs.tsx
lib/components/Box/Box.tsx
lib/components/Button/Button.tsx
lib/components/Card/Card.tsx
lib/components/Column/Column.docs.tsx
lib/components/Columns/Columns.docs.tsx
lib/components/private/Field/Field.tsx
lib/components/private/FieldOverlay/FieldOverlay.tsx
lib/components/private/InlineField/InlineField.tsx
lib/components/private/Overlay/Overlay.tsx
lib/hooks/typography/typography.treat.ts
lib/hooks/useBox/box.treat.ts
lib/hooks/useBox/index.ts
site/src/App/Components/ComponentRoute.tsx

The `backgroundColor` prop on `Box` is now `background`.
```diff
-<Box backgroundColor="brandAccent">
+<Box background="brandAccent">
```

feat(Box): Rename ‘backgroundColor’ prop to ‘background’

---

README.md
generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/BraidProvider/BraidProvider.docs.tsx
lib/components/BraidProvider/BraidProvider.tsx
lib/components/index.ts
lib/playroom/FrameComponent.tsx
lib/stories/all.stories.tsx
site/src/App/App.tsx
site/src/App/Components/ComponentRoute.tsx

`ThemeProvider` has been renamed to `BraidProvider`.
```diff
-<ThemeProvider theme={seekAnz}>
+<BraidProvider theme={seekAnz}>
```

feat: Rename ‘ThemeProvider’ to ‘BraidProvider’

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/FieldLabel/FieldLabel.docs.tsx
lib/components/FieldLabel/FieldLabel.migration.md
lib/components/FieldLabel/FieldLabel.tsx
lib/components/private/Field/Field.tsx
lib/components/private/FieldGroup/FieldGroup.tsx

`id` prop has been renamed to `htmlFor`.
```diff
-<FieldLabel id="someId">
+<FieldLabel htmlFor="someId">
```

feat(FieldLabel): Rename ‘id’ prop to ‘htmlFor’

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Bullet/Bullet.tsx
lib/components/BulletList/BulletList.tsx

`Bullet` and `BulletList` should always have `children` supplied, updating the type def to capture this.

fix(Bullet): Make children required for Bullet & BulletList

---

lib/components/private/InlineField/InlineField.tsx

Fixes the following import error for consumers of `Checkbox` and `Radio`:
```
ERROR in ./node_modules/braid-design-system/lib/components/private/InlineField/InlineField.tsx
Module not found: Error: Can't resolve 'lib/components/Box/BackgroundContext' in '<redacted>/node_modules/braid-design-system/lib/components/private/InlineField'
@ ./node_modules/braid-design-system/lib/components/private/InlineField/InlineField.tsx 14:0-74 75:25-43
@ ./node_modules/braid-design-system/lib/components/Radio/Radio.tsx
```

fix: Resolve import path error in Checkbox and Radio

---

lib/components/Textarea/Textarea.tsx

When `grow` is turned on (default), the field grows with the user as they type (up until the `lineLimit` if defined). This PR returns the field to the initial size when the value is cleared

fix(Textarea): Set to initial 'lines' when value cleared in 'grow' mode

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Dropdown/Dropdown.tsx
lib/hooks/typography/typography.treat.ts
lib/themes/jobStreet/tokens.ts
lib/themes/jobStreetClassic/tokens.ts
lib/themes/jobsDb/tokens.ts
lib/themes/makeTreatTheme.ts
lib/themes/seekAnz/tokens.ts
lib/themes/seekAsia/makeTokens.ts
lib/themes/wireframe/tokens.ts
lib/utils/isLight/index.ts
package.json
yarn.lock

Adds a new `brand` option for the `background` prop on `Box`.
Also fixed a bug with the `Dropdown` chevron colour when nested within a dark background context.
[Playroom demo](https://braid-design-system--9345107f63286824add5c4360c6d1168df2f3deb.surge.sh/playroom/#?code=PEJveAogIGJhY2tncm91bmQ9ImJyYW5kIgogIHBhZGRpbmdUb3A9Im1lZGl1bSIKICBwYWRkaW5nQm90dG9tPSJ4bGFyZ2UiCiAgcGFkZGluZ0xlZnQ9Imd1dHRlciIKICBwYWRkaW5nUmlnaHQ9Imd1dHRlciIKPgogIDxUZXh0RmllbGQgbGFiZWw9IldoYXQiIHJlc2VydmVNZXNzYWdlU3BhY2U9e2ZhbHNlfSAvPgogIDxCb3ggcGFkZGluZ1RvcD0ieHhzbWFsbCIgLz4KICA8RHJvcGRvd24gcmVzZXJ2ZU1lc3NhZ2VTcGFjZT17ZmFsc2V9IC8-CiAgPEJveCBwYWRkaW5nVG9wPSJ4c21hbGwiIC8-CiAgPFRleHRGaWVsZCBsYWJlbD0iV2hlcmUiIHJlc2VydmVNZXNzYWdlU3BhY2U9e2ZhbHNlfSAvPgogIDxCb3ggcGFkZGluZ1RvcD0ibGFyZ2UiIC8-CiAgPEJ1dHRvbiB3ZWlnaHQ9InN0cm9uZyI-C …

feat(Box): Add ‘brand’ background

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/MonthPicker/MonthPicker.treat.ts
yarn.lock

Improved type checking in `typescript@3.5` was causing an issue with vendor prefixed properties, but we were pinned to 3.4. Upgrading all sku dependencies and using the `VendorLonghandProperty` format as a fix.

fix: Change '-webkit-appearance' to 'WebkitAppearance' to fix type error

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Heading/Heading.docs.tsx
lib/components/Heading/Heading.migration.md
lib/components/Heading/Heading.tsx
lib/hooks/typography/typography.treat.ts
lib/themes/makeTreatTheme.ts
lib/themes/seekAnz/tokens.ts
lib/themes/seekAsia/makeTokens.ts
lib/themes/wireframe/tokens.ts

Introduces a new level of `Heading` to sit in between our current lowest level and large `Text`.
```jsx
<Heading level="4">Title</Heading>
```
Preview in [Playroom](https://braid-design-system--5a2dfb4498292a55c33555ad5bac28918af51661.surge.sh/playroom/#?code=PENhcmQ-CiAgPFBhcmFncmFwaD4KICAgIDxIZWFkaW5nIGxldmVsPSIxIj5IZWFkaW5nIExldmVsIDE8L0hlYWRpbmc-CiAgICA8VGV4dD5Mb3JlbSBpcHN1bSBkb2xvciBzaXQgYW1ldCwgY29uc2VjdCBhZGlwaXNjaW5nIGVsaXQsIHNlZCBkbyBlaXVzbW8gdGVtcG9yIGluY2lkaWR1bnQgdXQgbGFib3JlIGV0IGRvbG9yZSBtYWduYS48L1RleHQ-CiAgPC9QYXJhZ3JhcGg-CiAgPFBhcmFncmFwaD4KICAgIDxIZWFkaW5nIGxldmVsPSIyIj5IZWFkaW5nIExldmVsIDI8L0hlYWRpbmc-CiAgICA8VGV4dD5Mb3JlbSBpcHN1bSBkb2xvciBzaXQgYW1ldCwgY29uc2VjdCBhZGlwaXNjaW5nIGVsaXQsIHNlZCBkbyBlaXVzbW8gdGVtcG9yIGluY2lkaWR1bnQgdXQgbGFib3JlIGV0IGRvbG9yZSBtYWduYS48L1RleHQ- …

feat(Heading): Add level `4`

---

lib/hooks/typography/typography.treat.ts

We're currently experiencing issues with text styles in production mode. We're currently investigating, but in the meantime, reverting to `styleMap` instead of `styleTree` fixes the issue.

fix: Fix text styles

---

lib/hooks/typography/typography.treat.ts
lib/utils/isLight/index.ts

Previously we implemented custom logic for determining if a colour was light that was simply a subjective adjustment of a magic number luminance threshold. As it turns out there is an alternative research-based approach that leverages the [YIQ colour space](https://en.wikipedia.org/wiki/YIQ).
For further reading checkout this post on [Calculating Color Contrast](https://24ways.org/2010/calculating-color-contrast/).
Thanks to @patrickliu-sa for pointing us in this direction.

refactor: Use YIQ color space to determine if color is light

---

lib/components/Box/Box.tsx
lib/components/Checkbox/Checkbox.tsx
lib/components/Dropdown/Dropdown.tsx
lib/components/Radio/Radio.tsx
lib/components/TextField/TextField.tsx
lib/components/Textarea/Textarea.tsx
lib/themes/wireframe/tokens.ts
site/src/App/Components/ComponentRoute.tsx

Since implementing `forwardRef` in some components the docs site code snippets and the React Dev Tools experience has been a little broken/hard to use. This mitigates both problems by providing the display name explicitly where we have had to forward refs.

fix: Add display names to components forwarding refs

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/FieldLabel/FieldLabel.docs.tsx
lib/components/Heading/Heading.tsx
lib/components/Heading/HeadingContext.ts
lib/components/Text/Text.tsx
lib/components/Text/TextContext.ts
lib/components/TextField/TextField.docs.tsx
lib/components/TextLink/TextLink.docs.tsx
lib/components/TextLink/TextLink.tsx
lib/components/TextLinkRenderer/TextLinkRenderer.docs.tsx
lib/components/TextLinkRenderer/TextLinkRenderer.tsx
lib/components/TextLinkRenderer/TextLinkRendererContext.ts
lib/components/Textarea/Textarea.docs.tsx
lib/hooks/typography/index.ts
site/src/App/Components/Link.tsx

The `inline` prop has been removed from `TextLinkRenderer`/`TextLink` in favour of contextual inference.
```diff
-<Text>The next word is a <TextLink inline>link.</TextLink></Text>
+<Text>The next word is a <TextLink>link.</TextLink></Text>
```
Block level usage of `TextLinkRenderer`/`TextLink` must now contain a Text node.
```diff
-<TextLink>Link text</TextLink>
+<TextLink><Text>Link text</Text></TextLink>
```

feat(TextLinkRenderer): Remove 'inline' prop, fix heading styles

---

lib/components/Button/Button.treat.ts

This transition is already provided by `FieldOverlay`, which renders an `Overlay` with `transition="fast"`.
This doesn't meaningfully impact consumers, apart from a minuscule drop in CSS size, so decided to mark this as a refactor.

refactor(Button): Remove redundant CSS transition

---

lib/themes/applyReset.ts
lib/themes/jobStreet/index.ts
lib/themes/jobStreetClassic/index.ts
lib/themes/jobsDb/index.ts
lib/themes/seekAnz/index.ts
lib/themes/wireframe/index.ts

Fixing an underlying issue that has been present since `v0.0.80`, whereby consumers building an app that leverages dynamic imports for theming would fail.
```
ERROR in chunk braid-design-system-themes-wireframe
braid-design-system-themes-wireframe-24048686048bcd1a27f9.js
<...>/node_modules/braid-design-system/lib/themes/applyReset.ts
RuntimeTemplate.moduleId(): Module <...>/braid-design-system/lib/hooks/useBox/reset.treat.ts has no id. This should not happen.
```
Seems to be triggering an issue in webpack where the `applyReset` module containing only side effect code. Refactoring the importing of reset avoids the issue and enables consumers to build using dynamic imports of themes.

fix: Import reset directly, fixes dynamic theme import error

---

lib/hooks/useBox/reset.treat.ts

Identified by classnames in dev not using correct debug ident names, it seems the reset was importing treat directly rather than via sku. Will likely implement a lint rule to capture this in the future.

fix(reset): Import treat from sku

---

lib/hooks/useBox/reset.treat.ts

The native style sheet for a `<button>` includes a background color of `white`. When using `<Box component="button" />` it would be expected that the component reset takes care of this.

fix(Reset): Remove default background color on `button`

---

lib/hooks/useBox/reset.treat.ts

Both `TextField` and `Textarea` were not displaying their field border on iOS Safari. This was due to not resetting the `appearance` CSS property on `input` and `textarea` elements, resulting in style clashes.

fix: Ensure TextField & Textarea borders show on iOS

---

lib/components/Dropdown/Dropdown.docs.tsx
lib/components/Dropdown/Dropdown.tsx
lib/components/Heading/Heading.docs.tsx
lib/components/Secondary/Secondary.tsx
lib/components/Text/Text.docs.tsx
lib/components/TextField/TextField.docs.tsx
lib/components/TextLinkRenderer/TextLinkRenderer.tsx
lib/components/icons/Icon/Icon.tsx
lib/components/private/Field/Field.tsx
lib/hooks/typography/index.ts
lib/hooks/typography/typography.treat.ts
site/src/App/Components/ComponentRoute.tsx
site/src/types.d.ts

This fixes an issue where text within a `TextField`, `Dropdown` or `Textarea` was white when nested within a `Box` with a dark background (e.g. `<Box background="brand">`).
This PR also ensures that text provides adequate contrast against all `Box` backgrounds.
Before: 
After:
This issue was caused by the way `Field` works, where we pass classes down to the target field via render props. As a result, the white background of the field wasn't available on context within the `useTextTone` hook, so it was using the background context defined higher in the tree.
To fix this issue, the `useText`, `useHeading` and `useTextTone` hooks now support an optional `backgroundContext` override for times like this where it's not possible to provide a missing context value when using hooks.
I've also …

fix: Make field text visible within dark background context

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Alert/Alert.tsx
lib/components/FieldMessage/FieldMessage.tsx
lib/components/private/examplesForIcon.tsx
lib/hooks/typography/typography.treat.ts
lib/hooks/useIcon/icon.treat.ts
lib/hooks/useIcon/index.ts
site/src/App/Code/Code.tsx

Removes `inline` in favour of inferring this from the context of use. Nesting an icon inside a `<Text>` or `<Heading>` component will determine its size and position — no longer requiring the `inline` modifier or allowing a `size` that differs from the parent text.
An example migration, ie. determined as inline based on it being a child of `<Text>`.
```diff
<Text>
-  An inline icon <Icon inline />  amongst text
+  An inline icon <Icon />  amongst text
</Text>
```
An example migration, ie. determined as being `size="large"` based on it being a child of `<Text size="large">`.
```diff
<Text size="large">
-  An large icon <Icon size="large" />  amongst large text
+  An large icon <Icon />  amongst large text
</Text>
```
Note: Having different sizes is no longer permitted. Eg: 
```diff
<Text …
```

feat(Icons): Remove `inline` & infer size from usage

---

lib/components/Dropdown/Dropdown.treat.ts

Rectifies an issue where the chevron within the `Dropdown` component is oversized on mobile devices. This is a result of using the `fill` size for the icon without a horizontal constraint being provided to the container.

fix(Dropdown): Resolve oversized chevron on iOS

---

lib/themes/seekAnz/tokens.ts

For the `seekAnz` theme, this increases our line height for `<Heading level="4">` and `<Text size="large">` from `24px` (4 grid rows) to `30px` (5 grid rows).
**This may impact existing designs. Please ensure that any visual changes are reviewed before upgrading.**
---

fix: Increase line height for H4 and large text in 'seekAnz'

---

lib/components/Text/Text.tsx

Because we're passing an object to the `TextContext` provider, it will fail a reference equality check against the last render, which will then trigger a re-render of all `TextContext` consumers. To fix this, we now ensure that the context value object is memoized across renders using [`useMemo`](https://reactjs.org/docs/hooks-reference.html#usememo).

fix(Text): Ensure text context values are memoized

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/BraidLoadableProvider/BraidLoadableProvider.docs.tsx
lib/components/BraidLoadableProvider/BraidLoadableProvider.tsx
lib/components/BraidProviderLoadable/BraidProviderLoadable.tsx
lib/components/index.ts

`BraidLoadableProvider` is a code-splitting enabled alternative to `BraidProvider`.

feat: Add BraidLoadableProvider component

---

generate-component-docs/__snapshots__/contract.test.ts.snap
generate-component-docs/contractSerialiser.ts

In an another branch, I was getting pointless snapshot diffs with changes to the ordering of union types. Decided it would make more sense to ensure a consistent order for union types, regardless of source order.

test: Sort union types in contract test snapshots

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Badge/Badge.docs.tsx
lib/components/Badge/Badge.migration.md
lib/components/Badge/Badge.tsx
lib/hooks/typography/typography.treat.ts
lib/hooks/useBox/box.treat.ts
lib/themes/makeTreatTheme.ts
lib/themes/seekAnz/tokens.ts
lib/themes/seekAsia/makeTokens.ts
lib/themes/wireframe/tokens.ts
site/src/App/Code/Code.tsx

BREAKING CHANGE: The `secondary` tone for `Badge` has been renamed to `neutral`, as a side effect the `background` property on `Box` has also been updated — `secondary` to `neutral` and `secondaryLight` to `neutralLight`.
Following the definition of the global colour usage chart, we are aligning our current component apis to suit. The colour usage chart is designed to map the usage of colour with tone of voice used around the system, to give users a more balanced experience.
We have modelled this consistently already with `critical`, `positive` and `info`. This PR gets alignment for `neutral`, while leaving room to add `promote`, `warning`, `notice` etc.
This changed affects two public interfaces:
```diff
-<Badge tone="secondary">
+<Badge tone="neutral">
Expired
</Badge>
```
```diff
-<Box …
```

fix: Rename Badge tone & background `secondary` to `neutral`

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Autosuggest/Autosuggest.test.tsx
lib/components/Autosuggest/Autosuggest.tsx

For example, if you select a suggestion that looks like this:
```js
{
text: 'Apples',
value: 123,
highlights: [{ start: 0, end: 4 }]
}
```
The following object will be sent to your `onChange` function:
```js
{
text: 'Apples',
value: 123
}
```
I've updated the test suite so that every example now provides `highlights`, which ensures that these values are being filtered correctly.

fix(Autosuggest): Exclude ‘highlights’ from ‘onChange’ values

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Box/Box.tsx
lib/components/Button/Button.treat.ts
lib/components/Button/Button.tsx
lib/components/Dropdown/Dropdown.treat.ts
lib/components/Dropdown/Dropdown.tsx
lib/components/FieldLabel/FieldLabel.treat.ts
lib/components/FieldLabel/FieldLabel.tsx
lib/components/FieldMessage/FieldMessage.treat.ts
lib/components/FieldMessage/FieldMessage.tsx
lib/components/TextLinkRenderer/TextLinkRenderer.treat.ts
lib/components/TextLinkRenderer/TextLinkRenderer.tsx
lib/components/Toggle/Toggle.treat.ts
lib/components/Toggle/Toggle.tsx
lib/components/private/InlineField/InlineField.treat.ts
lib/components/private/InlineField/InlineField.tsx
lib/components/private/Overlay/Overlay.treat.ts
lib/components/private/Overlay/Overlay.tsx
lib/components/private/examplesForIcon.tsx
lib/hooks/useBox/box.treat.ts
lib/hooks/useBox/index.ts
site/src/App/Code/Code.treat.ts
site/src/App/Code/Code.tsx
site/src/App/Components/Components.treat.ts
site/src/App/Components/Components.tsx
site/src/App/Home/Home.treat.ts
site/src/App/Home/Home.tsx
site/src/App/MenuButton/MenuButton.treat.ts
site/src/App/MenuButton/MenuButton.tsx

Adds the following options to `Box`:
- `alignItems={'center' | 'flexStart' | 'flexEnd'}`
- `justifyContent={'center' | 'flexStart' | 'flexEnd' | 'spaceBetween'}`
- `width="touchable"`
- `height="touchable"`
- `borderRadius="full"`
- `cursor="pointer"`
- `pointerEvents="none"`
Note that `alignItems` and `justifyContent` are responsive props, which means that you can also provide an array of values for mobile and desktop, e.g.
```
<Box alignItems={['center', 'flexStart']}>
```

feat(Box): Support flex align, touchable size, full border radius

---

lib/themes/seekAsia/makeTokens.ts

The themes based on the `SeekAsia`, e.g. `JobsDB`, `JobStreet` & `JobStreetClassic`, all specify the `Muli` font as their preferred font family. The current theme sets the medium font weight to 500 which does not exist in this font.
Setting to 600 to align with the weight scale correctly.

fix(seekAsia): Increase medium font weight to 600

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Bullet/Bullet.docs.tsx
lib/components/Bullet/Bullet.treat.ts
lib/components/Bullet/Bullet.tsx
lib/components/BulletList/BulletList.tsx
lib/components/Column/Column.docs.tsx
lib/components/Text/Text.tsx
lib/hooks/useBox/index.ts

BREAKING CHANGE: Setting `component="li"` on `Text` no longer renders a bullet. Please migrate to `Bullet`. Also no longer renders white space after the last `Bullet`, please validate your usage.
See usage: https://seek-oss.github.io/braid-design-system/components/BulletList.
Setting the `component` prop on `Text` to `"li"` no longer renders a bullet list item. Consumers depending on this behaviour should migrate to `Bullet` and leverage the new apis on `BulletList` to achieve the desired outcome.
Consumers using `Text` instead of `Bullet` to support customising the text size should now migrate to `Bullet` and set the `size` on `BulletList` as follows:
```diff
-<BulletList>
+<BulletList size="small">
-  <Text component="li" size="small">...</Text>
+  <Bullet>...</Bullet>
...
</BulletList> …
```

feat(BulletList): Add support for changing text size & bullet spacing

---

docs/Style Guide Migration.md
generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/ContentBlock/ContentBlock.docs.tsx
lib/components/ContentBlock/ContentBlock.migration.md
lib/components/ContentBlock/ContentBlock.treat.ts
lib/components/ContentBlock/ContentBlock.tsx
lib/components/index.ts
lib/themes/makeTreatTheme.ts
lib/themes/seekAnz/tokens.ts
lib/themes/seekAsia/makeTokens.ts
lib/themes/wireframe/tokens.ts

This serves as the Braid replacement for SEEK Style Guide's [`PageBlock`](https://seek-oss.github.io/seek-style-guide/page-block), providing a centred container with a max-width.
This also adds support for wider page layouts via the `width` prop, e.g. `<ContentBlock width="large">...</ContentBlock>`

feat(ContentBlock): Add 'ContentBlock' component

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Button/Button.tsx
lib/components/ButtonRenderer/ButtonRenderer.docs.tsx
lib/components/ButtonRenderer/ButtonRenderer.treat.ts
lib/components/ButtonRenderer/ButtonRenderer.tsx
lib/components/index.ts

This component allows you to render elements that _look_ like buttons but actually aren't.
Most notably, this is to support links as buttons. For example, if you wanted to render a button that's actually a React Router link:
```js
<ButtonRenderer>
{(ButtonChildren, buttonProps) => (
<Link to="#" {...buttonProps}>
<ButtonChildren>Link button</ButtonChildren>
</Link>
)}
</ButtonRenderer>
```

feat(ButtonRenderer): Add ButtonRenderer component

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Autosuggest/Autosuggest.tsx
lib/themes/baseTokens/seekAnz.ts
lib/themes/baseTokens/seekAsia.ts
lib/themes/baseTokens/seekAsiaRebrand.ts
lib/themes/makeTreatTheme.ts
lib/themes/wireframe/tokens.ts

Introduce a full scale for box-shadow usage to better demonstrate elevation between different components.
Box shadow scale:
- small __(new)__ 
- Examples: Cards, content containers, etc
- medium __(new)__
- Examples: Overflow menus, Autosuggest list, etc
- large
- Examples: Toasts, sticky/fixed components, etc
[Playroom](https://braid-design-system--15a8f2904a1968fc6f7690d9bc32016657c0c643.surge.sh/playroom/#?code=PEJveCBiYWNrZ3JvdW5kPSJjYXJkIiBwYWRkaW5nPSJtZWRpdW0iPgogIDxTdGFjayBzcGFjZT0ieGxhcmdlIj4KICAgIDxCb3ggc3R5bGU9e3sgYm94U2hhZG93OiAiMCA5cHggMzBweCByZ2JhKDAsMCwwLC40KSIgfX0gcGFkZGluZz0ibWVkaXVtIj4KICAgICAgPFRleHQ-TGFyZ2UgKG9sZCk8L1RleHQ-CiAgICA8L0JveD4KICAgIDxEaXZpZGVyIC8-CiAgICA8Qm94IGJveFNoYWRvdz0ic21hbGwiIHBhZGRpbmc9Im1lZGl1bSI-CiAgICAgIDxUZXh0PlNtYWxsPC9UZXh0PgogICAgPC9Cb3g-CiAgIC …

feat: Add full box shadow scale

---

lib/themes/baseTokens/seekAsiaRebrand.ts

There are several component spec updates on jobsDB Rebrand theme, which cascaded from `seekAsiaRebrand` and will be adapted by jobStreet when rebranding takes place.
1. `<Strong>`: From **Bold** to **ExtraBold**
2. `<Text>`: Normal size lineHeight set from **20px** to **24px** instead
3. `<Button>` and `<TextField>`: Height from **48px** to **44px**

fix(jobsDbRebrand): Update token values

---

lib/themes/baseTokens/seekAnz.ts
lib/themes/wireframe/tokens.ts

This is designed to enable much larger selection areas—not just small elements like suggestions in `Autosuggest`.
Before: 
After:

fix(seekAnz): Change selection colour from grey to blue

---

lib/components/OverflowMenu/OverflowMenu.tsx
lib/components/OverflowMenuItem/OverflowMenuItem.tsx

Click events should never bubble out of the `OverflowMenu` component. This can cause issues when the menu is inside a clickable container. Stopping propagation of the event prevents the click handler of the parent container firing.

fix(OverflowMenu): Stop click events from bubbling

---

lib/components/Column/Column.tsx

Allows consumer to vertically center elements within column layouts by ensuring all `Column` components are full height. See [Playroom example](https://braid-design-system--612777060c8ea61789940cee47313560ee491317.surge.sh/playroom/#?code=N4Igxg9gJgpiBcIA8BhCAbArgWwHYGcA+AHVwAIzUMdcTyLKAhCADzICMBDMAawHMAThEy4oAXmIhcMTABcBndJLIB3AJZRZACwkgAZpnRKQZfLICe6GGODAyWmGr5bZ8MpIDMAJgAMABxZlAF8gsgB6OgokMLQsPEjKWJoEqOY2BycXXQMjZSg1fD90TnNsq0CTRSdcAElZGGx8XTAYXHqBSRSGJAAVGBZZUzUAL2tJYoE+GE6UVvayKr5pKDIANxgBWTUwRXRzBfQIXD58DRgh9nQ1Y7JIONxovoGu6LSE6KT40g-qPCJSEBBIA)

fix(Column): Support full height content

---

generate-component-docs/__snapshots__/contract.test.ts.snap
generate-component-docs/generate.ts
package.json
site/src/App/Documentation/ComponentProps.tsx
yarn.lock

When performing lock file maintenance, our `generate-component-docs` script appeared to start getting caught in a loop and blowing the stack. I've altered the way the script and documentation works to avoid this. I also had to upgrade sku to fix an issue with the latest version of TypeScript.

chore: Update sku and lock file, fix type doc generation

---

lib/utils/resolveResponsiveProp.ts
site/src/App/Documentation/Documentation.tsx

Currently, the following code fails to type check:
```
const responsiveSpace = ['small', 'large'] as const;
<Box padding={responsiveSpace} />
```
This code causes the following type error: `The type 'readonly ["small", "large"]' is 'readonly' and cannot be assigned to the mutable type '[Space, Space]'.`
This PR fixes this by marking responsive prop arrays as `Readonly`.

fix: Support 'readonly' arrays for responsive props

---

lib/components/Autosuggest/Autosuggest.tsx
lib/components/Textarea/Textarea.treat.ts
lib/components/private/Field/Field.tsx
lib/components/private/FieldOverlay/FieldOverlay.tsx
lib/components/private/InlineField/InlineField.tsx
lib/components/private/Overlay/Overlay.treat.ts
lib/components/private/Overlay/Overlay.tsx

For some reason, IE11 doesn't render inset box shadows on `textarea` elements. To fix this, I've converted the border to a `FieldOverlay`, like all the other states.

fix(Textarea): Ensure default border is visible in IE11

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Button/Button.tsx

Adds support for passing data attributes to `Button` components, eg:
```jsx
<Button data={{ testId: 'save' }}>
Save
</Button>
// => <button data-testId="save">Save</button>
```

fix(Button): Support data attribute mapping

---

lib/utils/resolveResponsiveProp.ts

The `instanceof Array` check returns false when the array was generated in a different global context, i.e. there are multiple `Array` globals in play. This fixes it by using `Array.isArray()` instead.

fix: Ensure responsive props work in dynamically loaded chunks

---

lib/components/Toggle/Toggle.treat.ts
lib/components/Toggle/Toggle.tsx
lib/components/private/Field/Field.treat.ts
lib/components/private/InlineField/InlineField.treat.ts
lib/components/private/InlineField/InlineField.tsx

Also removes the unnecessary z-index elevation to field icons for `TextField`, `Dropdown` & `Autosuggest`.

fix: Scope z-index elevations in Toggle, Checkbox & Radio

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Bullet/Bullet.tsx
lib/components/Columns/Columns.docs.tsx
lib/components/Columns/Columns.tsx
lib/components/Inline/Inline.docs.tsx
lib/components/Inline/Inline.tsx
lib/components/Stack/Stack.docs.tsx
lib/components/Stack/Stack.tsx
lib/utils/align.ts
lib/utils/responsiveProp.test.ts
lib/utils/responsiveProp.ts

This adds alignment support to our suite of layout components. `Stack` and `Inline` can now align content horizontally via the `align` prop, and `Columns` can manage vertical alignment via `alignY`.
All of these props are also responsive, making it easy to customise alignment across multiple screen sizes.
```
<Stack space="small" align="center">...</Stack>
<Stack space="small" align={['center', 'left']}>...</Stack>
<Inline space="small" align="center">...</Stack>
<Inline space="small" align={['center', 'left']}>...</Inline>
<Columns space="small" alignY="center">
<Column>...</Column>
<Column>...</Column>
<Column>...</Column>
</Columns>
```

feat: Add "align" to Stack and Inline, add "alignY" to Columns

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/TextLink/TextLink.docs.tsx
lib/components/TextLink/TextLink.tsx
lib/components/TextLinkRenderer/TextLinkRenderer.treat.ts
lib/components/TextLinkRenderer/TextLinkRenderer.tsx
lib/hooks/typography/typography.treat.ts
lib/themes/baseTokens/seekAnz.ts
lib/themes/baseTokens/seekAsia.ts
lib/themes/baseTokens/seekAsiaRebrand.ts
lib/themes/makeTreatTheme.ts
lib/themes/wireframe/tokens.ts

In order to support visited link styles, you can now pass a `showVisited` boolean prop to `TextLink` and `TextLinkRenderer`.
Example usage:
```tsx
<TextLink showVisited href="/">...</TextLink>
```

feat(TextLink): Add support for visited link styles

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Loader/Loader.docs.tsx
lib/components/Loader/Loader.treat.ts
lib/components/Loader/Loader.tsx

Move the delayed presentation of the `Loader` to being opt-in via a prop rather than default behaviour. The delay is useful for scenarios where showing a loading indicator can hurt user perceived performance.

fix(Loader): Show instantly, add delayVisibility to prevent flicker

---

lib/components/Autosuggest/Autosuggest.playroom.tsx
lib/components/Checkbox/Checkbox.playroom.tsx
lib/components/Checkbox/Checkbox.tsx
lib/components/Dropdown/Dropdown.playroom.tsx
lib/components/Dropdown/Dropdown.tsx
lib/components/MonthPicker/MonthPicker.playroom.tsx
lib/components/MonthPicker/MonthPicker.tsx
lib/components/Radio/Radio.playroom.tsx
lib/components/Radio/Radio.tsx
lib/components/TextField/TextField.playroom.tsx
lib/components/TextField/TextField.tsx
lib/components/Textarea/Textarea.playroom.tsx
lib/components/Textarea/Textarea.tsx
lib/components/Toggle/Toggle.playroom.tsx
lib/playroom/components.ts
lib/playroom/utils.ts
package.json
yarn.lock

This PR loosens the requirements on interactive components so that `id`, `value`/`checked`/`on` and `onChange` props are optional. This is achieved via wrapper components that generate the missing props for you, if required. 
This ensures that components in Playroom behave the same as production, even when props have been omitted—as opposed to relying on React's uncontrolled form element behaviour, which our components have not been designed to support.

docs: Add fallback props for interactive components in Playroom

---

lib/components/TextLink/TextLink.playroom.tsx
lib/playroom/components.ts

This ensures that, when prototyping, `TextLink` components are interactive even when an `href` hasn't been provided. This also prevents an extra history entry by calling `event.preventDefault()` in the fallback click handler.

docs(Playroom): Provide fallback behaviour for TextLink

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Stack/Stack.test.tsx
lib/components/Stack/Stack.tsx

This adds a `component` prop to `Stack` to customise the wrapper element, and if `ol` or `ul` are specified, each stack item is wrapped in an `li` element rather than a `div`.
For now, only `div`, `ol` and `ul` are supported. Any other values will throw an error in dev mode.
Because this is quite easy to break and can't be picked up in a visual test, I've added a few Jest tests to ensure the semantics are being managed correctly.

feat(Stack): Allow Stacks to be semantic lists

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Tiles/Tiles.docs.tsx
lib/components/Tiles/Tiles.treat.ts
lib/components/Tiles/Tiles.tsx
lib/components/index.ts
lib/utils/responsiveProp.ts
site/src/App/foundations/layout/layout.tsx

This introduces a new layout component called `Tiles` which allows you to freely flow content while defining the desired number of columns.
For example, if you wanted a 3 column grid layout with "medium" space:
```jsx
<Tiles columns={3} space="medium">
<Card>...</Card>
<Card>...</Card>
<Card>...</Card>
<Card>...</Card>
<Card>...</Card>
<Card>...</Card>
</Tiles>
```
[Playroom demo](https://braid-design-system--6b46b74c24f384e2f0cc3907fa8fdbd871ad2f75.surge.sh/playroom/#?code=N4Igxg9gJgpiBcIA8AVAlgGxgZwASQwFcBbAO2wF5gBmAX12wAcBDMGCgHRGJijRK4A+DqVy4kAYWYAnKIIB0ipAHops4aPFq5i+Su0axkmTqWqThrRd36LIowZvn19q+qcGRK9FmyCQADQgAC4AFjA82AgA2iDYMDAA1gCCpABeIAC6tEA)
---
The `columns` prop is also responsive, allowing you to specify the number of columns for each screen size.
For example, if you wanted …

feat(Tiles): Add ‘Tiles’ layout component

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Badge/Badge.treat.ts
lib/components/Badge/Badge.tsx
lib/components/Box/Box.tsx
lib/components/Box/useBoxStyles.treat.ts
lib/components/Box/useBoxStyles.ts
lib/components/ButtonRenderer/ButtonRenderer.treat.ts
lib/components/ButtonRenderer/ButtonRenderer.tsx
lib/components/Heading/Heading.docs.tsx
lib/components/Heading/Heading.tsx
lib/components/Text/Text.docs.tsx
lib/components/Text/Text.tsx
lib/components/Toggle/Toggle.treat.ts
lib/components/Toggle/Toggle.tsx
lib/hooks/typography/index.ts
lib/hooks/typography/typography.treat.ts
site/src/App/Documentation/Documentation.treat.ts
site/src/App/Documentation/Documentation.tsx

Adds the ability to truncate long running text with an ellipsis to support instances where text wrapping is not desired.
```jsx
<Text truncate>
Long heading
</Text>
```
or
```jsx
<Heading level="2" truncate>
Long heading
</Heading>
```
[Playroom demo](https://braid-design-system--5be8ab2c7558d4a5c4efee3dd17beca59272ae8c.surge.sh/playroom/#?code=N4Igxg9gJgpiBcIA8BhAhgJygPgDoDsACQpAZQBc0wBrQgZwAcqYBeXEAG0wHMZ28ixEiggcArgFt8dekzCt2EmFACWk-gSFDUoyfgFatSABIw0q-N0IcYANxgc2IAMztC5DGPxg05GAcMtABkIS0IACzMLK3Jw30IAdxhCKFDyRLR8dPIIRIw0Bk1AkgB6U3MVSwCjEpFxKWrtOr1ElShYp0gsmCyNQUCkAHl7DAAzDggEgFkesUaB4ZgxienZgEk-CWwAEQcYPyQSxeXJmfwxDZgtooGjkfHT2fnS5oabl90pOgF3skoaWTMJx0CRoDgcPoDAAqMAAHtlQgoQHQYF0oJgAJ5uDxeHx+Z7EJBrLohPEqUKEErYQgAJTM4Ix1lCVgYKlRyQgo3ccOycXSSRSaQyWXcuQS+UK-W0JRh8J+UsJsoR+CRKLRmOxnm8vn87yM …

feat: Add truncate support to Text and Heading

---

generate-component-docs/__snapshots__/contract.test.ts.snap
generate-component-docs/generate.ts
lib/components/Inline/Inline.tsx
lib/components/Stack/Stack.tsx
lib/components/Tiles/Tiles.tsx
lib/components/private/FieldGroup/FieldGroup.tsx
lib/components/private/ReactNodeNoStrings.ts
site/src/App/TextStack/TextStack.tsx

This change is designed to highlight the issue of accidentally passing strings to Layout components. This can happen unintendedly when using conditional rendering logic with potentially empty strings. 
e.g.
```jsx
// when description = ''
<Stack space="small">
{description && <Text>{description}</Text>}
</Stack>
```

fix(Stack,Inline,Tiles): Disallow strings as children

---

package.json
site/src/App/App.tsx
site/src/client.tsx
yarn.lock

There are a few issues with our current scroll position management solution that this aims to address:
- During development, hot reload resets your scroll position to the top.
- Clicking back or forwards also resets your scroll position to the top.
- The animated `scrollTo` call causes you to momentarily maintain your existing scroll position when navigating to a new page.
Instead, by using [react-router-scroll-memory](https://www.npmjs.com/package/react-router-scroll-memory), our scroll management now behaves much more like a traditional non-SPA site.

docs: Manage scroll position with 'react-router-scroll-memory'

---

lib/components/private/Placeholder/Placeholder.tsx

For example:
```tsx
<Placeholder width={80} height={80} shape="round" label="Logo" />
```
*(If you're wondering why it's not called `"circle"`, it's because it's not necessarily a circle, e.g. `<Placeholder width={160} height={80} shape="round" />`)*

chore(Playroom): Add support for round placeholders

---

lib/components/Toggle/Toggle.treat.ts
lib/components/Toggle/Toggle.tsx
lib/components/private/InlineField/InlineField.treat.ts
lib/components/private/InlineField/InlineField.tsx
lib/components/private/touchable/debugTouchable.ts
lib/components/private/touchable/hitArea.ts
lib/components/private/touchable/useVirtualTouchable.treat.ts
lib/components/private/touchable/useVirtualTouchable.ts

BREAKING CHANGE: Layout changes will be required.
Checkbox, Radio and Toggle components currently reserve surrounding white space to ensure that they satisfy a minimum touchable size. Unfortunately, this clashes with our layout philosophy of first-class white space via layout components.
In order to fix this problem, we've made the hit targets absolute so that the empty space isn't part of the document flow. For example:
Before:
After:
Since this introduces the risk of overlapping hit targets where the user may inadvertently activate the wrong element, you should ensure that there is enough surrounding white space. Generally this is already the case since this is standard design practice, particularly when designing for mobile, but it's worth being aware of.
To help debug this in …

fix(Checkbox,Radio,Toggle): Remove space around fields

---

lib/components/Box/Box.tsx
lib/components/Box/useBoxStyles.ts

Sometimes we call `useBoxStyles` when we don't have knowledge or control over the node being rendered. This means we end up applying two resets or an incorrect reset. This PR allows you to explicitly pass `component: null` to `useBoxStyles`, skipping the reset styles. 
This PR also changes the prop conditions to check equality against `undefined` rather than falsy. This is a smidge faster (roughly 3%), worth it in such a hot path.

chore: Allow disabling of reset on useBoxStyles

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Bullet/Bullet.docs.tsx
lib/components/Bullet/Bullet.tsx
lib/components/TextLink/TextLink.docs.tsx
lib/components/TextLink/TextLink.tsx
lib/components/TextLinkRenderer/TextLinkRenderer.tsx
lib/hooks/typography/index.ts
site/src/App/Documentation/Documentation.tsx

- Block-level `TextLink`/`TestLinkRenderer` components no longer occupy full touchable height in the document flow. You will need to add a `hitArea="large"` prop and reintroduce white space via layout components.
- All `TextLink`/`TestLinkRenderer` components must now be nested within a `Text` component.
**When TextLink is mentioned below, it refers to both the `TextLink` and `TextLinkRenderer` components.**
Previously Braid had two different TextLink implementations, depending on whether it was nested within a `Text` component or not. The thinking was, TextLinks that are not part of a sentence should reserve surrounding white space to ensure that they satisfied a minimum touchable size. The documentation referred to these as "block links".
Unfortunately, this clashes with our layout …

fix(TextLink,TextLinkRenderer): Remove surrounding space, add hitArea prop

---

lib/reset/reset.treat.ts

This PR removes the rectangular overlay that flashes over the top of interactive elements when tapping on them on mobile. This is something that was provided by previous style guide work but was missed when migrating to Braid.

fix: Disable WebKit tap highlight

---

lib/components/FieldMessage/FieldMessage.tsx
lib/components/MonthPicker/MonthPicker.tsx
lib/components/Textarea/Textarea.docs.tsx
lib/components/private/Field/Field.tsx

The character count was not rendering when approaching or exceeding the limit due to a falsey check on the rendering conditions around the field message.
Also adding `displayname` to `MonthPicker` to fix docs site code examples.

fix(Textarea): Show character count correctly

---

lib/components/Textarea/Highlight/Highlight.treat.ts
lib/components/Textarea/Textarea.treat.ts
lib/components/Textarea/Textarea.tsx
lib/components/Textarea/formatRanges.tsx

Some small issues with the new `highlightRanges` feature on `Textarea`. Highlighted ranges now scroll with the textarea on scroll and on change of the textarea. Also fixed a white space wrapping bug where the highlights could get out of sync with the textarea value.

fix(Textarea): Better scroll support for highlighted ranges

---

lib/components/Textarea/Highlight/Highlight.treat.ts
lib/components/Textarea/formatRanges.test.ts
lib/components/Textarea/formatRanges.tsx

Improving the logic powering the textarea highlights. New edge cases handled:
- Range where end character is before the start character is ignored
- Better handling for multiple ranges where some are invalid
- Sort ranges by their start point
- Handle overlapping adjoining by merging them into a single adjoining range.

fix(Textarea): Handle edge case highlight ranges

---

lib/components/TextLinkRenderer/TextLinkRenderer.treat.ts

This most notably improves the rendering of links within `Alert` components.
Before:
After:

fix(TextLink): Visually lower underline when permanently visible

---

lib/components/Rating/Rating.tsx

fix(Rating): Remove surrounding space

---

generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Tiles/Tiles.docs.tsx
lib/components/Tiles/Tiles.treat.ts
lib/components/Tiles/Tiles.tsx
lib/utils/responsiveProp.ts

Add support for specifying 6 columns tiled layouts. Also supports full height content, if the layout is rendering full height children they will all be uniform height.
[Playroom preview](https://braid-design-system--de587df565aaa97d6c514855ac3349e06d5b38cb.surge.sh/playroom/#?code=N4Igxg9gJgpiBcIA8AVAlgGxgZwASQwFcBbAO2wF5gA2AX12wAcBDMGCgHRG2OYwy4A+DqVy4kAIQgAPXACNWAawDmAJwiFSUTuGaqoXXAAsYaZUYAuOgGaF+hllChpSynTz4CQw0WPEAFDFYYIwgMWFVjU3MrYABGAAYE+gB6HzEkFKlpdPFs+SU1DS0dMD0DECizSxs7L1xHZ1d3XntvET8AoLZQ8JhIk2rYgBYk1NzM7In8hTAVdU1tLjL9Q0GY2raG5icXNy4PNtyMwODeiKqN4AAmMdw0jvEsmWmZArmixdLyteiarlsW0aexaniEjxO3RCYQu6xqNwArMl7hNnjlHpI3rN5sUlrpVpU4VYAXUHDsmvtuK0vMcumcYf1LvCAMx3B6+SYvDEzQoLErLH6Ev7EkCA+rA5oHang3yQ+l9AbCqhxJHjDFonyZdBYbA+EAAGhAFhMxBwCAA2twYDBFABBUgALxAAF1DQB3NBQY3YC0AdmoAA5nbQgA)

feat(Tiles): Support 6 columns and full height content

---

.changeset/twelve-fireants-teach.md
lib/components/Textarea/Textarea.treat.ts

This is a bug fix for an issue with the new highlighting feature in Textarea. If you add a trailing new line and then scroll, the highlight elements fall out of sync with the text in the textarea. This was previously an issue in the seek styleguide and this was the fix: https://github.com/seek-oss/seek-style-guide/blob/master/react/Textarea/Textarea.less#L95. I'm applying the same fix here
Playroom to showing the problem (scroll inside the textarea):
https://seek-oss.github.io/braid-design-system/playroom/#?code=N4Igxg9gJgpiBcIA8AVGAPALgQwE42wB0A7AAlNgGcxcBLAB01omIF5CQBhACz2zEwxclUgE4AtACZJpPDFK1iAN2wAbWlA4ly3WgHNu6g5gBK2YnpiVWwANrbypYA8ekYxKPFLSANC8eUOLiYXqL+AL4OALqRZApQ7CAaWnGq2ABGMKqJACIQpACeEACupOoA1vIAQrjYGgD8KeQqqsUwNgDkLW3Y2JRQAGZ9g8ND-WMj46OEJDPEcx2xAPQAfCQgPiAA7hqY3JQItgCMAAySACwx …

Textarea: Fix trailing new line highlight issue

---

site/src/App/App.tsx

Also hoisting the StrictMode component up so it wraps the entire app.
This bug was caused by the fact that the `exact` prop on `Redirect` only works when it's a direct child of `Switch` for some reason.

Docs: Fix redirect bug when loading component pages directly

---

.changeset/good-apples-confess.md
generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Divider/Divider.docs.tsx
lib/components/Divider/Divider.treat.ts
lib/components/Divider/Divider.tsx

I accidentally named this differently to the other weights in the system. Given this was only just released minutes ago and it only affects the naming of the default case, I decided to mark this as a patch rather than a breaking change.

Divider: Rename 'standard' weight to 'regular'

---

.changeset/two-scissors-turn.md
themes/occ.ts

This PR adds the OCC base theme export to support the OCC theme which was added recently.
/cc @michaeltaranto

Themes: Fix OCC theme export

---

lib/components/Accordion/Accordion.docs.tsx
lib/components/Actions/Actions.docs.tsx
lib/components/Autosuggest/Autosuggest.docs.tsx
lib/components/Button/Button.docs.tsx
lib/components/ButtonLink/ButtonLink.docs.tsx
lib/components/ButtonRenderer/ButtonRenderer.docs.tsx
lib/components/Checkbox/Checkbox.docs.tsx
lib/components/Dropdown/Dropdown.docs.tsx
lib/components/FieldLabel/FieldLabel.docs.tsx
lib/components/FieldMessage/FieldMessage.docs.tsx
lib/components/MenuRenderer/MenuRenderer.docs.tsx
lib/components/MonthPicker/MonthPicker.docs.tsx
lib/components/OverflowMenu/OverflowMenu.docs.tsx
lib/components/Radio/Radio.docs.tsx
lib/components/TextDropdown/TextDropdown.docs.tsx
lib/components/TextField/TextField.docs.tsx
lib/components/TextLink/TextLink.docs.tsx
lib/components/TextLinkRenderer/TextLinkRenderer.docs.tsx
lib/components/Textarea/Textarea.docs.tsx
lib/components/Toggle/Toggle.docs.tsx
site/src/App/SubNavigation/SubNavigation.tsx
site/src/types.d.ts

This distinction doesn't seem very helpful in practice, so let's drop it.

Docs: Merge 'Interaction' component category into 'Content'

---

.changeset/fuzzy-cycles-dream.md
.changeset/proud-sloths-sing.md
.changeset/tall-snails-divide.md
lib/components/Autosuggest/Autosuggest.tsx
lib/components/Dropdown/Dropdown.treat.ts
lib/components/Dropdown/Dropdown.tsx
lib/components/PasswordField/PasswordField.tsx
lib/components/Textarea/Textarea.docs.tsx
lib/components/Textarea/Textarea.tsx
lib/components/private/Field/ClearField.tsx
lib/components/private/Field/Field.tsx

Also rolled back `Dropdown` from using the `secondaryIcon` feature on `Field` internally as we want the right side padding on the select not the container.

Improve support for field buttons with browser extensions

---

.changeset/polite-keys-tap.md
lib/components/MonthPicker/MonthPicker.treat.ts
lib/components/MonthPicker/MonthPicker.tsx

Fix for the native Monthpicker on iOS having a reduced height when no value is provided.

MonthPicker: Preserve touchable height on iOS

---

.changeset/eighty-panthers-knock.md
.changeset/shy-jokes-watch.md
docs/Style Guide Migration.md
generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Hidden/Hidden.docs.tsx
lib/components/Hidden/Hidden.tsx
lib/components/HiddenVisually/HiddenVisually.docs.tsx
lib/components/HiddenVisually/HiddenVisually.migration.md
lib/components/HiddenVisually/HiddenVisually.treat.ts
lib/components/HiddenVisually/HiddenVisually.tsx
lib/components/index.ts
lib/stories/all.stories.tsx
site/src/types.d.ts

See changesets for details.
This PR also starts the process of deprecating the `screen` boolean prop on `Hidden` since people *think* it's the same behaviour as `HiddenVisually`. In practice, `<Hidden screen>` hides the content for _everyone_, but makes it available on print, which is a total edge case that our system doesn't need to explicitly cater to.

Add HiddenVisually, infer 'inline' prop for Hidden within text

---

.changeset/brown-paws-brush.md
.changeset/cold-ways-move.md
.changeset/lucky-sloths-cover.md
.changeset/soft-chairs-joke.md
generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Autosuggest/Autosuggest.tsx
lib/components/Box/useBoxStyles.treat.ts
lib/components/Dropdown/Dropdown.tsx
lib/components/Toggle/Toggle.tsx
lib/components/private/Field/Field.tsx
lib/components/private/FieldOverlay/FieldOverlay.tsx
lib/components/private/InlineField/InlineField.tsx
lib/themes/baseTokens/seekAnz.ts
lib/themes/baseTokens/seekAsia.ts
lib/themes/catho/tokens.ts
lib/themes/makeBraidTheme.ts
lib/themes/occ/tokens.ts
lib/themes/seekUnifiedBeta/tokens.ts
lib/themes/wireframe/tokens.ts
site/src/theme/tokens.ts

Themes can now configure the colour of field borders separately to standard border colours. This facilitates using a higher contrast border colour on fields to further improve accessibility.
Updated themes include:
- seekAnz
- seekBusiness
- seekUnifiedBeta
- catho (based on referencing Quantum)

Improve field border contrast ratio

---

.github/workflows/preview-site.yml
.github/workflows/release.yml
.github/workflows/validate.yml

Update github action branch references to `main` and migrate to seek-oss org secret for npm token

Update CI actions & use org npm token

---

.changeset/violet-baboons-invite.md
generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Notice/Notice.docs.tsx
lib/components/Text/Text.tsx
lib/components/TextLink/TextLink.docs.tsx
lib/components/TextLink/TextLink.tsx
lib/components/TextLinkButton/TextLinkButton.docs.tsx
lib/components/TextLinkButton/TextLinkButton.tsx
lib/components/TextLinkRenderer/TextLinkRenderer.treat.ts
lib/components/TextLinkRenderer/TextLinkRenderer.tsx
lib/components/TextLinkRenderer/TextLinkRendererContext.ts
lib/hooks/typography/index.ts

I've changed the logic of `TextLink` so that its default tone is based on the parent `TextContext` rather than the background colour, which meant that `Text` needed to put the resolved `tone` on context.
I've also removed the redundant 768px screenshots from `TextLink`.

TextLink: Add weight prop, add weak weight variant

---

lib/components/Dialog/Dialog.test.tsx

Increasing the timeout to 1500ms (up from the default 1000ms) for the two tests that assert on the removal of the Dialog from the DOM. Should be more than enough time, and is locally, but seems to struggle in CI.

Increase timeout for Dialog close assertion

---

.changeset/sharp-pianos-share.md
.gitignore
.vscode/Changeset.code-snippets
generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Loader/Loader.tsx

**Loader:** Add support for `aria-label`
Provides a mechanism for consumers to better communicate to assistive technologies what is happening.
```jsx
<Loader aria-label="Loading search results" />
```
**Developer Notes**
Also adding vscode snippet to support faster, more consistent release note authoring.

Add `aria-label` support to Loader

---

site/src/App/Code/Code.tsx
site/src/App/routes/gallery/Gallery.tsx
site/src/App/routes/gallery/GalleryPanel.tsx
site/src/App/routes/gallery/gallery.treat.ts
site/src/App/routes/gallery/index.tsx

A bunch of improvements following some early stage feedback:
- Added Braid logo in top left to support navigating back to the docs
- Renamed "Reset" to "Fit to Screen", and updated icon
- Zoom buttons now take 20% steps in/out
- Added Copy label to button
- Added `Copied` feedback after copying an example (Note: button is shared with `Code` panels in docs, added success feedback on copy for them too.)
- Added translucency to overlay panels, turning opaque on hover
- Moved theme selector into top left panel alongside logo

Minor updates to Gallery

---

site/src/App/routes/gallery/Gallery.tsx

Add badge next to component name in Gallery to highlight when it's 🆕

Highlight new components in Gallery

---

.changeset/strong-spoons-promise.md
lib/components/Toggle/Toggle.docs.tsx
lib/components/Toggle/Toggle.tsx

This fixes an issue where a justified Toggle inside a flex container (e.g. Column with a width of "content") would have no space between the label and the toggle.

Toggle: Ensure space between label and toggle when justified

---

lib/components/Autosuggest/Autosuggest.playroom.tsx
lib/components/Dialog/Dialog.docs.tsx
lib/components/Dialog/Dialog.playroom.tsx
lib/components/Drawer/Drawer.docs.tsx
lib/components/Drawer/Drawer.playroom.tsx
lib/components/TextField/TextField.playroom.tsx
lib/playroom/FrameComponent.tsx
lib/playroom/usePlayroomState.ts
lib/playroom/useScope.ts
package.json
sku.config.js
yarn.lock

This adds the `showToast` function returned from [useToast](https://seek-oss.github.io/braid-design-system/components/useToast), as well as the following state management functions:
- `getState: (key: string, defaultValue?: any) => any`
- `setState: (key: string, value: any) => void`
- `setState: (key: string) => (value: any) => void`
- `resetState: () => void`
- `resetState: (...keys: string[]) => void`
I've also tweaked a few Playroom component wrappers and snippets to make them play nicer with external state.

Add getState, setState, resetState and showToast to Playroom

---

.changeset/fair-dragons-smoke.md
.changeset/tasty-jars-jog.md
lib/components/Dropdown/Dropdown.test.tsx
lib/components/MonthPicker/MonthPicker.test.tsx
lib/components/MonthPicker/MonthPicker.tsx
lib/components/PasswordField/PasswordField.test.tsx
lib/components/TextField/TextField.test.tsx
lib/components/Textarea/Textarea.test.tsx
lib/components/private/Field/Field.tsx
lib/components/private/FieldGroup/FieldGroup.tsx

**TextField,Dropdown,PasswordField,MonthPicker,Textarea:** Apply aria-describedby to form elements only when needed
Only apply `aria-describedby` to form elements when needed, e.g. either a `message`, `description`, or an explicit `aria-describedby` is passed.
**MonthPicker:** Announce semantic grouping of fields and improved translation support.
When not on a native device, the MonthPicker uses a `fieldset` containing two dropdowns. This change ensures that the grouping is announced correctly. From a translations perspective the labels for the dropdowns are no longer a concatenation of the `label` and `monthLabel`/`yearLabel`, supporting translation of the entire phrase.

Form field description a11y & improved MonthPicker i18n support

---

.changeset/afraid-coins-talk.md
lib/components/BulletList/BulletList.docs.tsx
lib/components/Checkbox/Checkbox.test.tsx
lib/components/Radio/Radio.test.tsx
lib/components/private/InlineField/InlineField.tsx

**Radio,Checkbox:** Apply aria-describedby only when needed
Only apply aria-describedby when needed, e.g. either a message or description is passed.

Apply aria-describedby only when needed

---

.changeset/silly-lies-add.md
generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/List/List.docs.tsx
lib/components/List/List.playroom.tsx
lib/components/List/List.tsx
lib/playroom/components.ts

**List:** Add support for icons
Provides a way to use an icon for all the items in a list. When using `type="icon"` you must also provide the `icon` prop. See example below:
```jsx
<List type="icon" icon={<IconTick tone="positive" />}>
<Text>This is a list item.</Text>
<Text>This is a list item.</Text>
<Text>This is a list item.</Text>
</List>
```

List: Add support for icons

---

.changeset/curvy-boxes-grin.md
generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/RadioGroup/RadioGroup.tsx
lib/components/private/InlineField/InlineField.tsx

**Checkbox,RadioGroup,Radio:** Fix element type passed to onChange event
Fixes a bug where the `onChange` event previously received the change event for a `form` element rather than an `input` element.

Fix element type passed to onChange event

---

lib/components/Checkbox/Checkbox.docs.tsx
lib/components/Toggle/Toggle.docs.tsx

Removing this since it's likely to cause confusion when combined with our new prototyping and state binding system.

Playroom: Remove checked prop from Checkbox and Toggle snippets

---

lib/components/Autosuggest/Autosuggest.tsx

Since this is just a refactor, I'm not marking this as a release.

Autosuggest: Replace mobile detection logic with useBreakpoint

---

.changeset/nasty-squids-confess.md
lib/components/Autosuggest/Autosuggest.test.tsx
lib/components/Stack/Stack.tsx
lib/components/private/smoothScroll.ts

- Sets promise to void when being resolved without a value
- Use const types where possible to add assurance that the correct length of arrays are being used

Fix type definitions for Stack and scroll components

---

.changeset/nervous-papayas-warn.md
generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Checkbox/Checkbox.test.tsx
lib/components/Checkbox/Checkbox.tsx

**Checkbox:** Support inferring of tri-state checked value
To simplify the use of tri-state checkboxes, the **checked** prop now supports resolving the tri-state value from a array of checked values.
```jsx
<Checkbox
label="Select all"
checked={[ true, false, false ]} // Will resolve to "mixed"
/>
```

Checkbox: Support inferring of tri-state checked value

---

.changeset/weak-paws-help.md
lib/components/PasswordField/PasswordField.screenshots.tsx
lib/components/PasswordField/PasswordField.test.tsx
lib/components/PasswordField/PasswordField.tsx

**PasswordField:** Ensure disabled is handled correctly
Fixes a bug where the **disabled** prop was not being honoured, it was hiding the visibility toggle but leaving the field enabled.

PasswordField: Ensure disabled is handled correctly

---

lib/components/MonthPicker/MonthPicker.gallery.tsx
lib/components/PasswordField/PasswordField.gallery.tsx
lib/components/TextField/TextField.gallery.tsx
site/src/App/routes/gallery/Gallery.tsx

Change the id construction in Gallery to ensure all items are unique in the same dom regardless of position in examples array.

Ensure ids are unique in Gallery

---

lib/components/Box/Box.docs.tsx
lib/components/Box/useBoxStyles.treat.ts
lib/components/Box/useBoxStyles.ts
lib/themes/docs/tokens.ts
site/src/App/ComponentDoc/ComponentProps.tsx
site/src/App/Navigation/Navigation.tsx

This obvously isn't complete, but it's an improvement over the current docs, documenting the following Box features:
- `component` prop and forwarding native props to the underlying element.
- `className` prop supporting the full Classnames API.
- Padding and margin props, including responsive values.
- Backgrounds.
- Box shadows.
- General CSS utils.
To ensure the docs stay up to date, I've also made sure that the background and box shadow docs will break the build if they don't have a description provided for every possible value.
This PR also increases the "desktop" breakpoint in the docs theme, adjusts the sorting of component props so that third-party props are at the bottom, and fixes a bug with the navigation on tablet.

Add initial Box docs

---

.changeset/six-monkeys-itch.md
lib/components/Pagination/Pagination.tsx

Add space between page and navigation controls above mobile to improve affordance between the current page and the hover state of surrounding buttons.

Pagination: Add space between buttons above mobile

---

.changeset/red-readers-crash.md
lib/components/ButtonRenderer/ButtonRenderer.treat.ts
lib/components/ButtonRenderer/ButtonRenderer.tsx

**Button, ButtonLink:** Remove all interactive styles when loading
No longer applies hover and cursor pointer styles when a `Button` is set to `loading`.

Button: Remove all interactive styles when loading

---

.changeset/olive-turtles-hug.md
generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Button/Button.docs.tsx
lib/components/Button/Button.gallery.tsx
lib/components/Button/Button.playroom.tsx
lib/components/Button/Button.screenshots.tsx
lib/components/Button/Button.tsx
lib/components/ButtonLink/ButtonLink.playroom.tsx
lib/components/ButtonLink/ButtonLink.tsx
lib/components/ButtonRenderer/ButtonRenderer.treat.ts
lib/components/ButtonRenderer/ButtonRenderer.tsx
lib/components/ButtonRenderer/buttonSmallPaddingSize.ts
lib/playroom/components.ts

**Button, ButtonLink, ButtonRenderer:** Add `bleedY` prop
You can now choose to allow the button’s background colour to bleed out into the surrounding layout, making it easier to align with other elements.
For example, we can align a button to a Heading element using an Inline, even though the button is actually taller than the heading. If we didn’t use the **bleedY** prop in this case, the button would introduce unwanted space above and below the heading.
```jsx
<Inline space="small" alignY="center">
<Heading level="4">Heading</Heading>
<Button bleedY>Button</Button>
<Button bleedY size="small">
Button
</Button>
</Inline>
```
[Playroom Demo](https://braid-design-system--8c5ab9100e8f713f58fcd50b597a68ffffcddb63.surge.sh/playroom/#?code=N4Igxg9gJgpiBcIA8AhCAPABABwIZSgEsA7 …

Button: Add `bleedY` prop

---

lib/components/Tabs/Tabs.screenshots.tsx
lib/components/Tiles/Tiles.screenshots.tsx

These tests should not be bound to the visual implementation of a `Card`, so decoupling before upcoming `Card` changes.

Tabs, Tiles: Remove Card from screenshot tests

---

.changeset/six-carpets-sing.md
lib/components/Hidden/Hidden.tsx
lib/components/HiddenVisually/HiddenVisually.tsx
lib/components/Text/Text.tsx
lib/components/Text/TextContext.ts
lib/components/TextDropdown/TextDropdown.tsx
lib/components/TextLinkRenderer/TextLinkRenderer.tsx
lib/components/TooltipRenderer/TooltipRenderer.test.tsx
lib/components/TooltipRenderer/TooltipRenderer.tsx
lib/hooks/useIcon/index.ts

Because we're rendering the tooltip into a portal, we need to reset the TextContext so we don't trigger the Text within Text check. Updated the test suite to exercise this new logic.
Also refactored TextContext to use a named export because auto import was giving me grief.

TooltipRenderer: Support usage within Text elements

---

.changeset/ninety-otters-beg.md
generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Checkbox/Checkbox.docs.tsx
lib/components/Checkbox/Checkbox.gallery.tsx
lib/components/Checkbox/Checkbox.screenshots.tsx
lib/components/Checkbox/Checkbox.snippets.tsx
lib/components/Radio/Radio.tsx
lib/components/RadioGroup/RadioGroup.docs.tsx
lib/components/RadioGroup/RadioGroup.gallery.tsx
lib/components/RadioGroup/RadioGroup.screenshots.tsx
lib/components/RadioGroup/RadioGroup.snippets.tsx
lib/components/RadioGroup/RadioGroup.tsx
lib/components/RadioGroup/RadioGroupContext.ts
lib/components/RadioGroup/RadioItem.tsx
lib/components/Toggle/Toggle.docs.tsx
lib/components/Toggle/Toggle.gallery.tsx
lib/components/Toggle/Toggle.screenshots.tsx
lib/components/Toggle/Toggle.snippets.tsx
lib/components/Toggle/Toggle.treat.ts
lib/components/Toggle/Toggle.tsx
lib/components/private/InlineField/InlineField.treat.ts
lib/components/private/InlineField/InlineField.tsx
lib/components/private/InlineField/getSize.ts

Adds support for adjusting the `size` of a `Checkbox`, the RadioItems within a `RadioGroup` or a `Toggle`. Setting the size adjusts both the visual control and the text size of the label.
```jsx
<Checkbox size="small" label="Label" />
```
```jsx
<RadioGroup size="small" label="Label">
...
</RadioGroup>
```
```jsx
<Toggle size="small" label="Label" />
```
[Preview in Playroom](https://braid-design-system--1c775a68965d6afa676c7d0e4143a9735210e593.surge.sh/playroom/#?code=N4Igxg9gJgpiBcIA8BhAhgJygPgDoDsACQpAZQBc0wBrQgZwAcqYBeXEAG0wHMZ3CoASwBug2Bjp4ixEhSq1GzNiAC2MIQFcV7KTJlIAYoJgcoAGTQAjE4S7WOylAAsYNSxAAe-APS69hYABtdlIVNA4OdgAaQhDKfChMKHYAXQA6MIYACiy6QQAvGABKQhZsQiyCf31nV2p3L2lq4jzClmBWmDTyCDMIAHcYDHQ6GCyigF8q5uI7E3bOqabmyzQoXnakACE13kIe-FZ2Q41yDHCdAA4ABiRvHfWYbCWZ32m9Isn3km …

Add `size` support to Checkbox, RadioGroup & Toggle

---

.changeset/poor-lobsters-retire.md
lib/components/Autosuggest/Autosuggest.test.tsx
lib/components/Autosuggest/Autosuggest.tsx

Went with `data-testid` but open to suggestions 😉

Autosuggest: Fix missing/invalid group headings in some cases

---

patches/panzoom+9.4.2.patch
site/src/App/routes/gallery/Gallery.tsx

Tap events on links and buttons (for Alternatives, documentation etc) in Gallery were being swallowed by the gesture library. Patching it to enable these actions the same way we do with mouse down events (albeit that has a first class api)

Gallery: Fix links and buttons on touch

---

site/src/App/routes/gallery/Gallery.tsx
site/src/App/routes/gallery/gallery.css.ts

Gallery performance has been unusable in Safari, a lot can be attributed to animations within the greater transform that occurs with the zooming behaviour. Disabling the animations on components (like Loader and Buttons) unless the user hovers over that Gallery item.
Hopefully this make Safari at least usable, obviously plenty of perf improvements could be made, this is just trying to get Safari to where the other browsers are at in terms of usability.

Gallery: Improve Safari performance

---

.changeset/small-bats-joke.md
lib/components/private/InlineField/InlineField.css.ts
lib/components/private/InlineField/InlineField.tsx

Checkbox, RadioGroup, Radio: Use atoms for label cursor styles

---

.changeset/gold-parrots-perform.md
lib/components/private/FieldOverlay/FieldOverlay.tsx

**Buttons, Fields, TextLinks, Toggle:** Use `span` for field state overlays instead of `div`
Produce more valid HTML as `div` elements are not as flexible with which elements they can be inside (from a validators perspective).

Use span element for field overlays

---

site/src/App/Code/editorTheme.ts
site/src/App/Markdown/Markdown.css.ts
site/src/App/Markdown/Markdown.tsx

Update the site to use the internal palette for styling the code blocks. Also using custom styles on the release page to get around the nested Text component warnings on the Releases page in dev, due to markdown-based rendering.

Use color palette for code blocks, fix release page warnings

---

.changeset/brown-llamas-raise.md
.changeset/perfect-keys-lay.md
generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Card/Card.snippets.tsx
lib/components/Column/Column.screenshots.tsx
lib/components/Column/Column.tsx
lib/components/Columns/Columns.docs.tsx
lib/components/Columns/Columns.gallery.tsx
lib/components/Columns/Columns.migration.md
lib/components/Columns/Columns.playroom.tsx
lib/components/Columns/Columns.screenshots.tsx
lib/components/Columns/Columns.snippets.tsx
lib/components/Columns/Columns.tsx
lib/components/Columns/ColumnsContext.ts
site/src/App/routes/foundations/layout/layout.tsx

**Columns:** Make child Column optional and default internally
As an optimisation to the default use of `Columns`, it is now only necessary use `Column` as a child element when customising the `width` property. If the use case is equally distributed columns, wrapping in `Columns` will now be enough.
The following will now result in two columns equally distributed:
```jsx
<Columns space="medium">
<Card>...</Card>
<Card>...</Card>
</Columns>
```
or wrap a single child in a `Column` to customise it's width:
```jsx
<Columns space="medium">
<Card>...</Card>
<Card>...</Card>
<Column width="content">
<OverflowMenu />
</Column>
</Columns>
```
---
**Columns:** Support using span elements via component prop
Setting the `component` prop to `span` will now ensure all elements …

Columns: Optional Column children & component span support

---

.changeset/nervous-birds-stare.md
generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Pagination/Pagination.docs.tsx
lib/components/Pagination/Pagination.playroom.tsx
lib/components/Pagination/Pagination.screenshots.tsx
lib/components/Pagination/Pagination.test.tsx
lib/components/Pagination/Pagination.tsx
lib/components/Pagination/paginate.test.ts
lib/components/Pagination/paginate.ts

**Pagination:** Add `pageLimit` support
Add support for configuring the number of pages displayed using the `pageLimit` prop. The default is still set to 7, but consumers can now reduce this, useful when `Pagination` is used inside column layouts.
In addition, the layout is has been stabilised, preventing the links moving when the next/prev actions are shown/hidden.
```jsx
<Pagination
...
pageLimit={3}
/>
```

Pagination: Add `pageLimit` support

---

lib/components/ButtonIcon/ButtonIcon.playroom.tsx
lib/components/OverflowMenu/OverflowMenu.playroom.tsx
lib/components/OverflowMenu/OverflowMenu.tsx
lib/components/Tag/Tag.playroom.tsx
lib/playroom/components.ts

Adding fallback ids for `OverflowMenu` and `Tag` in playroom so that they always have tooltips when prototyping.

Playroom: Add fallback ids

---

generate-component-docs/generate.ts
lib/components/BraidTestProvider/BraidTestProvider.docs.tsx
site/src/App/navigationHelpers.ts
sku.routes.js

Moving the `BraidTestProvider` to its own `test` entry point [in v31.0.0](http://localhost:8080/components/BraidTestProvider/releases) accidentally dropped it from the docs site, which builds its navigation based on the `components` and `css` entry points.
This reinstates and includes the `test` entry point to cater for future exports as well.

site: Expose docs for test entry point

---

.changeset/afraid-pillows-smile.md
generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Bleed/Bleed.playroom.tsx
lib/components/Bleed/Bleed.screenshots.tsx
lib/components/Bleed/Bleed.tsx
lib/playroom/components.ts

Includes updated `BraidTestProvider` snapshot from previous PR. Opened [PR to sku](https://github.com/seek-oss/sku/pull/678) separately to ensure new snapshots fail the build in CI in the future.

Bleed: Support using span elements via component prop

---

.changeset/brown-crabs-visit.md
codemod/src/codemod.ts
codemod/src/plugin-deprecate/deprecationMaps/v31-11.ts
codemod/src/plugin-deprecate/plugin-prop-rename.test.ts
codemod/src/plugin-deprecate/plugin-prop-rename.ts
generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/Button/Button.css.ts
lib/components/Button/Button.docs.tsx
lib/components/Button/Button.gallery.tsx
lib/components/Button/Button.screenshots.tsx
lib/components/Button/Button.tsx
lib/components/ButtonLink/ButtonLink.tsx
site/src/App/routes/gallery/Gallery.tsx

Previously the `bleedY` prop allowed the background of `Button` to bleed vertically into the surrounding layout. This worked well for all variants except `transparent`, which needed to bleed horizontally as well.
To support this we have introduced the `bleed` prop which will apply the bleed based on the `variant`. We have also deprecated `bleedY` which will be removed in a future release.
```diff
<Button
-  bleedY
+  bleed
{...}
>
Button
</Button>
```
**MIGRATION GUIDE**
Migration from `bleedY` to `bleed` can be automated by running the Braid upgrade command, passing the `v31.11` version. You must provide a glob to target your project’s source files. For example:
```
yarn braid-upgrade v31.11 "**/*.{ts,tsx}"
```
It is recommended to visually review the any `Button` …

Button, ButtonLink: Improve Button `bleed`

---

.changeset/spicy-poems-visit.md
lib/components/Button/Button.screenshots.tsx
lib/components/Button/Button.tsx
lib/components/ButtonLink/ButtonLink.tsx

Ensure that `bleedY` applies bleed only vertically on `transparent` variant, isolating the new horizontal bleed to the new `bleed` prop exclusively.

Button, ButtonLink: Ensure bleedY backwards compat for transparent variant

---

.changeset/forty-coins-unite.md
generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/RadioGroup/RadioGroup.docs.tsx
lib/components/RadioGroup/RadioGroup.screenshots.tsx
lib/components/RadioGroup/RadioItem.tsx

Provide support for disabling individual `RadioItem`s within a `RadioGroup`.
```jsx
<RadioGroup>
<RadioItem label="One" value="1" />
<RadioItem label="Two" value="2" />
<RadioItem label="Three" value="3" disabled={true} />
</RadioGroup>
```
Wanted to add a test around the keyboard flow here, but testing-library doesnt support the [native arrow key behaviour not being implemented as yet](https://github.com/testing-library/user-event/issues/843). Will keep an eye on the issue as this would be valuable to add in the future.

RadioItem: Add disabled support

---

.changeset/chatty-rice-drive.md
generate-component-docs/__snapshots__/contract.test.ts.snap
lib/components/MenuItem/MenuItem.tsx
lib/components/MenuItem/MenuItemLink.tsx
lib/components/MenuItem/useMenuItem.tsx
lib/components/MenuItemCheckbox/MenuItemCheckbox.tsx
lib/components/MenuRenderer/MenuRenderer.actions.ts
lib/components/MenuRenderer/MenuRenderer.docs.tsx
lib/components/MenuRenderer/MenuRenderer.tsx
lib/components/MenuRenderer/testHelper.tsx
lib/components/OverflowMenu/OverflowMenu.docs.tsx

**MenuRenderer, OverflowMenu:** Provide context data to onClose
The `onClose` handler now receives data to allow consumers to discern why the menu closed — either by exiting or selecting an action. See the [documentation](https://seek-oss.github.io/braid-design-system/components/MenuRenderer#menu-interactions) for more details.
```jsx
<MenuRenderer
onClose={(closeReason) => {
// ...
}}
/>
```

MenuRenderer, OverflowMenu: Provide context data to onClose

---

package.json
pnpm-lock.yaml
scripts/writeBraidFrontMatter.js

Extend the changeset creation experience in the cli to include prompts for creating and inserting the additional front matter block used to Braid to add release information to the website.
Running `pnpm changeset` will now prompt for the following and enrich the changeset accordingly:
- What is the impact to the top level api of Braid? (updated / new / no change)
- Add scope list (inferred from original changeset if formatted as `<scope>: <message>`, otherwise prompt for scope list explicitly)
- Add release notes to be included on site
- Add `Example Usage` code block if required

Extend changeset DX to add braid release front matter

---

.changeset/slow-numbers-marry.md
.changeset/thirty-apricots-fix.md
scripts/writeBraidFrontMatter.js

Fix custom Braid release front matter script, which was. missing a `:` from the new/updated scope.
Also updating changesets created and merged in master.

Fix custom changesets and generate script

---

.changeset/rude-frogs-listen.md
lib/components/RadioGroup/RadioGroup.docs.tsx
lib/components/RadioGroup/RadioGroup.screenshots.tsx
lib/components/RadioGroup/RadioGroup.tsx

Removes additional white space applied above the `RadioItem`s when no visible `label` is provided, i.e. when labelling via `aria-label` or `aria-labelledby`.

RadioGroup: Remove surrounding white space with no visual label

---

.changeset/proud-cheetahs-serve.md
css/index.ts
css/vars.docs.tsx

Provide access to the themed `shadow` scale on the `vars` object
```jsx
import { vars } from 'braid-design-system/css';
export const dropShadow = style({
boxShadow: vars.shadow.small,
});
```

vars: Expose shadow palette

---

lib/components/Accordion/Accordion.screenshots.tsx
lib/components/Checkbox/Checkbox.docs.tsx
lib/components/Checkbox/Checkbox.screenshots.tsx
lib/components/Checkbox/CheckboxStandalone.screenshots.tsx
lib/stories/all.stories.tsx

Found this behaviour when testing Storybook in the monorepo branch:
<details>
<summary>Screen recording</summary>
</details>

Fix clashing ids in Storybook and Playroom

---

.changeset/sweet-carpets-kiss.md
packages/braid-design-system/lib/components/useToast/Toast.tsx
packages/braid-design-system/lib/components/useToast/ToastTypes.ts
packages/braid-design-system/lib/components/useToast/useToast.docs.tsx
packages/braid-design-system/lib/components/useToast/useToast.gallery.tsx
packages/braid-design-system/lib/components/useToast/useToast.screenshots.tsx

Add support for `neutral` tone. When using a `neutral` tone, an icon may optionally be provided. For consistency, the tone of the icon is set to **secondary** and cannot be customised.
```jsx
import { useToast } from "braid-design-system"
export default () => {
const showToast = useToast();
return (
<Button
onClick={() =>
showToast({
tone: "neutral",
icon: <IconBookmark />,
message: "Neutral with icon",
})
}
>
Show Toast
</Button>
);
}
```

useToast: Add neutral tone support

---

.changeset/lucky-clouds-melt.md
packages/braid-design-system/lib/components/Autosuggest/Autosuggest.docs.tsx
packages/braid-design-system/lib/components/Autosuggest/Autosuggest.test.tsx
packages/braid-design-system/lib/components/Autosuggest/Autosuggest.tsx
packages/braid-design-system/lib/components/private/Announcement/Announcement.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Provides consumers a way to give the user more context when no suggestions are available. The `noSuggestionsMessage` prop accepts either a simple message or a more structured prompt by providing an object containing **title** and **description**.
This message is only displayed when there are no available suggestions provided.
For the simple case:
```jsx
<Autosuggest
...
suggestions={[]}
noSuggestionsMessage="No results found"
/>
```
Or, for more a structured prompt:
```jsx
<Autosuggest
...
suggestions={[]}
noSuggestionsMessage={{
title: "No results found",
description: "Try searching for something else",
}}
/>
```
**MIGRATION GUIDE:**
In addition, the old mechanism allowing consumers to pass an object to `suggestions` containing a `message` has been deprecated. This …

Autosuggest: Add configurable message for no suggestions

---

packages/braid-design-system/lib/components/Accordion/Accordion.docs.tsx
packages/braid-design-system/lib/components/Alert/Alert.docs.tsx
packages/braid-design-system/lib/components/ButtonIcon/ButtonIcon.docs.tsx
packages/braid-design-system/lib/components/Checkbox/Checkbox.docs.tsx
packages/braid-design-system/lib/components/Dialog/Dialog.docs.tsx
packages/braid-design-system/lib/components/Disclosure/Disclosure.docs.tsx
packages/braid-design-system/lib/components/Drawer/Drawer.docs.tsx
packages/braid-design-system/lib/components/Loader/Loader.docs.tsx
packages/braid-design-system/lib/components/MenuItem/MenuItem.docs.tsx
packages/braid-design-system/lib/components/MenuItemCheckbox/MenuItemCheckbox.docs.tsx
packages/braid-design-system/lib/components/MenuItemDivider/MenuItemDivider.docs.tsx
packages/braid-design-system/lib/components/MenuRenderer/MenuRenderer.docs.tsx
packages/braid-design-system/lib/components/MenuRenderer/MenuRenderer.tsx
packages/braid-design-system/lib/components/Notice/Notice.docs.tsx
packages/braid-design-system/lib/components/OverflowMenu/OverflowMenu.docs.tsx
packages/braid-design-system/lib/components/Pagination/Pagination.docs.tsx
packages/braid-design-system/lib/components/RadioGroup/RadioGroup.docs.tsx
packages/braid-design-system/lib/components/Stepper/Stepper.docs.tsx
packages/braid-design-system/lib/components/Tabs/Tabs.docs.tsx
packages/braid-design-system/lib/components/TextLinkButton/TextLinkButton.docs.tsx
packages/braid-design-system/lib/components/TooltipRenderer/TooltipRenderer.docs.tsx
packages/braid-design-system/lib/components/useToast/useToast.docs.tsx

Since the W3C landed their new Accessibility Authoring Practices Guide (APG), the accessibility pattern links in the docs have been broken.
Updating to the new links which is a nicer experience too.
https://www.w3.org/WAI/ARIA/apg/patterns/

site: Update a11y links to new W3 APG site

---

.github/workflows/preview-site.yml
.github/workflows/release.yml
.github/workflows/snapshot.yml
.github/workflows/validate.yml
package.json

`pnpm/action-setup` can read the `packageManager` field in `package.json` now, so we don't need an explicit version in the github actions workflows.
There's also an issue in [this renovate PR's](https://github.com/seek-oss/braid-design-system/pull/1147) build where [the lockfile is out of date](https://github.com/seek-oss/braid-design-system/runs/8108055773?check_suite_focus=true#step:5:10). I'm not exactly sure if adding `pnpm install --lockfile-only` to the `version` script will fix it, but it's likely worth doing anyway.

CI cleanup and potential fix

---

packages/braid-design-system/lib/components/TextLink/TextLink.screenshots.tsx
packages/braid-design-system/package.json

Improving the visual testing of `TextLink` in advance of some clean ups. This will ensure no regressions slip through, but we really should have had these ages ago given their styling complexity.
The existing tests were a hangover from the shared docs and testing responsibilities, now the concerns are separate we can be more exhaustive.

TextLink: Improve screenshot tests

---

packages/braid-design-system/lib/components/Accordion/Accordion.screenshots.tsx
packages/braid-design-system/lib/components/Actions/Actions.screenshots.tsx
packages/braid-design-system/lib/components/Box/BoxRenderer.screenshots.tsx
packages/braid-design-system/lib/components/Button/Button.screenshots.tsx
packages/braid-design-system/lib/components/ButtonLink/ButtonLink.screenshots.tsx
packages/braid-design-system/lib/components/Disclosure/Disclosure.screenshots.tsx
packages/braid-design-system/lib/components/Hidden/Hidden.screenshots.tsx
packages/braid-design-system/lib/components/HiddenVisually/HiddenVisually.screenshots.tsx
packages/braid-design-system/lib/components/List/List.screenshots.tsx
packages/braid-design-system/lib/components/MenuItem/MenuItem.screenshots.tsx
packages/braid-design-system/lib/components/MenuRenderer/MenuRenderer.screenshots.tsx
packages/braid-design-system/lib/components/RadioGroup/RadioGroup.screenshots.tsx
packages/braid-design-system/lib/components/Tabs/Tabs.screenshots.tsx
packages/braid-design-system/lib/components/TextDropdown/TextDropdown.screenshots.tsx
packages/braid-design-system/lib/components/TextLinkButton/TextLinkButton.screenshots.tsx
packages/braid-design-system/lib/components/TooltipRenderer/TooltipRenderer.screenshots.tsx
packages/braid-design-system/lib/components/useToast/useToast.screenshots.tsx

Most `.screenshots.tsx` files import components from `../` which resolves to the top-level braid entrypoint, however a few were importing components from other places, as well as using `playroom` variants of components despite there being no need to do so in these files.
This PR normalizes all public component imports to import from `../` in order to make any future changes (e.g. using a `@braid-src` alias) a super simple find and replace. We may not use the public import going forward, but the point of this PR is to just make things consistent so we can change it easily in the future.

Normalize public component imports in `screenshots` files

---

packages/braid-design-system/lib/components/Card/Card.docs.tsx

`roundedAbove` had its tenses wrong

Fix prop typo

---

.changeset/blue-planes-draw.md
packages/braid-design-system/lib/components/Button/Button.screenshots.tsx
packages/braid-design-system/lib/components/Button/Button.tsx
packages/braid-design-system/lib/components/ButtonLink/ButtonLink.screenshots.tsx
packages/braid-design-system/lib/components/ButtonLink/ButtonLink.tsx

To improve optical balance of a `Button` with an `icon`, the icon container is bled to the left to balance against the larger horizontal inset of a `standard` button.
This alignment correction is now only applied on `standard` sized buttons that are not using the `transparent` variant.
Isolating this alignment correction enables transparent buttons to better align with other components with `icon` slots, for example:
```jsx
<Stack space="small">
<Text icon={<IconSend />}>Text</Text>
<Button icon={<IconSend />} variant="transparent" bleed>
Button
</Button>
</Stack>
```
Icons and text will now be perfectly aligned between Button components and others icon slots with the same text size.

Button, ButtonLink: Improve icon alignment

---

.changeset/beige-papayas-invent.md
packages/braid-design-system/lib/components/Rating/Rating.screenshots.tsx
packages/braid-design-system/lib/components/Rating/Rating.tsx

A star is only `filled` when the score is .75 and above. Fixes an issue where all scores .5 or above are shown as half filled stars.
Now when a rating reaches .75 it will round up to a full star.
```jsx
<Rating rating={3.75} /> // 4 filled
```

Rating: Only fill star for scores .75 and above

---

.changeset/many-coats-repair.md
packages/braid-design-system/lib/components/ButtonLink/ButtonLink.tsx

Disables the validation against the use of data attributes on `ButtonLink`. Given it exposes the full native anchor tag api, it is **not invalid** to use the native syntax.

ButtonLink: Allow native data attributes with anchor api

---

.changeset/giant-peas-grow.md
.changeset/hungry-moose-think.md
.changeset/serious-ties-shake.md
.changeset/slimy-guests-melt.md
packages/braid-design-system/lib/components/Bleed/Bleed.tsx
packages/braid-design-system/lib/components/Link/Link.tsx
packages/braid-design-system/lib/components/TextLink/TextLink.tsx
packages/braid-design-system/lib/components/private/buildDataAttributes.ts
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

The `data` attribute map now supports boolean values. This provides an improvement for the developer experience, no longer having to convert values to strings explicitly.
Also added `data` support to a few components that were missing it and disabled validation of native data attribute props on components that support native attributes.
As a side not, improved the dev/build time warning to have more valid syntax, e.g. wrapping property names in quotes where required.

Support data attribute boolean values

---

.changeset/flat-crabs-ring.md
packages/braid-design-system/lib/components/icons/IconRenderer.screenshots.tsx
packages/braid-design-system/lib/components/icons/IconRenderer.tsx
packages/braid-design-system/lib/components/index.ts
packages/braid-design-system/lib/hooks/useIcon/index.ts
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap
site/src/App/routes/foundations/iconography/IconsDetails.tsx
site/src/undocumentedExports.json

Provides support for sizing and aligning custom icons with Braid’s typographic components. The new `IconRenderer` component supports being used within `Text` and `Heading` components as well as inside `icon` slots of other components.
Uses the render prop pattern to provide the required classes to style and align a custom icon.
```jsx
<Heading level="1">
<IconRenderer>
{({ className }) => (
<svg className={className}>
...
</svg>
)}
</IconRenderer>
</Heading>
```

IconRenderer: Support sizing & alignment of custom icons

---

.changeset/early-lamps-own.md
packages/braid-design-system/lib/components/TextLink/TextLink.docs.tsx
packages/braid-design-system/lib/components/TextLink/TextLink.screenshots.tsx
packages/braid-design-system/lib/components/TextLink/TextLink.tsx
packages/braid-design-system/lib/components/TextLinkButton/TextLinkButton.docs.tsx
packages/braid-design-system/lib/components/TextLinkButton/TextLinkButton.screenshots.tsx
packages/braid-design-system/lib/components/TextLinkButton/TextLinkButton.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Provides a designed slot for adding an `icon` to a `TextLink` or `TextLinkButton`.
This solves for the problem of underlining the space between the icon and text.
```jsx
<Text>
<TextLink icon={<IconLink />}>...</TextLink>
</Text>
```

TextLink, TextLinkButton: Add icon support

---

.changeset/shaggy-tools-trade.md
packages/braid-design-system/lib/components/TextDropdown/TextDropdown.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap
pnpm-lock.yaml

On typescript versions >= 4.9, the `TextDropdown` component fails to typecheck [here](https://github.com/seek-oss/braid-design-system/blob/bcb987d486f946b43a95a47261d667bdf3784d35/packages/braid-design-system/lib/components/TextDropdown/TextDropdown.tsx#L34) with the error:
```
Type 'Value' is not assignable to type 'object'
```
This error is surfacing in typescript 4.9 for two reasons. Firstly, the narrowing conditions `typeof option !== 'string' && typeof option !== 'number'` were never strict enough to rule out the possibility that `option` could be a primitive value, so by the time the `in` operator was being executed, the type of `option` hadn't changed at all (pre typescript 4.9).
Secondly, the [changes to the `in` operator](https://devblogs.microsoft.com/typescript/announcing-typesc …

Refactor narrowing of `TextDropdownOption` to be compatible with typescript 4.9

---

.changeset/honest-hairs-wave.md
packages/braid-design-system/lib/components/Tabs/Tab.tsx
packages/braid-design-system/lib/components/Tabs/TabListContext.ts
packages/braid-design-system/lib/components/Tabs/TabPanel.tsx
packages/braid-design-system/lib/components/Tabs/TabPanels.tsx
packages/braid-design-system/lib/components/Tabs/Tabs.actions.ts
packages/braid-design-system/lib/components/Tabs/Tabs.css.ts
packages/braid-design-system/lib/components/Tabs/Tabs.docs.tsx
packages/braid-design-system/lib/components/Tabs/Tabs.screenshots.tsx
packages/braid-design-system/lib/components/Tabs/Tabs.tsx
packages/braid-design-system/lib/components/Tabs/TabsProvider.tsx
packages/braid-design-system/package.json
pnpm-lock.yaml

The appearance of a `Tab` has been updated. Changes include:
- Inactive tab uses `regular` text weight
- Hover state of inactive tab toggles `neutral` tone instead of underline
- Active tab indicator underlines content only, without the horizontal gutter
- Active tab indicator rounds top radii
- The `minimal` divider under `Tabs` underlines content only, without the horizontal gutter
Before: (first tab active, third tab hovered)
After: (first tab active, third tab hovered)
Note: Also fixes hot reload issue with `TabPanel` in dev mode.

Tab, Tabs: Updated visual design

---

.changeset/brown-badgers-shave.md
packages/braid-design-system/color-mode/index.ts
packages/braid-design-system/color-mode/query-param.ts
site/src/render.tsx

Add new `query-param` entry, providing a script for resolving the color mode preference from query string, as well as a utility function for retrieving the preference for constructing subsequent links.
Provides a clearer entry, co-locating all the color mode utilities by their mechanism (e.g. query param), allowing us to introduce others (e.g. local-storage) in the future.
We will be removing the previous `__experimentalDarkMode__` script once consumers have migrated.

color-mode: Add query-param entry

---

.github/workflows/validate.yml
package.json
packages/braid-design-system/lib/stories/all.stories.tsx
packages/braid-design-system/package.json
packages/braid-design-system/project.json

Now that `Tabs` uses transitions when switching between tabs, Chromatic snapshots trigger a review almost every time.
This PR disables CSS transiitions along with CSS animations.

Disable transitions in Chromatic

---

.changeset/loud-cups-switch.md
packages/braid-design-system/lib/components/Checkbox/CheckboxStandalone.screenshots.tsx
packages/braid-design-system/lib/components/Checkbox/CheckboxStandalone.tsx

Enables `CheckboxStandalone` to be wrapped in a `Text` component, ensuring it only occupies the same layout as as surrounding text.
This is useful for visually aligning checkboxes in a custom layout alongside other text-based components, e.g. `AccordionItem`.
```jsx
<Columns>
<Column>
<Text>
<CheckboxStandalone />
</Text>
</Column>
<Column>
<AccordionItem />
</Column>
</Columns>
```
Made the decision to isolate this to `CheckboxStandalone` and not the internal `StyledInput` as it is only relevant to the checkbox without a label.

CheckboxStandalone: Enable alignment with Text

---

.changeset/curly-falcons-wave.md
packages/braid-design-system/lib/components/Accordion/Accordion.docs.tsx
packages/braid-design-system/lib/components/Accordion/Accordion.playroom.tsx
packages/braid-design-system/lib/components/Accordion/Accordion.screenshots.tsx
packages/braid-design-system/lib/components/Accordion/Accordion.tsx
packages/braid-design-system/lib/components/Accordion/AccordionContext.ts
packages/braid-design-system/lib/components/Accordion/AccordionItem.playroom.tsx
packages/braid-design-system/lib/components/Accordion/AccordionItem.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Add support for customising the `weight` of `AccordionItem`s. This can be either at an `Accordion` level or on a standalone `AccordionItem` based on design requirements.
Note, in order to maintain visual consistency, the `weight` prop can only be specified on an `AccordionItem` when outside of an `Accordion`.
```jsx
<Accordion weight="strong">
<AccordionItem />
...
</Accordion>
```
or
```jsx
<AccordionItem weight="strong" />
```

Accordion, AccordionItem: Add `weight` support

---

.changeset/sour-days-whisper.md
packages/braid-design-system/lib/themes/tokenType.ts

The latest version of `FontMetrics` type in Capsize adds more properties, and we only populate the properties we require on the theme. Whitelisting the required properties to keep the themes explicit.

Whitelist only the required FontMetrics for theme tokens

---

.changeset/popular-cars-roll.md
packages/braid-design-system/lib/themes/makeBraidTheme.ts
packages/braid-design-system/lib/themes/makeVanillaTheme.ts

Internally some theme utilities were using Capsize’s `FontMetrics` as their expected payload, rather than correctly using the shape of the theme tokens. This makes Braid compatible with Capsize v3.x.

Use theme tokens for shape of font metrics

---

site/src/App/DocNavigation/DocProps.tsx

As part of compiling Braid, the internal directory structure changed. Updating the links to source and migration guides on the docs site.

site: Fix source and migration links

---

.changeset/soft-worms-check.md
packages/braid-design-system/src/lib/components/TextLink/TextLink.css.ts
packages/braid-design-system/src/lib/components/TextLink/TextLink.tsx

Increases the text weight of `weak` links to `medium`, increasing the affordance against standard text.
As a result, this makes the weight of all text links consistent.

TextLink, TextLinkButton: Increase text weight of weak links

---

.changeset/great-gorillas-live.md
packages/braid-design-system/src/lib/components/FieldLabel/FieldLabel.screenshots.tsx
packages/braid-design-system/src/lib/components/FieldLabel/FieldLabel.tsx
packages/braid-design-system/src/lib/components/MonthPicker/MonthPicker.screenshots.tsx
packages/braid-design-system/src/lib/components/PasswordField/PasswordField.screenshots.tsx
packages/braid-design-system/src/lib/components/RadioGroup/RadioGroup.screenshots.tsx
packages/braid-design-system/src/lib/components/TextField/TextField.screenshots.tsx
packages/braid-design-system/src/lib/components/Textarea/Textarea.screenshots.tsx
packages/braid-design-system/src/lib/components/private/Field/Field.tsx
packages/braid-design-system/src/lib/components/private/FieldGroup/FieldGroup.tsx

Previously, a `FieldLabel` without a `label` would return nothing. However, now that form fields can opt for [indirect or hidden labels] (via `aria-label` or `aria-labelledby`), the `description` should still be shown if provided.
> Note: The `secondaryLabel` and `tertiaryLabel` remain conditional based on the presence of a `label`. This is due to their location in the layout being anchored off the `label`.
```jsx
<FieldLabel
description="Description now visible without label"
/>
```
[indirect or hidden labels]: https://seek-oss.github.io/braid-design-system/components/TextField#indirect-or-hidden-field-labels

Show `description` on fields without a `label`

---

.npmrc
package.json
pnpm-lock.yaml

- Node.js 18.15.0
- pnpm 7.30.0
- pnpm [lockfile v6](https://pnpm.io/npmrc#use-lockfile-v6) which is the default in pnpm 8
Hopefully this fixes the peer deps issue from https://github.com/seek-oss/braid-design-system/pull/1234#issuecomment-1447382364 — [some defaults](https://github.com/pnpm/pnpm/releases/tag/v7.13.5) have changed between pnpm 7.8.0 and 7.30.0

Upgrade Node.js and pnpm

---

.depcheckrc.yaml
package.json
packages/codemod/package.json
packages/codemod/scripts/build.js
packages/codemod/src/codemod.ts
packages/codemod/src/plugin-deprecate/isBraidImport.test.ts
packages/codemod/src/plugin-deprecate/isBraidImport.ts
packages/codemod/src/plugin-deprecate/plugin-deprecate-atoms.ts
packages/codemod/src/plugin-deprecate/plugin-deprecate-props.ts
packages/codemod/src/plugin-deprecate/plugin-deprecate-vars.ts
packages/codemod/src/plugin-deprecate/plugin-import-update.ts
packages/codemod/src/plugin-deprecate/plugin-prop-rename.ts
packages/codemod/tsconfig.json
patches/yoga-layout-prebuilt@1.10.0.patch
pnpm-lock.yaml

The codemod appears to have been broken through the course of converting to a monorepo, and once fixed we discovered that a downstream dependency is broken (`yoga-layout-prebuilt`) which appears unlikely to be fixed.
Worked with @mrm007 to internalise this dependency from the codemod build, so that we could patch it to unblock features coming through.
Also added support for running codemod over Braid repo itself, rather than just consumer repos.

codemod: Fix build and enable running on Braid itself

---

.changeset/hungry-donuts-suffer.md
packages/braid-design-system/src/lib/components/Toggle/Toggle.tsx
packages/braid-design-system/src/lib/components/private/Field/Field.tsx
packages/braid-design-system/src/lib/components/private/FieldOverlay/FieldOverlay.tsx
packages/braid-design-system/src/lib/components/private/InlineField/StyledInput.tsx

**RadioItem, Toggle:** Use formAccent border when selected
Switch to using the `formAccent` border colour, rather than the `field` border colour, when in the selected state (e.g. `checked` for `RadioItem`, `on` for `Toggle`).

RadioItem, Toggle: Use formAccent border when selected

---

.changeset/big-dryers-report.md
.changeset/serious-hats-cry.md
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.tsx
packages/braid-design-system/src/lib/components/Badge/Badge.tsx
packages/braid-design-system/src/lib/components/Button/Button.tsx
packages/braid-design-system/src/lib/components/Card/Card.tsx
packages/braid-design-system/src/lib/components/Pagination/Pagination.tsx
packages/braid-design-system/src/lib/components/Textarea/Highlight/Highlight.tsx
packages/braid-design-system/src/lib/components/TooltipRenderer/TooltipRenderer.css.ts
packages/braid-design-system/src/lib/components/TooltipRenderer/TooltipRenderer.tsx
packages/braid-design-system/src/lib/components/useToast/Toast.tsx
packages/braid-design-system/src/lib/themes/baseTokens/apac.ts
packages/braid-design-system/src/lib/themes/docs/tokens.ts
packages/braid-design-system/src/lib/themes/tokenType.ts
packages/braid-design-system/src/lib/themes/wireframe/tokens.ts
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Extends the border radius scale to include `small` as a step below `standard`. This uplift is to support an upcoming design uplift that requires greater fidelity in the scale.
Note, the new value is also available as a responsive property.
Over time, individual components have reached for a larger radius in the scale, rather than increasing the scale at a theme level. This resulted in inconsistent use across the system, preventing uplift of the scale.
Re-aligning all components to use the scale consistently enables themes to apply very different radius scales — enabling an upcoming design uplift theme.

Add `small` radius & improve consistency of radius usage

---

fixtures/consumer/__snapshots__/build.test.ts.snap
packages/braid-design-system/package.json
packages/braid-design-system/src/lib/themes/baseTokens/apac.ts
packages/braid-design-system/src/lib/themes/docs/tokens.ts
packages/braid-design-system/src/lib/themes/tokenType.ts
packages/braid-design-system/src/lib/themes/wireframe/tokens.ts
pnpm-lock.yaml

Cleaning up the themes internally to pull the metrics from Capsize rather than use hard coded values in Braid.
Note also switching `wireframe` to use `Courier New` instead of `Courier` which had missing metrics that were filled manually.

Migrate to Capsize for font metrics

---

.changeset/big-hornets-prove.md
packages/braid-design-system/src/lib/themes/makeRuntimeTokens.ts

Previously the `webFont` on the theme was the `familyName` and was being used to construct a link tag to a Google Fonts stylesheet and provide to consumers via a runtime token. To enable fonts beyond Google Fonts, we are changing `webFont` to be a URL.
This does not impact existing themes (as there are no themes currently with a web font), and the contract of the runtime token (a constructed link tag) remains unchanged.

Add support for web fonts beyond Google Fonts

---

.changeset/polite-candles-float.md
packages/braid-design-system/src/lib/css/negativeMargin/negativeMargin.ts
packages/braid-design-system/src/lib/css/typography.ts

Fix error reading `standard` of undefined
The use of dynamic property access left some styles exposed to being marked as unused and tree shaken away.
Refactoring these styles to be explicitly referenced to ensure this will not be the case.

Fix error reading `standard` of undefined

---

packages/braid-design-system/src/lib/components/Button/Button.screenshots.tsx

Adding some screenshot tests for some edge cases so we can better visualise how they are handled in an upcoming button layout change.

Button: Add edge case screenshot tests

---

.changeset/quiet-parrots-watch.md
packages/braid-design-system/src/lib/components/Button/Button.css.ts
packages/braid-design-system/src/lib/components/Button/Button.tsx

Ensure the height of a `small` sized `Button` is not reliant on the text line height.
This enables different typographic scales across themes, while ensuring the `Button` height is relative.

Button, ButtonLink: Improve support for different typographic scales

---

.changeset/heavy-foxes-dress.md
packages/braid-design-system/src/lib/themes/baseTokens/apac.ts
packages/braid-design-system/src/lib/themes/docs/tokens.ts
packages/braid-design-system/src/lib/themes/tokenType.ts
packages/braid-design-system/src/lib/themes/wireframe/tokens.ts
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Extends the range of the space scale to include `xxxlarge`.
This addition is to support an upcoming design uplift that requires greater fidelity in the scale.
Note, the new value is also available as a responsive property.
```jsx
<Stack space="xxxlarge">...</Stack>
{/* Or responsively: */}
<Stack space={{ mobile: 'large', tablet: 'xxxlarge' }}>...</Stack>
```
```ts
import { atoms } from 'braid-design-system/css';
atoms({ paddingY: 'xxxlarge' })
```
```ts
import { vars } from 'braid-design-system/css';
const space = vars.space.xxxlarge;
```

Add `xxxlarge` to the space scale

---

.changeset/popular-teachers-care.md
packages/braid-design-system/src/lib/components/TooltipRenderer/TooltipRenderer.css.ts
packages/braid-design-system/src/lib/components/TooltipRenderer/TooltipRenderer.tsx

Removes the custom padding on tooltips in favour of using the space scale.
Previously, a custom value was used to complement the over sized radius which has now be reduced.

TooltipRenderer: Refine padding to complement radius scale

---

.changeset/chilly-fishes-fail.md
packages/braid-design-system/src/lib/components/MenuRenderer/MenuRenderer.tsx

Fixes a bug where the selection/highlight for a `MenuItem` could extend outside of the menu itself.

MenuRenderer: Hide overflow on menu

---

.changeset/shiny-penguins-hang.md
packages/braid-design-system/src/lib/components/private/Modal/ModalContent.tsx

Reducing the space between `title` and `description` to `small` to improve association of the header block content

Dialog, Drawer: Reduce space between title and description

---

.changeset/real-cooks-mate.md
packages/braid-design-system/src/lib/components/private/Keyline/Keyline.css.ts
packages/braid-design-system/src/lib/components/private/Keyline/Keyline.tsx

Previously the keyline width on the left determined its width using the space scale.
Re-aligning this to use the grid unit to enable themes with larger space scales.

Alert, Card, useToast: Decouple keyline width from space scale

---

.changeset/curvy-bottles-listen.md
packages/braid-design-system/src/lib/themes/makeVanillaTheme.ts
packages/braid-design-system/src/lib/themes/tokenType.ts
packages/braid-design-system/src/lib/themes/wireframe/tokens.ts

Provide support for themes to define their typographic line heights via `lineGap`.
This allows us to reason about the white space between wrapping lines of text in the same way we think about `Stack` spacing.
For a visual preview of this mental model head over to the [Capsize website].
[Capsize website]: https://seek-oss.github.io/capsize/
---
Note: Migrated the `wireframe` theme as a test/validation, but this will be leveraged in a production sense with the new theme coming soon.

Add support for defining line heights with lineGap

---

.changeset/quiet-comics-sin.md
packages/braid-design-system/src/lib/components/TooltipRenderer/TooltipRenderer.css.ts
packages/braid-design-system/src/lib/components/TooltipRenderer/TooltipRenderer.tsx

Use the correct semantic token for the background of tooltips.
While there is no visual change, this is just a clean up to ensure the palette usage remains consistent.

TooltipRenderer: Remove custom background

---

.changeset/honest-ants-sneeze.md
.changeset/tall-trees-smash.md
packages/braid-design-system/src/lib/components/Alert/Alert.tsx
packages/braid-design-system/src/lib/components/useToast/Toast.tsx
packages/braid-design-system/src/lib/components/useToast/useToast.docs.tsx

Refine the design to use consistent horizontal container inset, aligning content with elements like `Card`, as well as simplifying the design by removing the sidebar/keyline (consistent with `useToast`).
As a means to increase constrast against page content, the design has been updated to be presented on inverted backgrounds based on the color mode.
The design has also be refined to remove the sidebar/keyline (consistent with `Alert`), while also applying the `tone` to the provided `message`.

Alert, useToast: Design update

---

.changeset/mighty-apes-grow.md
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.docs.tsx
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.gallery.tsx
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.screenshots.tsx
packages/braid-design-system/src/lib/components/Dropdown/Dropdown.docs.tsx
packages/braid-design-system/src/lib/components/Dropdown/Dropdown.gallery.tsx
packages/braid-design-system/src/lib/components/Dropdown/Dropdown.screenshots.tsx
packages/braid-design-system/src/lib/components/FieldMessage/FieldMessage.docs.tsx
packages/braid-design-system/src/lib/components/FieldMessage/FieldMessage.gallery.tsx
packages/braid-design-system/src/lib/components/FieldMessage/FieldMessage.screenshots.tsx
packages/braid-design-system/src/lib/components/FieldMessage/FieldMessage.tsx
packages/braid-design-system/src/lib/components/MonthPicker/MonthPicker.docs.tsx
packages/braid-design-system/src/lib/components/MonthPicker/MonthPicker.gallery.tsx
packages/braid-design-system/src/lib/components/MonthPicker/MonthPicker.screenshots.tsx
packages/braid-design-system/src/lib/components/PasswordField/PasswordField.docs.tsx
packages/braid-design-system/src/lib/components/PasswordField/PasswordField.gallery.tsx
packages/braid-design-system/src/lib/components/PasswordField/PasswordField.screenshots.tsx
packages/braid-design-system/src/lib/components/RadioGroup/RadioGroup.docs.tsx
packages/braid-design-system/src/lib/components/RadioGroup/RadioGroup.tsx
packages/braid-design-system/src/lib/components/TextField/TextField.docs.tsx
packages/braid-design-system/src/lib/components/TextField/TextField.gallery.tsx
packages/braid-design-system/src/lib/components/TextField/TextField.screenshots.tsx
packages/braid-design-system/src/lib/components/Textarea/Textarea.docs.tsx
packages/braid-design-system/src/lib/components/Textarea/Textarea.gallery.tsx
packages/braid-design-system/src/lib/components/Textarea/Textarea.screenshots.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Add support for `caution` tone to form fields
Provide support for applying a `caution` tone to form fields.
Specifying this `tone` will provide the `IconCaution` alongside the provided `message`.
```jsx
<TextField tone="caution" message="Caution message" />
```

Add support for `caution` tone to form fields

---

.changeset/loud-birds-scream.md
.changeset/popular-kangaroos-walk.md
packages/braid-design-system/src/lib/components/Textarea/Highlight/Highlight.css.ts
packages/braid-design-system/src/lib/components/Textarea/Highlight/Highlight.tsx
packages/braid-design-system/src/lib/components/Textarea/Textarea.docs.tsx
packages/braid-design-system/src/lib/components/Textarea/Textarea.screenshots.tsx
packages/braid-design-system/src/lib/components/Textarea/Textarea.tsx
packages/braid-design-system/src/lib/components/Textarea/formatRanges.test.ts
packages/braid-design-system/src/lib/components/Textarea/formatRanges.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Providing a `tone` of `caution` along with a set of `highlightRanges` will now apply the `caution` tone to the text being highlighted.
To complement this feature, the design has been uplifted to work consistently across both the `critical` and `caution` tones.
```jsx
<Textarea
tone="caution"
message="Caution message"
highlightRanges={...}
/>
```

Textarea: Add support for `caution` highlightRanges

---

.changeset/shiny-chairs-lay.md
packages/braid-design-system/src/lib/components/MenuItemCheckbox/MenuItemCheckbox.css.ts
packages/braid-design-system/src/lib/components/MenuItemCheckbox/MenuItemCheckbox.tsx

Align the size of a `MenuItemCheckbox` with a `small` sized `Checkbox`.
Previously the size of the checkbox followed icon sizing, which saw the checkbox size follow the text size of theme — yielding unexpected sizing with different themes. Aligning to the `small` sized `Checkbox` size makes sizing more consistent across themes.

MenuItemCheckbox: Align checkbox size with a `small` Checkbox

---

.changeset/itchy-rabbits-study.md
packages/braid-design-system/src/lib/components/Textarea/Highlight/Highlight.css.ts

Remove the vertical padding on the highlight element to prevent the background colour overlapping the wavy underline in themes with tighter line heights.

Textarea: Adjust highlightRange background height

---

.changeset/wild-buttons-march.md
packages/braid-design-system/src/lib/components/private/InlineField/InlineField.css.ts
packages/braid-design-system/src/lib/components/private/InlineField/InlineField.tsx
packages/braid-design-system/src/lib/components/private/InlineField/StyledInput.tsx

Improve layout to work with updated `Badge` layout which is no longer driven by line height.

Checkbox, RadioItem: Fix alignment with updated `Badge` layout

---

.changeset/big-bats-decide.md
packages/braid-design-system/src/lib/components/private/InlineField/InlineField.css.ts
packages/braid-design-system/src/lib/components/private/InlineField/InlineField.tsx

A `RadioItem` and `Checkbox` previously created a new stacking context with an elevated `z-index` applied on hover, resulting in their labels overlaying other elements in an unpredictable ways — most noticable when [toggling nested content].
For example, toggling nested content containing an `Autosuggest`, would see the list of suggestions list would be overlayed by the next `RadioItem` on hover.
To fix this, the `z-index` is no longer elevated on hover, and additionally the nested content container applies an elevated index when the field is **checked**.
[toggling nested content]: https://seek-oss.github.io/braid-design-system/components/RadioGroup#toggling-nested-content
https://user-images.githubusercontent.com/912060/232358248-4f29e1f9-5440-4493-ba4f-e12f5b69b944.mov …

RadioItem, Checkbox: Fix stacking context behaviour

---

.changeset/healthy-mugs-sip.md
.changeset/warm-terms-film.md
packages/braid-design-system/src/lib/components/Card/Card.docs.tsx
packages/braid-design-system/src/lib/components/Card/Card.screenshots.tsx
packages/braid-design-system/src/lib/components/Card/Card.tsx
packages/braid-design-system/src/lib/components/Column/Column.screenshots.tsx
packages/braid-design-system/src/lib/components/Column/Column.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Provide support for making a `Card` use all available vertical space. This is useful when laying out rows of `Card` elements and having them all be equal height.
```jsx
<Card height="full">
...
</Card>
```
---
Provides support for full height content by growing the all `Column` elements to be uniform in height.
This will have no effect on the content itself, but enables consumers to create designs of uniform content, such as rows of `Card` elements.

Card, Column: Add support for full height

---

.changeset/curly-poets-obey.md
packages/braid-design-system/src/lib/components/private/Typography/Typography.tsx

Only show the truncate deprecation message when `truncate` is provided and set to `true`
Given we default it to `false` in the Typography component, we are currently showing the message a few too many times 🤦‍♂️

Text, Heading: Only show truncate deprecation message when true

---

.changeset/sour-goats-glow.md
packages/braid-design-system/src/lib/components/TextLink/TextLink.css.ts
packages/braid-design-system/src/lib/components/TextLink/TextLink.screenshots.tsx

Refine the underline position to be consistent across the whole typographic hierarchy, ensuring it does not interfere with wrapping lines of text.
Previews across `apac` and the upcoming `seekjobs` theme:
Before:
After:

TextLink, TextLinkButton: Improve underline position for wrapping text

---

.changeset/eight-clouds-hammer.md
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.screenshots.tsx
packages/braid-design-system/src/lib/components/Button/Button.screenshots.tsx
packages/braid-design-system/src/lib/components/ButtonIcon/ButtonIcon.screenshots.tsx
packages/braid-design-system/src/lib/components/Checkbox/Checkbox.screenshots.tsx
packages/braid-design-system/src/lib/components/Checkbox/CheckboxStandalone.screenshots.tsx
packages/braid-design-system/src/lib/components/Dropdown/Dropdown.screenshots.tsx
packages/braid-design-system/src/lib/components/Heading/Heading.screenshots.tsx
packages/braid-design-system/src/lib/components/Loader/Loader.screenshots.tsx
packages/braid-design-system/src/lib/components/MonthPicker/MonthPicker.screenshots.tsx
packages/braid-design-system/src/lib/components/PasswordField/PasswordField.screenshots.tsx
packages/braid-design-system/src/lib/components/Radio/Radio.screenshots.tsx
packages/braid-design-system/src/lib/components/RadioGroup/RadioGroup.screenshots.tsx
packages/braid-design-system/src/lib/components/Rating/Rating.screenshots.tsx
packages/braid-design-system/src/lib/components/Text/Text.screenshots.tsx
packages/braid-design-system/src/lib/components/TextField/TextField.screenshots.tsx
packages/braid-design-system/src/lib/components/TextLink/TextLink.screenshots.tsx
packages/braid-design-system/src/lib/components/Textarea/Textarea.screenshots.tsx
packages/braid-design-system/src/lib/components/Toggle/Toggle.css.ts
packages/braid-design-system/src/lib/components/Toggle/Toggle.screenshots.tsx
packages/braid-design-system/src/lib/components/Toggle/Toggle.tsx
packages/braid-design-system/src/lib/components/private/Field/Field.css.ts
packages/braid-design-system/src/lib/components/private/Field/Field.tsx
packages/braid-design-system/src/lib/components/private/InlineField/InlineField.css.ts
packages/braid-design-system/src/lib/components/private/InlineField/StyledInput.tsx
packages/braid-design-system/src/lib/utils/BackgroundContrastTest.tsx

Reduce visual noise when a form field is displayed in a dark container by hiding the default border.
As fields are light on light backgrounds, the border is used to delineate its bounds against the container, which is not relevant in a dark container.
Before:
After:

Hide field borders in dark containers

---

.changeset/loud-nails-float.md
packages/braid-design-system/src/lib/components/Button/Button.test.tsx
packages/braid-design-system/src/lib/components/Button/Button.tsx
packages/braid-design-system/src/lib/components/TextLinkButton/TextLinkButton.test.tsx
packages/braid-design-system/src/lib/components/TextLinkButton/TextLinkButton.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Provide support for `aria-label`, enabling additional context to be given to assistive technologies where context is typically visual.
```jsx
<Button aria-label="Save job">Save</Button>
```

Button, TextLinkButton: Add `aria-label` support

---

packages/braid-design-system/src/lib/components/Columns/Columns.playroom.tsx
packages/braid-design-system/src/lib/components/Inline/Inline.playroom.tsx
packages/braid-design-system/src/lib/components/Stack/Stack.playroom.tsx
packages/braid-design-system/src/lib/components/Tiles/Tiles.playroom.tsx
packages/braid-design-system/src/lib/playroom/cleanSpaceValue.ts

In order to guard against rendering errors in playroom while typing, we have a helper function for our Playroom wrapper components that ensures the `space` value that is passed is valid and not likely to cause an error trying to access invalid space styles.
This resulted in breaking the default value, seeing components such as `List` render with no space between its items (in Playroom only).

playroom: Fix space cleaning helper

---

.changeset/brave-singers-knock.md
packages/braid-design-system/src/lib/components/ContentBlock/ContentBlock.docs.tsx
packages/braid-design-system/src/lib/components/PageBlock/PageBlock.docs.tsx
packages/braid-design-system/src/lib/components/PageBlock/PageBlock.gallery.tsx
packages/braid-design-system/src/lib/components/PageBlock/PageBlock.screenshots.tsx
packages/braid-design-system/src/lib/components/PageBlock/PageBlock.snippets.tsx
packages/braid-design-system/src/lib/components/PageBlock/PageBlock.tsx
packages/braid-design-system/src/lib/components/index.ts
packages/braid-design-system/src/lib/playroom/snippets.ts
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap
site/src/App/DocNavigation/DocExample.tsx
site/src/App/routes/foundations/layout/layout.tsx
site/src/types.d.ts

Provides a top-level page container, constraining the content width (using `ContentBlock`) while establishing common screen gutters on smaller devices.
```jsx
<PageBlock width="large">
...
</PageBlock>
```

PageBlock: Add new component

---

.github/workflows/release.yml
.github/workflows/validate.yml

A [recent workflow run](https://github.com/seek-oss/braid-design-system/actions/runs/5107377818) uncovered a situation where Chromatic wasn't run on master because the 'Skip Duplicate Actions' action correctly identified that it did not need to run. However, the **Validate** workflow has a side-effect (running Chromatic on master which updates the baseline), which wasn't executed any more. See https://github.com/seek-oss/braid-design-system/pull/1309#issuecomment-1566368339
This change skips the **Chromatic** workflow step on `push`/`pull_request` but still runs it on `push: master`, ensuring the baseline in Chromatic is updated every time. This also runs Chromatic earlier (without waiting for all the **Lint & Test** steps, so pending pull requests get the updated snapshot baseline …

Always run Chromatic on master

---

.changeset/spotty-wasps-poke.md
packages/braid-design-system/src/lib/components/Dialog/Dialog.docs.tsx
packages/braid-design-system/src/lib/components/Drawer/Drawer.docs.tsx
packages/braid-design-system/src/lib/components/private/Modal/Modal.tsx
packages/braid-design-system/src/lib/components/private/Modal/modalTestSuite.tsx
packages/braid-design-system/src/lib/playroom/playroomState.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

To prevent a `Dialog` or `Drawer` from closing, e.g. due to validation, the `onClose` function can now return **false**.
```jsx
<Drawer
onClose={() => {
const valid = runValidation();
if (!valid) {
return false;
}
closeDrawer();
}}
/>
```

Drawer, Dialog: Support validation blocking closure of modal

---

.changeset/stale-ties-rescue.md
packages/braid-design-system/src/lib/components/Dialog/Dialog.screenshots.tsx
packages/braid-design-system/src/lib/components/Drawer/Drawer.screenshots.tsx
packages/braid-design-system/src/lib/components/private/Modal/ModalContent.tsx
packages/braid-design-system/src/lib/stories/all.stories.tsx
site/src/types.d.ts

Fix for a regression (introduced [here]) where the gutter around the close button was reduced — resulting in visually clashing with the content when scrolling.
(Also adding screenshot tests to prevent future regressions, and applying the modal backdrop to the Dialog and Drawer tests for better affordance)
[here]: https://github.com/seek-oss/braid-design-system/pull/1316/files#diff-d95ad2142ce38ae0fd78738b870d5b1ef50f5891e2f6f09d01ef2adf03d5b8dbR210

Drawer, Dialog: Increase gutter around close button

---

.changeset/empty-zebras-serve.md
packages/braid-design-system/src/lib/components/Page/Page.css.ts
packages/braid-design-system/src/lib/components/Page/Page.docs.tsx
packages/braid-design-system/src/lib/components/Page/Page.screenshots.tsx
packages/braid-design-system/src/lib/components/Page/Page.snippets.tsx
packages/braid-design-system/src/lib/components/Page/Page.tsx
packages/braid-design-system/src/lib/components/Page/PageContext.ts
packages/braid-design-system/src/lib/components/index.ts
packages/braid-design-system/src/lib/playroom/snippets.ts
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap
site/src/App/routes/foundations/layout/layout.tsx

The new `Page` component establishes a consistent page-level layout, by managing the relationship between the footer and the main content.
By default, for pages with limited content the `footer` will at a minimum be placed at the bottom of the screen, pushed beyond as the page content grows.
For pages with dynamic content, it is recommended to place the footer out of view by setting the `footerPosition` prop to `belowFold` to prevent the footer from popping in and out of view when the page content changes, e.g. toggling between a loading indicator and content.
```jsx
<Page footer={<Footer />}>
<Header />
{/* page content... */}
</Page>
```

Page: Add component

---

.changeset/few-wasps-applaud.md
packages/braid-design-system/src/lib/components/Tabs/TabPanel.tsx

Increase the radius of the focus outline to better align to the scale. A `TabPanel` is typically a "large" element containing entire sections of UI, so using the `large` radius to better align to the radius scale.
Example of before and after with the tab panel focused:

TabPanel: Align focus outline radius to scale

---

packages/braid-design-system/src/lib/components/TooltipRenderer/TooltipRenderer.docs.tsx

Adding some alternatives to the Tooltip documentation to guide consumers to other system elements when considering richer content.

Document tooltip alternatives

---

site/src/render.tsx

The docs site is hosted on GitHub Pages, and has a global `/braid-design-system` prefix for its URL paths. This is achieved in React Router using the `basename` prop on the various routers.
However, when the routers have a basename enabled, and sku requests an un-basenamed path to build, react router doesn't find anything. This causes all of the static renders in `IS_GITHUB_PAGES` mode to be empty.
We can fix this by having sku pass in the route with relevant basename prepended.
There's also a small change here to add the leading slash to the `routerBasename` const. This simplifies the logic required for the `route` and playroom path values, and all the example usage of basename I can find accepts the leading slash.

Fix rendering of GitHub Pages

---

.changeset/few-mayflies-lick.md
packages/braid-design-system/src/lib/components/RadioGroup/RadioGroup.tsx

Consider the `reserveMessageSpace` prop as well as `message` when conditionally applying internal padding between radio list and field message.

RadioGroup: Ensure `reserveMessageSpace` prevents layout shift correctly

---

.changeset/chilly-mugs-tickle.md
packages/braid-design-system/src/lib/components/Dialog/Dialog.screenshots.tsx
packages/braid-design-system/src/lib/components/private/Modal/ModalContent.tsx

Fixes an issue where the close button could protrude from a `Drawer`.
This was only visible when setting `position` to `left` and between a small range of screen widths — above 660px (`small` content width) and below 768px (`tablet` breakpoint).

Drawer: Prevent close button protruding in left position

---

.github/workflows/validate.yml

Attempt to fix Chromatic not picking up the latest builds on master (because the workflow had been cancelled)

Don't cancel other workflow runs for the same commit

---

.changeset/tough-icons-brush.md
packages/braid-design-system/src/lib/components/private/Modal/Modal.css.ts
packages/braid-design-system/src/lib/components/private/Modal/ModalExternalGutter.ts

Make use of the new [dynamic viewport units] for applying a max height to modal elements such as `Dialog` and `Drawer`. These new units take into account dynamic browser toolbars that expand and contract as the user scrolls, ensuring the browser interface never obscures the web site content.
Fix also incorporates fallback for older browsers to use regular viewport units.
Refactored the `maxSize` style to make better use of CSS vars, as well as refactoring the shared `externalGutter` to use the object syntax over the array syntax for responsive values.
[Before] / [After]
[Before]: https://braid-design-system--d1c4d3e2aab81e4e658e6d06f84e58cda82c1b0a.surge.sh/playroom/preview/#?code=N4Igxg9gJgpiBcIA8ARAlgQwDYQOYAIAXNQrGAXgB0R1s98AJGDKNAO12vwgAcY3ywQgCcArjAC+APkpt8+JABUYAD0IAxNDCxR8WDACNtVEAB …

Dialog, Drawer: Adapt max height to available viewport space

---

.changeset/curvy-ads-shake.md
packages/braid-design-system/src/lib/components/Button/Button.docs.tsx
packages/braid-design-system/src/lib/components/Button/Button.gallery.tsx
packages/braid-design-system/src/lib/components/Button/Button.screenshots.tsx
packages/braid-design-system/src/lib/components/Button/Button.tsx
packages/braid-design-system/src/lib/components/ButtonLink/ButtonLink.docs.tsx
packages/braid-design-system/src/lib/components/ButtonLink/ButtonLink.screenshots.tsx
packages/braid-design-system/src/lib/components/icons/Icons.screenshots.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap
site/src/App/SubNavigation/SubNavigation.tsx

**Button, ButtonLink:** Provide `formAccent` as the name for undefined tone
Formalise the name of the `undefined` tone as `formAccent`, making it more discoverable as an accent available for increased prominence.
_Note: Consumers should only apply this tone where an action should be emphasized explicitly. The `undefined` value is still valid for buttons that should follow the default button style of the theme._
```jsx
<Button tone="formAccent">
...
</Button>
```
Making a few docs changes in preparation for a later PR that changes the default tone/variant based on the `legacy` theme flag. Changes include:
- Be explicit about the `variant` and `tone` in docs, gallery, screenshots etc
- Move `Sizes` documentation below the `tone` documentation sections.

Button, ButtonLink: Provide `formAccent` as the name for `undefined` tone

---

.changeset/curly-gorillas-pull.md
packages/braid-design-system/src/lib/components/Button/Button.docs.tsx
packages/braid-design-system/src/lib/components/Button/Button.screenshots.tsx
packages/braid-design-system/src/lib/components/Button/Button.tsx

**Button, ButtonLink:** Default to ghost neutral in non-legacy themes
By default, a button now has a `neutral` tone and uses the `ghost` variant, allowing the visual prominence to be increased or decreased as required, enabling colour to be applied as accents and with purpose, rather than by default.
```jsx
<Button />
// => variant="ghost" & tone="neutral"
```
To compliment this, when a `tone` is purposefully applied, the default variant is becomes `solid` to maximise it’s impact — allowing the visual prominence to be reduced as needed.
```jsx
<Button tone="brandAccent" />
// => variant="solid" & tone="brandAccent"
```
Given the fundamental change in approach to colour and usage of such a core component, this change has been isolated newer themes and **does not impact `apac` and …

Button, ButtonLink: Default to ghost neutral in non-legacy themes

---

.github/workflows/release.yml
.github/workflows/validate.yml

Updating the Chromatic workflow run to ensure changes are accepted as baselines for all merges to master rather than just on release.
This ensures PRs opened by Changesets do not have to re-accept the delta of changes against the last released version of master.

Ensure Chromatic changes are accepted on unreleased master

---

packages/braid-design-system/src/lib/components/useResponsiveValue/useResponsiveValue.docs.tsx
site/src/App/DocNavigation/DocDetails.tsx
site/src/App/routes/gallery/Gallery.tsx
site/src/types.d.ts

Fix the `responsiveStyle` link on the `useResponsiveValue` docs page.
Enables the alternatives to be from sub paths other than `components`, e.g. `css`.

docs: Fix useResponsiveValue alternative link

---

packages/braid-design-system/src/lib/playroom/cleanSpaceValue.ts

Fixes responsive array space values in Playroom. A "[previous fix]" accidentally broke support for the array syntax, this PR extends the helper to support it.
[previous fix]: https://github.com/seek-oss/braid-design-system/pull/1305

playroom: Fix responsive array space values

---

site/src/App/Navigation/Navigation.css.ts
site/src/App/Navigation/Navigation.tsx
site/src/App/SubNavigation/SubNavigation.tsx

Moving the theme selector into the header on the docs site, so that it its always available regardless of scroll position in the side bar navigation.
Also adding some affordance to the top of the side bar when scrolled to improve affordance of the current scroll position not being at the top of the navigation.
| | Top of page | Scrolled navigation |
| --- | --- | --- |
|  Before | ![Top Before]  | ![Scrolled Before] |
|  After | ![Top After] | ![Scrolled After] |
[Top Before]: https://github.com/seek-oss/braid-design-system/assets/912060/d6937d39-272e-47ca-b99a-3107b31ce655
[Top After]: https://github.com/seek-oss/braid-design-system/assets/912060/a59639ea-52f4-43d4-808b-f7229f0e3634
[Scrolled Before]: https://github.com/seek-oss/braid-design-system/assets/912060/32d8897d-a9db-4453-b61e-8e …

docs: Move theme selector to header

---

.changeset/stupid-trees-remain.md
packages/braid-design-system/src/lib/components/Loader/Loader.tsx

Animating the dots in the Loader seems to affect their width, which pushes them outside of the viewbox resulting in clipping.
Easy fix here is to just make the viewbox slightly wider.
| Before | After |
| ------ | ------ |
| <img width="280" alt="Screenshot 2023-10-10 at 9 50 11 am" src="https://github.com/seek-oss/braid-design-system/assets/36141055/c6dbae0a-1e55-41ef-a847-4a193616296f"> | <img width="280" alt="Screenshot 2023-10-10 at 9 50 27 am" src="https://github.com/seek-oss/braid-design-system/assets/36141055/0ff2ef68-471c-46bf-95c3-43c9692b3bd0"> |

Fix Loader clipping

---

.changeset/red-melons-compete.md
packages/source.macro/__snapshots__/source.macro.test.ts.snap
packages/source.macro/source.macro.cjs
packages/source.macro/source.macro.test.ts

`@babel/generator`'s default value for `retainLines` is `false`. This means that applying the source macro on a code block with something like this:
```js
const options = [
{ value: "1", label: "Option 1" },
{ value: "2", label: "Option 2" },
{ value: "3", label: "Option 3" },
{ value: "4", label: "Option 4" },
{ value: "5", label: "Option 5" },
];
```
results in this
```js
const options = [
{
value: "1",
label: "Option 1",
},
{
value: "2",
label: "Option 2",
},
{
value: "3",
label: "Option 3",
},
{
value: "4",
label: "Option 4",
},
{
value: "5",
label: "Option 5",
},
];
```
Another example:
<details>
<summary>Before</summary>
```js
const responsiveValue = useResponsiveValue()
const isMobile = responsiveValue({
mobile: true,
tablet: false,
})
const isDesktopOrAbove = responsiveValue({ …
```

source macro: preserve new lines

---

packages/braid-design-system/src/lib/components/Button/Button.playroom.tsx
packages/braid-design-system/src/lib/components/Button/Button.tsx
packages/braid-design-system/src/lib/components/ButtonIcon/ButtonIcon.playroom.tsx
packages/braid-design-system/src/lib/components/ButtonIcon/ButtonIcon.tsx

Adding guards for the `tone` prop for `Button` and `ButtonIcon` in Playroom. This prevents an error from presenting while typing incomplete `tone` props.

Playroom: Guard tone on Button & ButtonIcon

---

.changeset/late-socks-double.md
packages/braid-design-system/src/lib/components/TooltipRenderer/TooltipRenderer.tsx

Fixes an issue where the tooltip would not re-evaluate it's position when the `trigger` or `children` prop changed while the tooltip was already open.
https://github.com/seek-oss/braid-design-system/assets/912060/72080336-719d-47fc-bb53-5582d81d83c9
[Before] / [After]
[Before]: https://braid-design-system--bb744806600c5337caa6b8ba2e99d26b01139dab.surge.sh/playroom/#?code=N4Igxg9gJgpiBcIA8AhCAPABABwIZSgEsA7AcwF4AdEAWxiIFcbqA%2BS4zTJAYQmIBcYAlABsIYANaYA7oSj8AFlRDoAzjVwiRrdpyQBlfrkmZVeMDGXp0I3ACdSMHR05dDxqWeOXq6zdpA2F1cuABUYdH4WAHlsIUxFQlVMPhgZQkVMCRgATwAjCHsoJAB6cMigkM5gR353QQAKahoIADcnEABKTAB%2BTCbgqqRy-gTU5TA7DMIwTVZQqdJHO0wW9qgAGjGIEX5CbEwoCBhVAUx4BtKRyqru%2BExiBi0AX10hlAZ%2Bfj4ASUhiN5VUyEABePhAtgcHUBVRmfHIwCQfz4AEE7HYINJDoQ7DAwHt4dQjtIASBMCUWK9BiFbHkYCJlABZNrQ6muOTKVS4drUGEhPjcEQzCQIhrdc …

TooltipRenderer: Re-evaluate position when trigger or children changes

---

.changeset/smooth-comics-call.md
packages/braid-design-system/src/lib/components/TextLink/TextLink.css.ts

A subtle bug affecting `TextLink` and `TextLinkButton` was causing underline thickness to change on hover. I believe this was unintentional since the base style contains an explicit `textDecorationThickness` property.
The bug is not visible at 100% zoom on Chrome, but becomes visible at larger zoom levels. The bug is pretty much always visible on Firefox. Safari is not affected by the bug.
The cause of the bug is the fact that the `weakLink` style is declared after the `base` style, so its `textDecoration` value ends up applying a default `textDecorationThickness` value of `auto` in [browsers that include `textDecorationThickness` in the shorthand](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration#browser_compatibility) (i.e. not Safari), overriding the `base` style's …

TextLink, TextLinkButton: Ensure consistent underline thickness

---

.changeset/calm-poets-float.md
packages/braid-design-system/src/lib/components/BraidProvider/BraidProvider.tsx

Node 21 has introduced a `navigator` object, where we could previously rely on there not being one in a Node environment.
This fixes that issue (which has been reported internally already). See changeset for full detail.

Fix navigator check for BraidProvider

---

packages/braid-design-system/src/lib/components/Button/Button.snippets.tsx

The `solid` Button snippets in Playroom were previously relying on the default variant for styling, which is now different depending on theme. Changing this to be explicit now.

docs: Explicitly apply solid variant to Button snippets

---

.github/workflows/validate.yml
fixtures/jest.config.js
jest.config.js
package.json
packages/braid-design-system/project.json

Sometimes the build mysteriously fails in CI when icons are added, e.g. #1390 has been failing on every commit.
There are two issues that have been intermittently observed since we moved to a monorepo with Nx:
1. Linting fails because Prettier expects but doesn't find the generated icon files. This is caused by a race condition where the linting task runs before the icon generation task ([example][lint]).
2. Tests fail because the generated icon files are missing ([example][test]). This is because an integration test runs the `build` script which wipes out all icon component files.
[lint]: https://github.com/seek-oss/braid-design-system/actions/runs/6856814056/job/18644723861#step:7:361
[test]: https://github.com/seek-oss/braid-design-system/actions/runs/6857128352/job/18645633637#step:8:4 …

Solve some task dependency issues

---

.changeset/odd-snails-hammer.md
fixtures/consumer/__snapshots__/build.test.ts.snap
package.json
pnpm-lock.yaml

This release fixes a bug where the reset module included all the tokens for all the themes. It builds upon #1397 and https://github.com/seek-oss/crackle/pull/136.
Additionally, this release contains significant compilation fixes to ensure that only styles for the imported components are included in the generated CSS. Previously, due to the default bundling behavior of Vite, styles for all Braid components were included in the generated CSS, regardless of which components were imported.
This should speed up compilation times and reduce the size of the generated CSS in consuming apps. Running `sku build` on a project created with `sku init` (without minification):
```
➜ hyperfine --setup 'pnpm install' --parameter-list BRAID_VERSION '32.14.0,fix-theme-side-effects' --prepare 'rm -rf …
```

Fix theme side effects

---

site/src/App/routes/foundations/tones/tones.tsx

The headings for the tone descriptions looked a little odd in their alignment.
I think it looks more natural to have them centered.
This also makes them linkable.
| Before | After |
| --------------------- | ------------------- |
| ![Screenshot before] | ![Screenshot after] |
[screenshot before]: https://github.com/seek-oss/braid-design-system/assets/36141055/c629e7cc-fd4b-4f13-881f-9eec0c8bc3a1
[screenshot after]: https://github.com/seek-oss/braid-design-system/assets/36141055/7954193f-c639-4224-9655-c23bc65c127c

Align tone headings

---

site/src/App/Seo/AppMeta.tsx

With the new changes to make the favicon path relative, we forgot to account for the sometimes present `/braid-design-system` basename.
React router has a hook for this, `useHref`.
We're now using this hook to generate the favicon paths, which means they should be correct in all environments.

Fix favicon paths

---

.changeset/late-bats-sleep.md
packages/docs-ui/README.md
packages/docs-ui/src/components/HeaderNavigation/HeaderNavigation.tsx
packages/docs-ui/src/index.ts
site/src/App/Navigation/Navigation.tsx

Add HeaderNavigation component to docs-ui and consume in Braid site

Add HeaderNavigation component to docs-ui

---

.changeset/ninety-moose-share.md
packages/braid-design-system/src/lib/components/Rating/Rating.docs.tsx
packages/braid-design-system/src/lib/components/Rating/Rating.screenshots.tsx
packages/braid-design-system/src/lib/components/Rating/Rating.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Provide a `weight` prop to customise the weight of the text rating alongside the stars.
```jsx
<Rating rating={3} weight="strong" />
```

Rating: Add `weight` support

---

.changeset/swift-emus-fry.md
packages/docs-ui/README.md
packages/docs-ui/src/components/HeaderNavigation/HeaderNavigation.tsx

Normally, the logo takes you to the '/' path. However, you can use this prop to set a custom home path should your project have one (i.e. a base path).

Add `logoHref` prop to `HeaderNavigation` component in docs-ui package

---

site/sku.routes.js
site/src/App/Updates/index.ts

Props are release paths were not included in the static render for icons, causing links such as https://seek-oss.github.io/braid-design-system/components/IconDownload/props to return a 404.
This change includes the correct paths in the static render.
Also, retire usage of `flatten` in favour of `.flat()` and `.flatMap`.

Fix routing for Icon page tabs

---

.changeset/config.json

Switching changesets over to only bump peer deps internally when out of range. This prevents the `docs-ui` package from getting a major version bump for every release of Braid.

changesets: Only bump peer deps out of range

---

packages/braid-design-system/src/lib/components/Button/Button.docs.tsx

Adding a linkable section to the Button docs on the site that talks about the reasoning behind no `disabled` state being available.

site: Add disabled button docs

---

.changeset/old-games-attack.md
.depcheckrc.yaml
.github/workflows/validate.yml
integration/__snapshots__/build-output.test.ts.snap
nx.json
package.json
packages/braid-design-system/crackle.config.ts
packages/braid-design-system/package.json
packages/braid-design-system/project.json
packages/braid-design-system/tsconfig.json
packages/docs-ui/package.json
packages/docs-ui/project.json
pnpm-lock.yaml

A recent Crackle PR https://github.com/seek-oss/crackle/pull/167 added a `package.mode` config option which helps avoid circular dependencies.
I've added the validate script before the fix ([failing build](https://github.com/seek-oss/braid-design-system/actions/runs/7838260132/job/21389406082)) and the Crackle config which fixes the issue in a separate commit.
The `package.json#sideEffects` flag in `braid-design-system` doesn't need to be updated. The patterns match both `src/` and `dist/` paths, as seen in the updated snapshots.

Add a `validate` script to check for circular dependencies

---

.changeset/cool-tomatoes-attend.md
packages/braid-design-system/src/lib/components/Tabs/Tab.tsx
packages/braid-design-system/src/lib/components/Tabs/Tabs.css.ts

Previously the `icon` slot on a `Tab` was cropped on the left to improve alignment with the active tab indicator.
For most icons in a `Tab`, this was subtle polish, but for others it had the undesirable side effect of clipping the side of the icon.
Removing the cropping until we have a better solution for trimming whitespace around icons.

Tab: Remove cropping of the icon slot

---

.changeset/itchy-mayflies-allow.md
packages/braid-design-system/src/lib/components/Heading/Heading.screenshots.tsx
packages/braid-design-system/src/lib/components/private/MaxLines/MaxLines.css.ts
packages/braid-design-system/src/lib/components/private/Typography/Typography.tsx

A combination of webkit-box, line-height and font-size can lead to instances where descender in the last line are cropped. 
This change focuses on preventing any potential cropping on text nodes

Text: Remove descender crop on truncated text

---

site/src/App/DocNavigation/DocProps.tsx

For reasons that defy explanation, the Props pages for Icons in the Braid docs are blank.
This can't be replicated locally, and it also works fine on surge.
To test this, we need to run it in a master build.
I'm temporarily adding a console log to see some of the details in the props page, as I suspect we're somehow triggering the null just after this line.

Add a testing log for the missing icon props page

---

site/src/App/DocNavigation/DocProps.tsx

The last test (#1461 ) revealed that the logs _were_ being triggered for the icon components, and they were as I expected them to be.
Next step is to check whether they're missing from the componentDocs json.
Have added a log to see the contents of componentDocs, as well as one to check if we are indeed hitting that null.

Add some additional logging for missing props

---

site/src/App/DocNavigation/DocProps.tsx

The last test (#1462) fixed it. No idea how though.
We did do two things here, so the next test is to unwind them one thing at a time and see when it goes back to breaking.

Remove one of the icon prop console logs

---

packages/braid-design-system/src/lib/components/index.ts
site/src/App/DocNavigation/DocProps.tsx

Continuing the investigation from (#1463), we've narrowed the problem down to the Icons sometimes not being present in the `componentDocs.json` file.
Next step is to work out why that is.
I'd like to see the contents of the star export for Icons, in case they're going missing in the master builds.

Log the icons that are generated in the build

---

site/project.json

We now suspect the issue (#1464) is that there's a race condition between `generate:icons` and `generate:component-docs`. The page is missing because the componentDocs.json gets generated after the icon files in CI.
To test this (and fix), the `generate:component-docs` task is now dependent on `^generate` rather than being a peer.
This should hopefully remove any possible race conditions.

Make component docs dependent on sub-`generate`s

---

packages/braid-design-system/src/lib/components/index.ts
site/src/App/DocNavigation/DocProps.tsx

I think the icon props page is fixed (#1466), so we can get rid of all the testing logs that were added to solve the problem.
NX task orchestration strikes again.

Remove all the bits added to test the icons page

---

site/src/App/Code/Code.tsx
site/src/App/routes/examples/job-summary/job-summary.tsx
site/src/App/routes/foundations/iconography/IconsDetails.tsx

In docs site (mainly docs code snippet examples) migrate to using the `Icon` prop in `Text` components, rather than including an `Icon` component as a child of `Text`.

Use Icon prop on Text component in all docs examples

---

site/project.json

We solved the missing props page issue by making `generate:icons` a dependency of `generate:component-docs`, which would force it to run first, thus preventing race conditions.
However, we did that by making `generate:component-docs` depend on `^generate`, which isn't the whole story.
This update should have much the same effect, but now more accurately captures that we need specifically icons to run before generating the component docs.

More accurately capture NX task dependencies

---

packages/braid-design-system/project.json

Build is currently failing for the site, as building the dev entries of Braid require the icons to have been generated.
Before:
After:

site: Fix nx task dependencies

---

.changeset/calm-fireants-exist.md
.changeset/gentle-ads-stare.md
packages/braid-design-system/src/lib/components/Dialog/Dialog.docs.tsx
packages/braid-design-system/src/lib/components/private/Modal/Modal.css.ts
packages/braid-design-system/src/lib/components/private/Modal/Modal.tsx

While `Modal` currently has an exit transition, it looks like a fall-through in a switch statement has prevented this from ever showing.
This change:
- Prevents fall through behaviour in the switch statement
- Smooths out the behaviour of the `Drawer` and `Dialog` exit animations
- Refactors animation style logic
- Fixes typo in `horizontalTransition`
- Updates `Dialog` docs page to add seperate state for the Dialog's width and open status

Fix Animation handling in Modal component

---

.changeset/few-ravens-cheat.md
.changeset/mighty-comics-tan.md
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.tsx
packages/braid-design-system/src/lib/components/ButtonIcon/ButtonIcon.docs.tsx
packages/braid-design-system/src/lib/components/ButtonIcon/ButtonIcon.gallery.tsx
packages/braid-design-system/src/lib/components/ButtonIcon/ButtonIcon.playroom.tsx
packages/braid-design-system/src/lib/components/ButtonIcon/ButtonIcon.screenshots.tsx
packages/braid-design-system/src/lib/components/ButtonIcon/ButtonIcon.snippets.tsx
packages/braid-design-system/src/lib/components/ButtonIcon/ButtonIcon.tsx
packages/braid-design-system/src/lib/components/private/FieldButtonIcon/FieldButtonIcon.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Introduce a new `small` size for `ButtonIcon` component. This size sits alongside the existing `standard` and `large` sizes.
```jsx
<ButtonIcon
size="small"
icon={<IconEdit />}
label="Small size"
/>
```
Subsequently adopting the `small` sized `ButtonIcon` for field actions such as clear field, or toggle password visibility.

ButtonIcon: Add `small` size

---

.github/workflows/preview-site.yml
.github/workflows/release.yml
.github/workflows/snapshot.yml
.github/workflows/validate.yml

Upgrading all Github actions to use latest node.
Also changing the way we detect duplicate parallel builds, aligning with Capsize which solved Chromatic builds getting out of step.

Upgrade GitHub actions and change parallel build check

---

.changeset/six-laws-burn.md
packages/braid-design-system/src/lib/components/Tag/Tag.docs.tsx
packages/braid-design-system/src/lib/components/Tag/Tag.gallery.tsx
packages/braid-design-system/src/lib/components/Tag/Tag.playroom.tsx
packages/braid-design-system/src/lib/components/Tag/Tag.screenshots.tsx
packages/braid-design-system/src/lib/components/Tag/Tag.snippets.tsx
packages/braid-design-system/src/lib/components/Tag/Tag.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Introduce a new `small` size for `Tag` component. This size sits alongside the existing `standard` size, which is the default.
```jsx
<Tag size="small">
Tag
</Tag>
```

Tag: Add `small` size

---

.changeset/brown-seahorses-notice.md
packages/braid-design-system/src/lib/components/PageBlock/PageBlock.docs.tsx
packages/braid-design-system/src/lib/components/PageBlock/PageBlock.gallery.tsx
packages/braid-design-system/src/lib/components/PageBlock/PageBlock.screenshots.tsx
packages/braid-design-system/src/lib/components/PageBlock/PageBlock.snippets.tsx
packages/braid-design-system/src/lib/components/PageBlock/PageBlock.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Add `small` to available `width` options of `PageBlock` to support narrower max width for page content.
Also introducing `full` as a `width` option to enable full width content, while still maintaining consistent screen gutters.
```jsx
<PageBlock width="small">
...
</PageBlock>
```

PageBlock: Add `small` and `full` width options

---

packages/braid-design-system/src/lib/components/private/Placeholder/Placeholder.tsx

Due to `Text` components containing validation that prevents nesting typography components, the `Placeholder` cannot be used in certain contexts due to using a `Text` component internally for its label.
The `Placeholder` should not be part of the nesting typography validation, so resetting the context.

Support `Placeholder` in tooltip content inside Text

---

.changeset/flat-coats-flow.md
packages/braid-design-system/src/lib/components/ContentBlock/ContentBlock.docs.tsx
packages/braid-design-system/src/lib/components/ContentBlock/ContentBlock.screenshots.tsx
packages/braid-design-system/src/lib/components/ContentBlock/ContentBlock.snippets.tsx
packages/braid-design-system/src/lib/components/ContentBlock/ContentBlock.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap
site/src/App/routes/foundations/layout/layout.tsx

Introduces horizontal alignment support for `ContentBlock`, enabling content to be constrained to a max width and aligned to the left.
Useful inside of larger `PageBlock` or `ContentBlock` elements when constraining the content for readability or length of form fields.
```jsx
<ContentBlock align="left">
...
</ContentBlock>
```

ContentBlock: Add support for left alignment

---

.changeset/kind-balloons-cough.md
packages/braid-design-system/src/lib/components/Button/Button.playroom.tsx
packages/braid-design-system/src/lib/components/Button/Button.tsx
packages/braid-design-system/src/lib/components/Button/buttonTones.ts
packages/braid-design-system/src/lib/components/ButtonIcon/ButtonIcon.docs.tsx
packages/braid-design-system/src/lib/components/ButtonIcon/ButtonIcon.gallery.tsx
packages/braid-design-system/src/lib/components/ButtonIcon/ButtonIcon.screenshots.tsx
packages/braid-design-system/src/lib/components/ButtonIcon/ButtonIcon.snippets.tsx
packages/braid-design-system/src/lib/components/ButtonIcon/ButtonIcon.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap
site/src/App/DocNavigation/DocNavigation.tsx

Introduces support for the `formAccent` tone on `ButtonIcon`.
The new tone sits alongside the existing `neutral` tone, while the `secondary` tone is now deprecated and to be removed in a future version (see [Migration Guide] below).
```jsx
<ButtonIcon tone="formAccent" icon={<IconAdd />} />
```
**MIGRATION GUIDE:**
For consumers of the now deprecated `secondary` tone, you can pro-actively migrate away from it by moving the `tone` to the icon itself:
```diff
<ButtonIcon
-  tone="secondary"
-  icon={<IconAdd />}
+  icon={<IconAdd tone="secondary" />}
```
[Migration Guide]: #migration-guide

ButtonIcon: Add `formAccent` tone

---

.changeset/slow-pears-deliver.md
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.tsx
packages/braid-design-system/src/lib/components/Tag/Tag.tsx
packages/braid-design-system/src/lib/components/private/FieldButtonIcon/FieldButtonIcon.tsx
packages/braid-design-system/src/lib/components/private/Modal/ModalContent.tsx
packages/braid-design-system/src/lib/components/useToast/Toast.tsx
site/src/App/routes/gallery/Gallery.tsx

Move secondary ButtonIcon tone to icons
Following the deprecation of the `secondary` tone of `ButtonIcon`, this updates all internal usages to apply the `secondary` tone directly to the icon.

Move secondary ButtonIcon tone to icons

---

.changeset/few-planets-invite.md
packages/braid-design-system/src/lib/components/Toggle/Toggle.docs.tsx
packages/braid-design-system/src/lib/components/Toggle/Toggle.gallery.tsx
packages/braid-design-system/src/lib/components/Toggle/Toggle.screenshots.tsx
packages/braid-design-system/src/lib/components/Toggle/Toggle.snippets.tsx
packages/braid-design-system/src/lib/components/Toggle/Toggle.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Add `togglePosition` prop to `Toggle` component:
* `togglePosition="leading"` - positions the toggle before the label text
* `togglePosition="trailing"` - positions the toggle after the label text
If no `togglePosition` prop is provided:
* If `align` is set to `left`,  `togglePosition` is set to `leading`
* If `align` is not set to `left`, `togglePosition` is set to `trailing`
This is to preserve the current behaviour with `align` to avoid a breaking change
See changeset for more details

Add `togglePosition` prop to `Toggle` component

---

.changeset/brave-walls-ring.md
.changeset/sixty-knives-worry.md
packages/braid-design-system/src/lib/components/Toggle/Toggle.screenshots.tsx
packages/braid-design-system/src/lib/components/Toggle/Toggle.tsx

Label text can be vertically misaligned in some scenarios - [Playroom](https://seek-oss.github.io/braid-design-system/playroom/#?code=N4Igxg9gJgpiBcIA8AhCAPABAIwIZgGsBzAJwgFcA7KAXgB1wSBLAFybFwBsAZJogCxYMAfHUqZMSAJKVOTSjExc%2BlAJr1wMSixgkGmAM4AHfDA3p0BgLZdOIsRIlIAKhCJFOizrmwxOG7h8-fQMmAC8zBmtbfQB6UXFHFxh0FkNwyJBozjsQYWzOTB1UpFjnFJYEp1iZOQUE0rR0BJAAGhAWfhgrGAMEAG0QXBMwNqyYGAIAKQhsPoBddoB3JihOvvh%2BgGYAJgAGeYBfIA)
With a small size `Toggle`, the text sits slightly too high
This change resolves these issues

Toggle: fix label text vertical centering for small size

---

.changeset/sharp-bears-remember.md
packages/braid-design-system/src/lib/components/Tag/Tag.docs.tsx
packages/braid-design-system/src/lib/components/Tag/Tag.gallery.tsx
packages/braid-design-system/src/lib/components/Tag/Tag.screenshots.tsx
packages/braid-design-system/src/lib/components/Tag/Tag.snippets.tsx
packages/braid-design-system/src/lib/components/Tag/Tag.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Tag actions have been extended to now support being “added”.
A `Tag` will include a small add icon button when both an `onAdd` handler and `addLabel` prop are provided.
```jsx
<Tag onAdd={() => {...}} addLabel="Add Tag" />
```

Tag: Introduce “addable” support

---

.changeset/purple-clocks-impress.md
packages/braid-design-system/src/lib/components/Button/Button.docs.tsx
packages/braid-design-system/src/lib/components/Toggle/Toggle.css.ts
packages/braid-design-system/src/lib/components/Toggle/Toggle.docs.tsx
packages/braid-design-system/src/lib/components/Toggle/Toggle.gallery.tsx
packages/braid-design-system/src/lib/components/Toggle/Toggle.screenshots.tsx
packages/braid-design-system/src/lib/components/Toggle/Toggle.snippets.tsx
packages/braid-design-system/src/lib/components/Toggle/Toggle.test.tsx
packages/braid-design-system/src/lib/components/Toggle/Toggle.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

This change:
* Adds `bleedY` prop
* Separates Toggle component JSX into sub sections, as the component is getting a bit lengthy
* Adds dev warning if `Toggle` is used without specifying `bleedY`
* Adds `bleedY` set to `true` in all `Toggle` uses across the repo

Toggle: add `bleedY` prop

---

.changeset/strong-eggs-relax.md
packages/braid-design-system/src/lib/components/Toggle/Toggle.css.ts
packages/braid-design-system/src/lib/components/Toggle/Toggle.tsx

**Toggle:** Remove tick icon & fix antialias haze when selected
Simplying the selected state design by removing the tick icon from the toggle thumb.
Also fixes the antialias haze that appears around the thumb when selected.
Also reverts internal refactor to use separate components due to re-rendering preventing the animation. Best reviewed by turning off white space highlighting.

Toggle: Remove tick and fix antialias haze

---

site/src/App/ThemeSetting/ThemedExample.css.ts

Lighten the visual treatment of the transparent background pattern for the examples on the docs site

site: Update example bgs from checkers to dots

---

.changeset/silver-carpets-act.md
packages/braid-design-system/src/lib/themes/seekJobs/tokens.ts

**seekJobs:** Use Tahoma for Thai fallback font
Currently in the `seekJobs` theme, the fallback font for the Thai character set resolves to the default system font which differs by operating system. By choosing a deterministic fallback that is available across operating systems, we can use [Capsize] to [improve the alignment] with the SEEK Sans web font, and reduce Cumulative Layout Shift for experiences that use Thai.
Additionally, adding `sans-serif` as an ultimate fallback in the event that we ever fall all the way through the stack on an obscure operating system.
[Capsize]: https://seek-oss.github.io/capsize/
[improve the alignment]: https://github.com/seek-oss/capsize?tab=readme-ov-file#createfontstack

seekJobs: Use Tahoma for Thai fallback font

---

packages/braid-design-system/src/lib/components/Bleed/Bleed.docs.tsx
packages/braid-design-system/src/lib/components/Card/Card.docs.tsx
site/src/App/routes/foundations/layout/layout.tsx

A quick once over of the content within the layout guide, mainly addressing spacing values and Card usage.
Also updating the visuals on the Bleed documentation for better visual clarity

site: Update layout guide content

---

site/src/App/routes/gallery/Gallery.tsx

Layout components are moved into their own section in Gallery, making them more discoverable and adding some more hierarchy to the components view

site: Move 'Layout' components into separate section in Gallery

---

site/src/App/ThemeSetting/ThemedExample.css.ts
site/src/App/ThemeSetting/ThemedExample.tsx

The forced dark canvas on the token examples on site got broken in some of its late refactoring, so this fixes them up.

site: Fix dark canvas for token examples

---

site/src/App/ThemeSetting/ThemeSettingContext.tsx

Switching the default docs theme to 'seekJobs', as it is now the standard flagship theme

site: Switch default theme from 'apac' to 'seekJobs'

---

.changeset/config.json

Noticed these packages appearing in the Version Packages PR when they should be ignored by Changesets

changesets: Ignore internal packages and site

---

.changeset/perfect-rockets-tan.md
packages/braid-design-system/src/lib/components/Badge/Badge.screenshots.tsx
packages/braid-design-system/src/lib/components/Badge/Badge.tsx

Ensure that the foreground text of a `Badge` always follows the correct tone for the background colour.
Fixes a bug where using a `Badge` in a `List` that overrides the default tone would result in the `Badge` text following the `List` tone instead of the `Badge` tone.

Badge: Ensure label follows correct tone

---

packages/braid-design-system/src/lib/components/Actions/Actions.docs.tsx
packages/braid-design-system/src/lib/components/Actions/Actions.gallery.tsx
packages/braid-design-system/src/lib/components/Actions/Actions.screenshots.tsx
packages/braid-design-system/src/lib/components/Actions/Actions.snippets.tsx
packages/braid-design-system/src/lib/components/Actions/Actions.tsx

Part of a wave of PRs to improve and update the documentation. Goals for this include:
- Align snippets, examples, etc to spacing guidelines
- Improve quality & consistency of Playroom snippets
- Pull in relevant guidance from internal "Pattern Guides"

site: Update Actions documentation and examples

---

.changeset/fast-kangaroos-switch.md
packages/braid-design-system/src/lib/components/Column/Column.screenshots.tsx
packages/braid-design-system/src/lib/components/Column/Column.tsx
packages/braid-design-system/src/lib/components/Columns/Columns.docs.tsx
packages/braid-design-system/src/lib/components/Inline/Inline.docs.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Introduce new `hideAbove` and `hideBelow` props on column for responsively hiding columns across breakpoint.
These props can be used either separately or in combination to optimise content display across different screen sizes.
```jsx
<Columns space="small">
<Column>
<Placeholder height={60} label="Always visible" />
</Column>
<Column hideBelow="tablet">
<Placeholder height={60} label="Tablet and above" />
</Column>
<Column hideAbove="mobile">
<Placeholder height={60} label="Mobile Only" />
</Column>
</Columns>
```

Column: Add support for hide above/below breakpoint

---

packages/braid-design-system/src/entries/css/atoms.docs.tsx
packages/braid-design-system/src/lib/components/Box/Box.docs.tsx

Fix an issue where the docs site was rendering array indexes instead of the correct values for unresponsive prop values.
Need to handle both the possible array and object data structures.
Before:
After:

site: Fix Box & atoms unresponsive prop values

---

.changeset/proud-moles-exist.md
packages/braid-design-system/src/lib/components/Card/Card.snippets.tsx
packages/braid-design-system/src/lib/components/Columns/Columns.docs.tsx
packages/braid-design-system/src/lib/components/MenuRenderer/MenuRenderer.docs.tsx
packages/braid-design-system/src/lib/components/OverflowMenu/OverflowMenu.docs.tsx
packages/braid-design-system/src/lib/components/Spread/Spread.css.ts
packages/braid-design-system/src/lib/components/Spread/Spread.docs.tsx
packages/braid-design-system/src/lib/components/Spread/Spread.gallery.tsx
packages/braid-design-system/src/lib/components/Spread/Spread.playroom.tsx
packages/braid-design-system/src/lib/components/Spread/Spread.screenshots.tsx
packages/braid-design-system/src/lib/components/Spread/Spread.snippets.tsx
packages/braid-design-system/src/lib/components/Spread/Spread.tsx
packages/braid-design-system/src/lib/components/index.ts
packages/braid-design-system/src/lib/playroom/components.ts
packages/braid-design-system/src/lib/playroom/snippets.ts
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap
site/src/App/DocNavigation/DocReleases.tsx
site/src/App/routes/examples/job-summary/job-summary.tsx
site/src/App/routes/foundations/layout/layout.tsx
site/src/App/routes/gallery/Gallery.tsx

Introduce a new layout component, `Spread`, used to justify content with both an equally distribute and a specify the minimum amount of space in between each child.
The `Spread` component will work horizontally by default:
```jsx
<Spread space="small" alignY="center">
<Heading level="4">Heading</Heading>
<OverflowMenu label="Options">
<MenuItem>First</MenuItem>
<MenuItem>Second</MenuItem>
</OverflowMenu>
</Spread>
```
But can be switched to `vertical` via the `direction` prop:
```jsx
<Spread space="large" direction="vertical">
<Stack space="small">
<Heading level="4">Heading</Heading>
<Text>Text</Text>
</Stack>
<Text size="small" tone="secondary">
Date
</Text>
</Spread>
```
Includes updated snippets and examples to use latest spacing and layout guidance, e.g. `Job …

Spread: Add new layout component

---

.changeset/bright-nails-cry.md
packages/braid-design-system/src/lib/components/MenuRenderer/MenuRenderer.css.ts
packages/braid-design-system/src/lib/components/MenuRenderer/MenuRenderer.tsx

Limit the menu to show a maximum of around 10 items before scrolling (a little less so its evident there is more to scroll to).

MenuRenderer, OverflowMenu: Limit the menu height

---

.changeset/forty-coins-wait.md
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.docs.tsx
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.tsx
packages/braid-design-system/src/lib/components/Autosuggest/reverseMatches.test.ts
packages/braid-design-system/src/lib/components/Autosuggest/reverseMatches.ts

Currently, the `suggestionHighlight` prop when set to `remaining` will set every match range to end with the length of the suggestion.
This does not work when matches are found in multiple words, where the match ranges may end at the end of a word rather than the end of the total string.

Autosuggest: Fix bug in `suggestionHighlight` prop when using `remaining`

---

.changeset/hungry-ads-cheer.md
packages/braid-design-system/src/lib/components/Heading/Heading.screenshots.tsx
packages/braid-design-system/src/lib/components/Text/Text.screenshots.tsx
packages/braid-design-system/src/lib/components/private/Typography/Typography.tsx

Provide `min-width` to `Text` and `Heading` components to ensure `maxLines` truncates as expected when typography components are used as a direct child of a flex container.

Text, Heading: Ensure `maxLines` truncates correctly in flex container

---

.changeset/smart-rocks-wait.md
packages/braid-design-system/src/lib/components/Spread/Spread.css.ts
packages/braid-design-system/src/lib/components/Spread/Spread.screenshots.tsx
packages/braid-design-system/src/lib/components/Spread/Spread.tsx

Align the behaviour of children in `Spread` to be the same as `Inline` children.
This makes their behaviour more predicatable when spreading full width elements, while also ensuring child elements are not stretched vertically.

Spread: Apply content width to children

---

packages/braid-design-system/src/lib/components/List/List.test.tsx

Adding tests to `List` component to ensure semantic markup.
This was previously implicitly tested by `Stack`, but with an upcoming change to our layout components, this should be explicitly tested by `List`.

List: Add tests for semantic markup

---

packages/braid-design-system/src/lib/components/Column/Column.screenshots.tsx
packages/braid-design-system/src/lib/components/Columns/Columns.docs.tsx
packages/braid-design-system/src/lib/components/Inline/Inline.docs.tsx
packages/braid-design-system/src/lib/components/Spread/Spread.docs.tsx
packages/braid-design-system/src/lib/components/Stack/Stack.docs.tsx
packages/braid-design-system/src/lib/components/Stack/Stack.snippets.tsx

Adding some missing "Semantic elements" documentation to document the `component` prop.
Also adding the missing `reverse` documentation from the `Inline` component.

site: Add `component` and missing `reverse` docs

---

.changeset/bright-squids-ring.md
jest/setupTests.ts
packages/braid-design-system/src/lib/components/BraidTestProvider/BraidTestProvider.tsx

In an earlier [PR] the `Autosuggest` moved from using a custom scrolling function over to the native [scrollIntoView API].
Due to [jsdom not supporting it], we stubbed it for *our tests*, but this has resulted in the following error:
```
Error: Uncaught [TypeError: highlightedItem?.scrollIntoView is not a function]
```
Moving the stubs to a side effect of importing `BraidTestProvider` to solve it in all Braid consumers test environments.
[PR]: https://github.com/seek-oss/braid-design-system/pull/1571/files
[scrollIntoView API]: https://caniuse.com/mdn-api_element_scrollintoview
[jsdom not supporting it]: https://github.com/jsdom/jsdom/issues/1695

BraidTestProvider: Provide `scrollIntoView` stub function for jsdom

---

.changeset/good-hats-remember.md
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.css.ts
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.tsx

Updating the design of the suggestion group headings, moving from `formAccent` to `secondary` tone, from all caps to provided casing, and from `xsmall` to `small` size.
(Left: before, right: after)

Autosuggest group headings

---

.changeset/shiny-peas-love.md
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.tsx
packages/braid-design-system/src/lib/components/Dropdown/Dropdown.tsx
packages/braid-design-system/src/lib/components/MonthPicker/MonthPicker.tsx
packages/braid-design-system/src/lib/components/PasswordField/PasswordField.tsx
packages/braid-design-system/src/lib/components/RadioGroup/RadioGroup.tsx
packages/braid-design-system/src/lib/components/TextField/TextField.tsx
packages/braid-design-system/src/lib/components/Textarea/Textarea.tsx
packages/braid-design-system/src/lib/components/private/Field/Field.tsx
packages/braid-design-system/src/lib/components/private/FieldGroup/FieldGroup.tsx

Introduce development-time validation for the `label` prop on form fields to guard against blank values and guide towards the alternative labelling options that are available.
This validation helps ensure that all fields are accessible to screen readers and other assistive technologies.

Validate accessible field labels in development

---

.changeset/selfish-terms-shake.md
packages/braid-design-system/src/lib/components/Column/Column.screenshots.tsx
packages/braid-design-system/src/lib/components/Columns/Columns.docs.tsx
packages/braid-design-system/src/lib/components/Columns/Columns.gallery.tsx
packages/braid-design-system/src/lib/components/Columns/Columns.screenshots.tsx
packages/braid-design-system/src/lib/components/Columns/Columns.tsx
packages/braid-design-system/src/lib/components/Inline/Inline.docs.tsx
packages/braid-design-system/src/lib/components/Inline/Inline.tsx
packages/braid-design-system/src/lib/utils/collapsibleAlignmentProps.ts

The `reverse` prop is only respected in combination with `collapseBelow`.
This ensures the content is reversed on the same row, but follows the document order when collapsed.
If content needs to be reversed without `collapseBelow` then it should be reversed in the document/source order directly.

Columns, Inline: Only respect `reverse` with `collapseBelow`

---

.changeset/red-ladybugs-doubt.md
packages/braid-design-system/src/lib/components/Stack/Stack.docs.tsx
packages/braid-design-system/src/lib/components/Stack/Stack.screenshots.tsx
packages/braid-design-system/src/lib/components/Stack/Stack.tsx

As a convenience, the `align` prop sets the text alignment for the container, meaning any nested `Text` or `Heading` components will inherit this alignment by default.
This can be overridden by setting the alignment explicitly on the relevant `Text` or `Heading` component.

Stack: Set default text alignment based on `align`

---

.changeset/fair-donuts-worry.md
packages/braid-design-system/package.json

To enable Braid to leverage newer React APIs, we are no longer providing support for React v17.x.
React 18 was released in March 2022 and consumers were encouraged to upgrade to this as part of the Braid v32 release in Feb 2023 (which dropped React 16 support).
Removing support for React 17 allows us to simplify and streamline a lot of our component APIs, which will have downstream improvements on consumer codebases.
Consumers still on v17 should follow the [How to Upgrade to React 18 guide].
For [sku] consumers who upgraded to Braid v32 and added the "`jsx-runtime` workaround for ESM incompatibility", this can now be safely removed this from their webpack configuration once updated to React 18:
```diff
// sku.config.ts
{
dangerouslySetWebpackConfig: (config) =>
webpackMerge(config, {
- …
```

Drop support for React 17.x

---

.changeset/lucky-bottles-relate.md
packages/braid-design-system/src/lib/components/useColor/useColor.ts

Align the available `background` tokens between `Box`, `vars`, and the `useColor` Hook.
Removes the `surfaceDark` and `bodyDark` tokens that were mistakenly exposed in the `useColor` Hook.

useColor: Align `background` tokens with `Box` and `vars`

---

.changeset/heavy-radios-remain.md
packages/braid-design-system/src/lib/themes/seekJobs/tokens.ts

The size of the `gutter` token on the `seekJobs` theme will be reduce from `large` (i.e. 32px), to `medium` (i.e. 24px).
This is a semantic token that runs through many system components, and consumers are encouraged to perform a visual design audit to ensure experiences are laid out as intended.

seekJobs: Reduce size of `gutter` token

---

.changeset/perfect-zoos-confess.md
packages/braid-design-system/src/lib/components/PageBlock/PageBlock.docs.tsx
packages/braid-design-system/src/lib/components/PageBlock/PageBlock.tsx

Increase the horizontal screen gutter from `xsmall` (i.e. 12px) to `small` (i.e. 16px) on mobile devices.

PageBlock, Drawer: Increase screen gutter on mobile

---

packages/braid-design-system/src/lib/components/Inline/Inline.css.ts
packages/braid-design-system/src/lib/components/Inline/Inline.screenshots.tsx
packages/braid-design-system/src/lib/components/Tiles/Tiles.css.ts
packages/braid-design-system/src/lib/components/Tiles/Tiles.screenshots.tsx

Identified an issue where truncated items (more explicitly, elements with `white-space: nowrap`) within an `Inline` or `Tiles` would not truncate correctly, and break the boundaries of the parent container.
The fix is to ensure children of these components apply the `min-width: 0` so flex and grid infer their width and correctly truncate.
There is no changeset as this is a refactor on the CSS gap updates already in the `next` branch

Inline, Tiles: Enable truncated items

---

.changeset/yellow-mirrors-hear.md

Adding changeset to capture the Braid peer dep change in the `docs-ui` package Changelog

docs-ui: Bump Braid peer dependency to v33

---

.changeset/loud-wasps-tickle.md
packages/braid-design-system/src/lib/components/useToast/Toast.tsx

Applies left alignment to `Toast` content to ensure intended alignment, regardless of other styles applied.

useToast: Ensure content is left aligned

---

packages/braid-design-system/src/lib/components/Inline/Inline.playroom.tsx
packages/braid-design-system/src/lib/components/Stack/Stack.playroom.tsx

Missed this when we removed the `component` validation, and by destructuring it we would never set the right component in Playroom (most notably, list items would always have the default style)

playroom: Fix Stack and Inline `component` prop

---

.changeset/wet-bananas-end.md
packages/braid-design-system/src/lib/components/Disclosure/Disclosure.docs.tsx
packages/braid-design-system/src/lib/components/Disclosure/Disclosure.gallery.tsx
packages/braid-design-system/src/lib/components/Disclosure/Disclosure.screenshots.tsx
packages/braid-design-system/src/lib/components/Disclosure/Disclosure.snippets.tsx
packages/braid-design-system/src/lib/components/Disclosure/Disclosure.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Introduce the `size` prop to the `Disclosure` component, providing the same options as the `Text` component.
```jsx
<Disclosure
size="small"
>
...
</Disclosure>
```

Disclosure: Add `size` support

---

site/src/App/routes/foundations/iconography/IconsBrowse.tsx

Switching to `Tiles` for more even layout space.
NB: desktop gets more columns than wide because desktop doesn't show the sidebar

docs: refine icon browse layout

---

.changeset/yellow-frogs-wait.md
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.tsx

Applies left alignment to `Autosuggest` dropdown content to ensure consistent alignment, even when inside centered layout containers.

Autosuggest: Ensure dropdown content is left aligned

---

.github/workflows/preview-site.yml
site/src/App/Navigation/Navigation.tsx

Centralising the definition of the preview path for deployments to a single env var. This makes it easier to update the path once centrally (e.g. the custom grad-connection site we maintain).
Also fixing a double slash on the production site link when on the root page.

site: Improve definition of preview path, fix double slash on root

---

.github/workflows/release.yml

Whitelisting the `preview` (and `grad-connection`) folders to prevent the release of the docs site from cleaning the output directory and blowing them away.
Also opting into `single-commit` as an optimisation as we have no need to git history on the `gh-pages` branch.

Preserve preview sites on master release

---

.github/workflows/release.yml

Ensures that the site is only built and deployed if either a package was just published, or if there are no changesets in master.
Additionally ensuring the clean-exclude is considered only at the root level so as not to confuse the Playroom Preview folder with the preview deployments directory.

site: Fix Playroom Preview deployments

---

packages/braid-design-system/src/lib/components/OverflowMenu/OverflowMenu.css.ts
packages/braid-design-system/src/lib/components/OverflowMenu/OverflowMenu.tsx

https://github.com/seek-oss/braid-design-system/pull/1658 introduced `justifySelf: 'flex-end'` on `OverflowMenu` to simplify its internal structure and ensure it would right align in its parent container regardless of the display property used.
It looks like `justifySelf` for block level boxes is only supported in [Chrome 130+](https://chromium-review.googlesource.com/c/chromium/src/+/5838707). Setting `display="flex"` appears to make no difference.
This [Playroom](https://seek-oss.github.io/braid-design-system/playroom/#?code=N4Igxg9gJgpiBcIA8AhCAPABFAlgZwAcAbAQwE8BeAHRADMiZ0bM8AXMhi4YTAKwFc2OWmQDKMIrXiYa9RgFoYAOyjMAvmoB8VJZkxIAKo1abRrEipIAnKJlbGkAeiPoTOp2nTalIADQhWAAsYAFsYPAQAbRA8GBgAawApCAAjCIBdfwB3HCggiPhIgHYANgAOdLUgA) will currently right align the content in Chromium browsers with …

OverflowMenu: fix layout issue

---

.changeset/tender-olives-sell.md
packages/braid-design-system/src/lib/components/MenuRenderer/MenuRenderer.tsx

Fixes a bug where menus could be obscured when rendered inside a `Dialog` or `Drawer` component.
`MenuRenderer` and Modals are both in separate Braid portals, which are in the same stacking context. Hence, their `zIndex` values are compared. `MenuRenderer` previously had a lower `zIndex` value than Modals, and hence if one was used in a `Model` it would be stacked incorrectly. As they now have the same `zIndex` value, the element later in the DOM is stacked above, which works correctly for `Menus` in and out of `Modals`.
In this solution, the `zIndex` value for `MenuRenderer` is not semantically accurate. This should likely be revisited in the future to address this issue.

MenuRenderer, OverflowMenu: Ensure menus work in Modal components

---

.changeset/clever-seahorses-yell.md
packages/braid-design-system/src/lib/components/Tiles/Tiles.css.ts
packages/braid-design-system/src/lib/components/Tiles/Tiles.tsx

Optimise layout implementation to prevent hydration error.
The hydration error was:
```
Warning: Prop `style` did not match.
Server: "--mobileColumnsVar__3trpbp1:3"
Client: "--mobileColumnsVar__3trpbp1:3;--tabletColumnsVar__3trpbp2:;--desktopColumnsVar__3trpbp3:;--wideColumnsVar__3trpbp4:" Error Component Stack
```
This meant that on the client, setting a CSS var to an empty string did not result it in being omitted from the inline style (but strangely not on the server 🤔).
This change sets the var to undefined instead of empty string (when it is not explicitly set), which ensures it is always omitted from the inline style, preventing the hydration error.
Edit: This change now always sets explicit column values at different breakpoints to ensure nested `Tiles` with responsive columns work …

Tiles: Prevent hydration error

---

.changeset/four-cups-live.md
packages/braid-design-system/src/lib/components/Button/Button.screenshots.tsx
packages/braid-design-system/src/lib/components/Button/Button.tsx
packages/braid-design-system/src/lib/components/ButtonLink/ButtonLink.screenshots.tsx

Ensuring the inner label element is full width to maintain backwards compatibility with previous block layout.

Button, ButtonLink: Ensure inner label is full width

---

.changeset/orange-kiwis-laugh.md
packages/braid-design-system/src/lib/components/Columns/Columns.tsx

Enables `Columns` content to occupy the available height of the parent container.

Columns: Ensure component occupies available height

---

.changeset/tidy-cooks-fly.md
.changeset/wise-guests-bow.md
packages/braid-design-system/src/lib/components/Accordion/Accordion.tsx
packages/braid-design-system/src/lib/components/Accordion/AccordionContext.ts
packages/braid-design-system/src/lib/components/Accordion/AccordionItem.tsx

Improve default spacing values and simplify internal layout.
This change reduces the default spacing within `Accordion` and `AccordionItem` components at certain sizes to improve its visual balance, ensuring the content is better associated with the correct `AccordionItem`.
Within the `Accordion` component, the default space between `AccordionItem` components has been reduced for size `large` with dividers, and sizes `small` and `xsmall` without dividers.
Within the `AccordionItem` component, the space between the `label` and content has been reduced for sizes `large` and `small`.

Accordion, AccordionItem: improve default space values

---

.changeset/wicked-dancers-end.md
packages/braid-design-system/src/lib/components/Badge/Badge.tsx
packages/braid-design-system/src/lib/components/Badge/defaultBadgeProps.tsx
packages/braid-design-system/src/lib/components/MenuItem/MenuItem.screenshots.tsx
packages/braid-design-system/src/lib/components/MenuItem/MenuItem.tsx
packages/braid-design-system/src/lib/components/MenuItem/MenuItemLink.tsx
packages/braid-design-system/src/lib/components/MenuItem/useMenuItem.css.ts
packages/braid-design-system/src/lib/components/MenuItem/useMenuItem.tsx
packages/braid-design-system/src/lib/components/MenuItemCheckbox/MenuItemCheckbox.screenshots.tsx
packages/braid-design-system/src/lib/components/MenuItemCheckbox/MenuItemCheckbox.tsx
packages/braid-design-system/src/lib/components/MenuItemDivider/MenuItemDivider.screenshots.tsx
packages/braid-design-system/src/lib/components/MenuItemDivider/MenuItemDivider.tsx
packages/braid-design-system/src/lib/components/MenuRenderer/MenuRenderer.css.ts
packages/braid-design-system/src/lib/components/MenuRenderer/MenuRenderer.docs.tsx
packages/braid-design-system/src/lib/components/MenuRenderer/MenuRenderer.gallery.tsx
packages/braid-design-system/src/lib/components/MenuRenderer/MenuRenderer.screenshots.tsx
packages/braid-design-system/src/lib/components/MenuRenderer/MenuRenderer.snippets.tsx
packages/braid-design-system/src/lib/components/MenuRenderer/MenuRenderer.tsx
packages/braid-design-system/src/lib/components/MenuRenderer/MenuRendererContext.ts
packages/braid-design-system/src/lib/components/MenuRenderer/MenuRendererTypes.ts
packages/braid-design-system/src/lib/components/OverflowMenu/OverflowMenu.docs.tsx
packages/braid-design-system/src/lib/components/OverflowMenu/OverflowMenu.screenshots.tsx
packages/braid-design-system/src/lib/components/OverflowMenu/OverflowMenu.snippets.tsx
packages/braid-design-system/src/lib/components/OverflowMenu/OverflowMenu.tsx
packages/braid-design-system/src/lib/playroom/snippets.ts
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Introduce a new `small` size for the `MenuRenderer` component.
This is available via the `size` prop, which supports the existing `standard` (default) and `small`.
```jsx
<MenuRenderer size="small" ... />
```
**NB**:
In small menus, `ScrollContainer` is causing some issues in non-production themes (docs, wireframe). This is due to their small value for `xsmall` padding, being too small to accommodate for the excess space created by the `virtualTouchable` box around each `MenuItem`. Potentially, the space scale of these themes could be revisited? I'm not sure another way around this problem.

MenuRenderer, OverflowMenu: add `small` size

---

packages/braid-design-system/src/lib/components/MenuItem/useMenuItem.tsx

Refactoring `Badge` `bleedY` treatment. We get `bleedY` for free in a `Text` component, so removing the default `Badge` props. Also removing some `flex` properties which seems to create no diff.

MenuRenderer: refactor Badge bleed

---

.changeset/big-toys-walk.md
packages/braid-design-system/src/lib/components/Accordion/AccordionItem.tsx

Issue caused due to bad refactor in #1674

AccordionItem: Fix issue parsing data props incorrectly

---

packages/braid-design-system/src/lib/components/Stepper/Stepper.docs.tsx

Just noticed the Contextual Design section never existed for this component, so removing the link to the heading. Also fix typo

docs: Remove broken link and fix typo on Stepper

---

.changeset/friendly-trains-explain.md
packages/braid-design-system/src/lib/components/MenuRenderer/MenuRenderer.screenshots.tsx
packages/braid-design-system/src/lib/components/MenuRenderer/MenuRenderer.tsx

This limit was mistakenly removed in https://github.com/seek-oss/braid-design-system/pull/1675
Added some screenshot tests to prevent the issue. In legacy themes, the max height of small and standard Menus is different due to the padding workaround, but this does not impact `seekJobs` theme

MenuRenderer, OverflowMenu: Ensure max height

---

.changeset/green-wasps-fail.md
packages/braid-design-system/src/lib/themes/makeRuntimeTokens.ts
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Extend the `webFonts` runtime token to include the `href` property containing the web font URL. This enables custom handling of web fonts beyond injecting the pre-constructed `link` tag(s).
```jsx
import seekJobs from 'braid-design-system/themes/seekJobs';
const webFontHrefs = seekJobs.webFonts.map(({ href }) => href);
// => [ "https://www.seek.com.au/static/shared-web/seeksans.css" ]
```

theme: Expose web fonts `href` on runtime tokens

---

package.json
packages/docs-ui/package.json
pnpm-lock.yaml

The removal of the default React export exposed a missing types dependency in dev for the `docs-ui` package. This was not picked up until the build on `master` due to a mistake in the workflow that only runs the `docs-ui` as part of the `prepare-publish` step.
The workflow fix is to run `build:braid` and `build:docs-ui` as part of the `validate` step to ensure we catch this earlier.

docs-ui: Fix build workflow

---

.github/workflows/clean-up-previews.yml
package.json

Pointing the clean up workflow at the real `gh-pages` branch, and setting to 7 day max age.
Leaving the trigger to be manual for the moment, but can set the cron cadence and max age as a follow up.
(Also removing unused `deploy` command pointing to a script that no longer exists)

ci: Update GitHub pages clean up workflow

---

.changeset/tidy-jars-arrive.md
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.playroom.tsx
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.test.tsx
packages/braid-design-system/src/lib/components/Checkbox/Checkbox.tsx
packages/braid-design-system/src/lib/components/Checkbox/CheckboxStandalone.playroom.tsx
packages/braid-design-system/src/lib/components/Dropdown/Dropdown.playroom.tsx
packages/braid-design-system/src/lib/components/Dropdown/Dropdown.test.tsx
packages/braid-design-system/src/lib/components/MonthPicker/MonthPicker.playroom.tsx
packages/braid-design-system/src/lib/components/MonthPicker/MonthPicker.test.tsx
packages/braid-design-system/src/lib/components/MonthPicker/MonthPicker.tsx
packages/braid-design-system/src/lib/components/PasswordField/PasswordField.playroom.tsx
packages/braid-design-system/src/lib/components/PasswordField/PasswordField.test.tsx
packages/braid-design-system/src/lib/components/PasswordField/PasswordField.tsx
packages/braid-design-system/src/lib/components/RadioGroup/RadioGroup.playroom.tsx
packages/braid-design-system/src/lib/components/RadioGroup/RadioGroup.test.tsx
packages/braid-design-system/src/lib/components/RadioGroup/RadioGroupContext.ts
packages/braid-design-system/src/lib/components/RadioGroup/RadioItem.tsx
packages/braid-design-system/src/lib/components/TextDropdown/TextDropdown.playroom.tsx
packages/braid-design-system/src/lib/components/TextDropdown/TextDropdown.test.tsx
packages/braid-design-system/src/lib/components/TextDropdown/TextDropdown.tsx
packages/braid-design-system/src/lib/components/TextField/TextField.playroom.tsx
packages/braid-design-system/src/lib/components/TextField/TextField.test.tsx
packages/braid-design-system/src/lib/components/private/Field/Field.tsx
packages/braid-design-system/src/lib/components/private/FieldGroup/FieldGroup.tsx
packages/braid-design-system/src/lib/components/private/InlineField/StyledInput.tsx
packages/braid-design-system/src/lib/components/private/validateTabIndex.ts
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Ensure the `tabIndex` prop is available on all form fields, enabling greater control over which elements appear in the keyboard navigation flow.
In line with [MDN guidance], the only supported values are `0` and `-1` to ensure best practice for keyboard navigation and assistive technologies.
```jsx
<TextField tabIndex={-1} />
```
[MDN guidance]: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex#:~:text=only%20use%200%20and%20%2D1%20as%20tabindex%20values

Add `tabIndex` to all form fields

---

.changeset/green-dots-warn.md
packages/braid-design-system/src/lib/components/Accordion/Accordion.tsx
packages/braid-design-system/src/lib/components/Accordion/AccordionItem.tsx

Ensure the `data` prop is correctly passed through to `Stack` internally, and validate `data-*` attributes are not being passed in incorrectly.
This was broken in part of the [v33 refactor].
[v33 refactor]: https://github.com/seek-oss/braid-design-system/pull/1602/files#diff-7f76bf257112052ee42c8d0cf0399f455ed33c7a3eca90b36040b6f8043ce226L85-L89

Accordion: Fix `data` prop parsing

---

site/playroom.config.mjs
site/project.json

- Change `playroom.config.js` into `mjs`.
- Add `"^dev"` as a dependency in `project.json` for the playroom commands.
Turning the playroom config into `mjs` is in preparation for an upcoming release of `sku` which is going to be esm only.

Update playroom config to mjs

---

.github/workflows/clean-up-previews.yml

Allow manual clean up in addition to schedule. Also reducing the window to 7 days.

ci: Reduce preview site history

---

site/src/App/Navigation/Navigation.css.ts
site/src/App/Navigation/Navigation.tsx

As part of the colour re-work the scroll shadow got out of sync with the background on the docs site. Realised we can adopt our `ScrollContainer` (still private i know) component and leverage the masking technique rather than try and guess the background colours.

site: Use ScrollContainer for side navigation

---

packages/braid-design-system/src/lib/components/TooltipRenderer/TooltipRenderer.docs.tsx

The current example shows text formatted with `weight="strong"`, which is the same as the default `Text` weight in `Tooltips` in the flagship themes.
Changing this to large `Text`, but could also use regular `Text` or another example

docs: Fix `TooltipRenderer` formatting example

---

packages/braid-design-system/src/lib/components/TextField/TextField.docs.tsx
packages/braid-design-system/src/lib/components/TextField/TextField.playroom.tsx
pnpm-lock.yaml

Edit: switched solution to option 1
Currently when not setting onClear on a TextField the Clear button (Cross on the right side) isn't visible in applications and the documentation site.
**Example: Documentation Site - No Clear Button**
However, it is visible in Playroom, due to Playroom's automatic injection of state handling.
**Example: Playroom - Clear Button**
This creates a discrepancy between what users see in docs examples and playrooms, and makes it impossible create playrooms where the Clear button is not visible.
Avoid passing onClear through to the TextField in Playroom when it's falsy.
To make it easy for prototyping to add the clear field behaviour allow passing `true` instead of a no-op function.
```jsx
<TextField
label="Label"
stateName="field1"
onClear={true}
/>
``` …

Fix Clear button always being visible in Playroom TextFields

---

.changeset/bitter-vans-pay.md
packages/braid-design-system/src/lib/components/private/Announcement/Announcement.tsx

Not sure of a nice screenshot test for this.
This change ensures `Annoucements` will not cause the document to grow in certain layouts using vh units

Autosuggest: Fix layout issue causing minor content overflow in certain scenarios

---

.changeset/rare-chairs-occur.md
packages/braid-design-system/src/lib/components/Table/Table.test.tsx
packages/braid-design-system/src/lib/components/Table/Table.tsx
packages/braid-design-system/src/lib/components/Table/TableBody.tsx
packages/braid-design-system/src/lib/components/Table/TableCell.tsx
packages/braid-design-system/src/lib/components/Table/TableFooter.tsx
packages/braid-design-system/src/lib/components/Table/TableHeader.tsx
packages/braid-design-system/src/lib/components/Table/TableRow.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

TODO
note: [`forwardRef` is deprecated](https://react.dev/blog/2024/12/05/react-19#ref-as-a-prop). We could migrate now or wait for the codemod?

Add `ref` to Table components

---

.changeset/cuddly-radios-remain.md
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.docs.tsx
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.gallery.tsx
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.playroom.tsx
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.tsx
packages/braid-design-system/src/lib/components/Disclosure/Disclosure.gallery.tsx
packages/braid-design-system/src/lib/components/TextDropdown/TextDropdown.docs.tsx
packages/braid-design-system/src/lib/components/TextDropdown/TextDropdown.gallery.tsx
packages/braid-design-system/src/lib/components/TextDropdown/TextDropdown.playroom.tsx
packages/braid-design-system/src/lib/components/TextDropdown/TextDropdown.tsx
packages/braid-design-system/src/lib/components/TextField/TextField.docs.tsx
packages/braid-design-system/src/lib/components/TextField/TextField.gallery.tsx
packages/braid-design-system/src/lib/components/TextField/TextField.playroom.tsx
packages/braid-design-system/src/lib/components/TextField/TextField.tsx
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

Grouping these three components together because their docs files use each other. Easier to remove all ids from these files at once.
Also - forgot to remove `ids` from `Disclosure.gallery.tsx` in #1743. Adding it here

Autosuggest, TextDropdown, TextField: Change `id` prop from required to optional

---

packages/braid-design-system/src/lib/components/Tag/Tag.playroom.tsx

`id` prop is already optional on `Tag`

Tag: Remove `useFallbackId` call for playroom

---

packages/braid-design-system/src/lib/components/OverflowMenu/OverflowMenu.playroom.tsx
packages/braid-design-system/src/lib/playroom/components.ts

`id` for `OverflowMenu` is already optional

OverflowMenu: Remove playroom wrapper component

---

packages/braid-design-system/src/lib/components/Textarea/Textarea.playroom.tsx

Textarea: Remove `useFallbackId` call for playroom

---

packages/braid-design-system/src/lib/components/Accordion/AccordionItem.test.tsx
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.snippets.tsx
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.test.tsx
packages/braid-design-system/src/lib/components/Checkbox/Checkbox.test.tsx
packages/braid-design-system/src/lib/components/Checkbox/Checkbox.tsx
packages/braid-design-system/src/lib/components/Checkbox/CheckboxStandalone.test.tsx
packages/braid-design-system/src/lib/components/Checkbox/CheckboxStandalone.tsx
packages/braid-design-system/src/lib/components/Dialog/Dialog.gallery.tsx
packages/braid-design-system/src/lib/components/Disclosure/Disclosure.test.tsx
packages/braid-design-system/src/lib/components/Drawer/Drawer.gallery.tsx
packages/braid-design-system/src/lib/components/Dropdown/Dropdown.test.tsx
packages/braid-design-system/src/lib/components/FieldLabel/FieldLabel.gallery.tsx
packages/braid-design-system/src/lib/components/FieldMessage/FieldMessage.gallery.tsx
packages/braid-design-system/src/lib/components/FieldMessage/FieldMessage.playroom.tsx
packages/braid-design-system/src/lib/components/MenuRenderer/MenuRenderer.docs.tsx
packages/braid-design-system/src/lib/components/OverflowMenu/OverflowMenu.docs.tsx
packages/braid-design-system/src/lib/components/PasswordField/PasswordField.test.tsx
packages/braid-design-system/src/lib/components/RadioGroup/RadioGroup.tsx
packages/braid-design-system/src/lib/components/RadioGroup/RadioGroupContext.ts
packages/braid-design-system/src/lib/components/RadioGroup/RadioItem.tsx
packages/braid-design-system/src/lib/components/Table/Table.gallery.tsx
packages/braid-design-system/src/lib/components/Table/Table.snippets.tsx
packages/braid-design-system/src/lib/components/Tag/Tag.docs.tsx
packages/braid-design-system/src/lib/components/TextDropdown/TextDropdown.test.tsx
packages/braid-design-system/src/lib/components/TextField/TextField.test.tsx
packages/braid-design-system/src/lib/components/TextField/TextField.tsx
packages/braid-design-system/src/lib/components/Textarea/Textarea.test.tsx
packages/braid-design-system/src/lib/components/private/InlineField/InlineField.tsx
packages/braid-design-system/src/lib/components/private/InlineField/StyledInput.tsx
packages/braid-design-system/src/lib/components/private/Modal/modalTestSuite.tsx

Some `id`s were missed in #1767. This change:
* Removes remaining `id` usage in `Example`
* Removes `id` in tests except where necessary
* Removes some missed `id` uses in snippets, Gallery and docs
* Removes `id` on `ButtonIcon` wrapper elements which are no longer necessary
* Updates `FieldMessage.playroom.tsx` to `useFallbackId`
* Change `id` prop from required to optional on `InlineField`

Remove all remaining `id` usage

---

.changeset/fuzzy-snakes-enjoy.md
packages/braid-design-system/src/lib/components/MenuItem/useMenuItem.tsx

On iOS, `MenuItemLink` would require one tap to activate the hover style, and a secondary tap to trigger `href` and `onClick` - [Problem Demo](https://seek-oss.github.io/braid-design-system/playroom/#?code=N4Igxg9gJgpiBcJgGcYBcAiMBmBDArgDZoDKauaMAFADohoQDmjhMdANAAR6GoCUAXxoA7EQB4AQhAAenAA64oUAJbDGAXjqFcAJ0ZsQAPhGdOYknJ0xFnZArAxNIbXoPHhp02ICyMYfgAlP1grHRNPUwhsbFRSe0c6ZABbXEJCOnCItB1lZhgddWAqbNz9HQAFHQg5ZC5gTmq-TgE%2BTnVDTloPCM9JGU58VB0SGFYwNCdhCGEDTjB8HWQIAro5CFVKMJBOYAA6fZK8iqqagXcenrEAFRhpNHOLnt9-YDpOOiFux96ASUhhADCAAsYAA3KqiL7fTwqKzjZTTQqNDwAfneIHwcje8HRUAgAHdRCBPtCeqlcsIAJpOQgE-JgXCoDJQ74Aege3zErJudw5l1ZUmkfNMgkynGFZme%2BB%2BlCSABlVABrMURIFWbBOIFoNA1eCs1n4w27RgQJisXaQJKs5nfaYAwjKMCKwpUVrtTgMZisMgUah0T0sAyilnilWeBXCZUhrlSmUweVKvkxvyBYL5fLuMXAfSkciUWj0JiBuitNFdC7XW5oWzKABeCWcun0b3xMFyWqcy …

MenuItem, MenuItemCheckbox, MenuItemLink: Fix iOS double tap trigger bug

---

.changeset/nasty-rooms-stay.md
packages/braid-design-system/src/lib/components/Accordion/AccordionItem.tsx
packages/braid-design-system/src/lib/components/Button/Button.tsx
packages/braid-design-system/src/lib/components/MenuItem/useMenuItem.tsx
packages/braid-design-system/src/lib/components/Tabs/Tab.tsx
packages/braid-design-system/src/lib/components/TextLink/TextLink.tsx
packages/braid-design-system/src/lib/components/TextLinkButton/TextLinkButton.tsx
packages/braid-design-system/src/lib/components/private/InlineField/InlineField.tsx
packages/braid-design-system/src/lib/components/private/Typography/Typography.tsx
packages/braid-design-system/src/lib/components/useToast/ToastTypes.ts

As a consumer, I found it surprising I couldn't do `<Checkbox badge={something ? <Badge ... /> : null}`; only undefined was accepted. Typically react node props accept `ReactNode` which has `null` built-in, but the strongly-typed arguments like this don't.

Support null in some more places

---

packages/braid-design-system/src/lib/components/Columns/Columns.snippets.tsx

Renaming this snippet, so when I search 'table' , the `Table` component is the first result
'Responsive columns' fits with the convention of other responsive snippets, so seems appropriate
Noticing there might be an optimisation for sorting results in Playroom, but will address that separately

snippets: Ensure 'table' is only used in `Table` snippets

---

jest/setupTests.ts
packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.tsx
packages/braid-design-system/src/lib/components/ButtonIcon/ButtonIcon.test.tsx
packages/braid-design-system/src/lib/components/ButtonIcon/ButtonIcon.tsx
packages/braid-design-system/src/lib/components/MenuRenderer/MenuRenderer.screenshots.tsx
packages/braid-design-system/src/lib/components/MenuRenderer/MenuRenderer.tsx
packages/braid-design-system/src/lib/components/TooltipRenderer/TooltipRenderer.css.ts
packages/braid-design-system/src/lib/components/TooltipRenderer/TooltipRenderer.docs.tsx
packages/braid-design-system/src/lib/components/TooltipRenderer/TooltipRenderer.screenshots.tsx
packages/braid-design-system/src/lib/components/TooltipRenderer/TooltipRenderer.tsx
packages/braid-design-system/src/lib/components/private/Popover/Popover.css.ts
packages/braid-design-system/src/lib/components/private/Popover/Popover.screenshots.tsx
packages/braid-design-system/src/lib/components/private/Popover/Popover.tsx
packages/braid-design-system/src/lib/components/private/animationTimeout.ts

NB: This change results in a slight change to the `OverflowMenu` menu positioning due to current implementation of `Popover` API. It is now positioned based on the `OverflowMenu` `ButtonIcon` (not its bounding box with negative margins), in line with standard use of `MenuRenderer` and `ButtonIcon`.

Popover: Add private component

---

site/playroom.config.mjs

Still seeing too much of this and it hurts my soul

Playroom: remove `apac` from default visible themes

---

.changeset/two-parts-rhyme.md
packages/braid-design-system/src/lib/components/useToast/Toast.tsx
packages/braid-design-system/src/lib/components/useToast/ToastTypes.ts
packages/braid-design-system/src/lib/components/useToast/useToast.docs.tsx
packages/braid-design-system/src/lib/playroom/useScope.ts

The `useToast` page would sometimes crash when switching between it and another component page on the docs site.
Looks like the problem is calling hooks within examples in the docs page. When you switch pages, React complains that `DocExample` is calling a different set of hooks (in this case also calling `useId`).
```
hook.js:608 
Warning: React has detected a change in the order of Hooks called by DocExample.
This will lead to bugs and errors if not fixed.
For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks
Previous render            Next render
------------------------------------------------------
1. useContext                 useContext
2. useContext                 useContext
3. useContext                 useContext
4. useCallback …
```

docs: Fix site crashing when switching in and out of the `useToast` page

---

.changeset/grumpy-seas-clean.md
packages/braid-design-system/src/entries/css/atoms.docs.tsx
packages/braid-design-system/src/lib/components/Box/Box.docs.tsx
packages/braid-design-system/src/lib/css/atoms/atomicProperties.ts
packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap

I'd like to add `sticky` because:
1. It is [supported](https://developer.mozilla.org/en-US/docs/Web/CSS/position#browser_compatibility) under our browser policy
2. It plays nicely with our new layout components ([example](https://seek-oss.github.io/braid-design-system/playroom/#?code=N4Igxg9gJgpiBcIA8AhCAPABABwIZSgEsA7AcwF4AdEUgVwBd6YAnagPkuM0yQGV7cYANaYAznjAwqIUQFtcAGwXtO3bkgDCuZlA5c16-oJHjBU6gu2kYK-QfUAJGPhKlMCmADcYC6QBZ2JxcyJAB6IKIyPXs1JAAVGHR6NgSksNTk1Xswo2Fo2NCtHXz1NHQsg1F6AE8PcmBgHAhRQnpCCGJ4TGoqwmFq6kwAXyGKtXoIbHqABlG7NQAvAEliWHR6gEY5mIAjCB0WACUXWlFpS2ZrajHuPfReAAt8CAB3aT2D5hRmXFWAQTAkmI9Gu81uxlIzAgtFW0lEtGYADMzKCYngCK5pHRGCxUWoSrFciYJOYQBcriACQYkBFXO4vD5-Ox%2BH0hNVMGBtFAwrSojdYhkUol6OlhVSeKEiQSwmVpUVdPy%2BAJhGISecrDZKfzHM5Im4PN5fNQApTeaQebrXOL1IKMqKkuKcsqhNLCly2MBBtRtrF5Y6iaqzOrLpr …

Box, atoms: Add `sticky` position

---

site/src/App/DocNavigation/DocNavigation.css.ts
site/src/App/DocNavigation/DocNavigation.tsx

Did this as part of debugging but feel like it's worth keeping. Splitting out for ease of PR review, but it should have no functional impact.
1. This component requires a unique layout solution, so I think the code should be a bit more explicit for ease of reading (i.e. comments)
2. Tried to consolidate some `Box` components

docs: Simplify `DocNavigation` component

---

.changeset/itchy-boats-wonder.md
packages/braid-design-system/src/lib/components/TooltipRenderer/TooltipRenderer.tsx

Optimise performance by only calculating trigger position when tooltip is open and when the window is resized, instead of on every render
Noticed this when testing #1782

TooltipRenderer: Optimise performance

---

.changeset/brown-pillows-pull.md
packages/braid-design-system/src/lib/components/RadioGroup/RadioGroup.test.tsx
packages/braid-design-system/src/lib/components/RadioGroup/RadioGroup.tsx

Fixes a bug where the provided `id` was not being passed through to the `fieldset` element.

RadioGroup: Ensure `id` is assigned to `fieldset`

---

.github/workflows/chromatic.yml
.github/workflows/validate.yml

So we can choose when to run chromatic screenshot tests. Incidentally, this means the `validate` workflow can now do a shallow clone, speeding up that workflow by almost 3 minutes.
Currently the chromatic CI check is mandatory for merging. If you don't want to run chromatic, but do want to merge a PR, that check either needs to be temporarily disabled, or the merge must be performed with admin override (probably the better option for the time being).
Note that the manual workflow isn't available in [the Actions tab](https://github.com/seek-oss/braid-design-system/actions) yet as I believe that only reflects the state of `master`.

Isolate `chromatic` to a manual CI workflow

---

.changeset/shiny-states-listen.md
packages/docs-ui/project.json

`validate` scripts for `braid-design-system` and `docs-ui` are run during [`postbuild`](https://github.com/seek-oss/braid-design-system/blob/f6363acac318fb9a69c38328be2d061b3a4b6bdb/package.json#L16). `validate:dist` for `docs-ui` had a dependency on its `dev` script, which results in `crackle dev` being run right before publishing, causing published artifacts to contain dev-time code that fails to resolve.
The following versions were affected by this bug:
- [`3.0.1`](www.npmjs.com/package/@braid-design-system/docs-ui/v/3.0.1)
- [`3.0.2`](www.npmjs.com/package/@braid-design-system/docs-ui/v/3.0.2)
- [`3.0.3`](www.npmjs.com/package/@braid-design-system/docs-ui/v/3.0.3)
- [`3.0.4`](www.npmjs.com/package/@braid-design-system/docs-ui/v/3.0.4)
This dependency was added in …

`docs-ui`: Don't run `dev` script before `validate:dist`
