- README.md
- lib/stories/all.stories.js
- package.json
Thanks to the fact that sku includes Storybook out of the box, this is an amazingly small PR 🎉
> chore(storybook): Add initial Storybook

- package.json
- yarn.lock
Adopt new `husky` hooks api and setup `lint-staged`
> chore(deps): Update hooks and commit flow

- package.json
- yarn.lock
This update allows you to resize the code pane and detach it from the main window.
> chore(deps): Update Playroom to v0.3.0

- .eslintrc
Adding eslint config to the project to support editor feedback. Ultimately will be promoting this to be a controlled config in sku, but for now we'll simply add this in.
> style(eslint): Add config to support editors

- .pullapprove.yml
We have turned off the service, just cleaning up by removing the config file
> chore(pullapprove): Remove config file

- docs/src/App/Home/Home.tsx
- lib/components/Actions/Actions.docs.tsx
- lib/components/Button/Button.docs.tsx
- lib/components/Button/Button.tsx
Map the click handler through to the button element 🤦‍♂️
> fix(Button): Map click handler through

- yarn.lock
Playroom is currently broken. This fixes it.
> chore: Perform lock file maintenance

- lib/themes/seekAsia/tokens.ts
Adjustments to SEEK Asia styles based on feedback from Joanne from reviewing the JobAlert work.
- Touchable height reduced from 11 rows to 10
- Large text size for desktop reverted to mobile size
> fix(SeekAsia): Decrease touchable height and large text size

- lib/components/FieldMessage/FieldMessage.tsx
Fixes the inconsistent hook execution error when a field message appears dynamically based on the nested and conditional execution of the `useStyles` hook.
> fix(FieldMessage): Refactor icon to fix inconsistent hook usage error

- lib/components/TextLinkRenderer/TextLinkRenderer.tsx
Lifting the weight of text links to improve accessibility.
> fix(TextLink): Increase text weight to medium

- lib/components/private/FieldOverlay/FieldOverlay.tsx
- lib/components/private/InlineField/InlineField.treat.ts
- lib/components/private/InlineField/InlineField.tsx
- lib/components/private/Overlay/Overlay.tsx
Addressed a couple of user experience issues with `Radio` & `Checkbox` components. 
- Increased the hit area, previously too small and was not continuous between the field and its label,
- Improved hover affordance,
- Added selection animation to give them some life
Check it out in [playroom](https://braid-design-system--395218595b4fded18556d828e151bba04932df39.surge.sh/playroom/#?code=PENhcmQ-CiAgPENoZWNrYm94CiAgICBpZD0iMSIKICAgIGxhYmVsPSJPbmUiCiAgICByZXNlcnZlTWVzc2FnZVNwYWNlPXtmYWxzZX0KICAvPgogIDxDaGVja2JveAogICAgaWQ9IjIiCiAgICBsYWJlbD0iVHdvIgogICAgdG9uZT0iY3JpdGljYWwiCiAgICByZXNlcnZlTWVzc2FnZVNwYWNlPXtmYWxzZX0KICAvPgogIDxDaGVja2JveAogICAgaWQ9IjMiCiAgICBsYWJlbD0iVGhyZWUiCiAgICBjaGVja2VkPXt0cnVlfQogICAgcmVzZXJ2ZU1lc3NhZ2VTcGFjZT17ZmFsc2V9CiAgLz4KICA8Q2hlY2tib3gKICAgIGlkPSI0IgogICAgbGFiZWw …
> fix: Improve Radio & Checkbox UX

- docs/Style Guide Migration.md
- docs/Todo List.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/Toggle/Toggle.docs.tsx
- lib/components/Toggle/Toggle.migration.md
- lib/components/Toggle/Toggle.treat.ts
- lib/components/Toggle/Toggle.tsx
- lib/components/index.ts
- lib/components/private/InlineField/InlineField.treat.ts
- lib/components/private/InlineField/getSize.ts
Preview in [Playroom](https://braid-design-system--df5643aa711b13c747954543addd69cd67c0004d.surge.sh/playroom/#?code=PENhcmQ-CiAgPFRvZ2dsZSBsYWJlbD0iT2ZmIiAvPgogIDxUb2dnbGUgbGFiZWw9Ik9uIiBvbj17dHJ1ZX0gLz4KICA8VG9nZ2xlIGxhYmVsPSJBbGlnbiByaWdodCIgb249e3RydWV9IGFsaWduPSJyaWdodCIgLz4KPC9DYXJkPgo)
> feat(Toggle): Add component

- docs/Style Guide Migration.md
- docs/Todo List.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/Badge/Badge.docs.tsx
- lib/components/Badge/Badge.migration.md
- lib/components/Badge/Badge.treat.ts
- lib/components/Badge/Badge.tsx
- lib/components/index.ts
- lib/hooks/typography/typography.treat.ts
- lib/hooks/useBox/box.treat.ts
- lib/themes/jobStreetClassic/tokens.ts
- lib/themes/makeTreatTheme.ts
- lib/themes/seekAnz/tokens.ts
- lib/themes/seekAsia/makeTokens.ts
- lib/themes/wireframe/tokens.ts
- lib/utils/a11y/index.ts
First pass at a minimal suite for `Badge`. Leveraging the design and visual language we currently have for the `Alert` components. This required tweaking the algorithm for calculating the light variants of the available `tone`s, so needed to take a holistic view of both these components to strike the right balance.
```jsx
<Badge
tone={ 'info' | 'positive' | 'critical' | 'secondary' }
weight={ 'regular' | 'strong' }>
Featured
</Badge>
```
Preview in [Playroom](https://braid-design-system--f19540faa89eb411477ebb87e6e9bd8bf5d46183.surge.sh/playroom/#?code=PEJveAogIHBhZGRpbmdUb3A9InhzbWFsbCIKICBwYWRkaW5nTGVmdD0ieHNtYWxsIgogIHBhZGRpbmdSaWdodD0ieHNtYWxsIgogIGJhY2tncm91bmQ9InNlY29uZGFyeUxpZ2h0IgogIHN0eWxlPXt7IGhlaWdodDogIjEwMHZoIiB9fQo-CiAgPENhcmQ-CiAgICA8SGVhZGluZyBsZXZlbD0iMyI-QmFkZ2VzPC9IZWFka …
> feat(Badge): Add component

- README.md
- lib/components/BraidProvider/BraidProvider.docs.tsx
Updating some theme paths in the docs/readme that were reaching into `lib`
> docs: Update theme import path

- lib/themes/treatTheme.d.ts
This is in preparation for moving the treat global theme type to an interface.
> fix: Update Theme type to be an interface

- lib/themes/baseTokens/seekAsia.ts
- lib/themes/baseTokens/seekAsiaRebrand.ts
Spotted ambiguous disabled radio states for several themes
> fix(Radio): Fix disabled styles for seekAsia & seekAsiaRebrand

- lib/themes/baseTokens/seekAsiaRebrand.ts
Align `seekAsiaRebrand` color palette with the given specification below:
> fix(seekAsiaRebrand): Update colour palette

- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/Autosuggest/Autosuggest.docs.tsx
- lib/components/Autosuggest/Autosuggest.treat.ts
- lib/components/Autosuggest/Autosuggest.tsx
- lib/components/Dropdown/Dropdown.docs.tsx
- lib/components/Dropdown/Dropdown.tsx
- lib/components/MonthPicker/MonthPicker.tsx
- lib/components/TextField/TextField.docs.tsx
- lib/components/TextField/TextField.tsx
- lib/components/Textarea/Textarea.tsx
- lib/components/private/Field/Field.treat.ts
- lib/components/private/Field/Field.tsx
Add support for decorating `TextField`, `Dropdown`, & `Autosuggest` with icons:
[Preview in Playroom &#08594;](https://braid-design-system--99320240c7a7fff3eecbb5d09e28ef9145cf33a7.surge.sh/playroom/#?code=PEJveCBwYWRkaW5nWD0ic21hbGwiIHBhZGRpbmdZPSJ4eGxhcmdlIiBiYWNrZ3JvdW5kPSJicmFuZCI-CiAgPFN0YWNrIHNwYWNlPSJsYXJnZSI-CiAgICA8SGVhZGluZyBsZXZlbD0iMSI-U2VhcmNoIGZvciBqb2JzPC9IZWFkaW5nPgogICAgPENvbHVtbnMgY29sbGFwc2Ugc3BhY2U9e1sibWVkaXVtIiwgInhzbWFsbCJdfT4KICAgICAgPENvbHVtbj4KICAgICAgICA8VGV4dEZpZWxkCiAgICAgICAgICBpZD0iaWQiCiAgICAgICAgICBpY29uPXs8SWNvblNlYXJjaCAvPn0KICAgICAgICAgIG9uQ2xlYXI9eygpID0-IHt9fQogICAgICAgICAgcGxhY2Vob2xkZXI9IlJvbGUgb3IgdGl0bGUiCiAgICAgICAgICByZXNlcnZlTWVzc2FnZVNwYWNlPXtmYWxzZX0KICAgICAgICAgIGF1dG9Db21wbGV0ZT0ib2ZmIgogICAgICAgIC8-CiAgICAgIDwvQ29sdW1uPgogICAgICA8Q29sdW1uPg …
> feat: Add support for icons to TextField, Dropdown & Autosuggest

- lib/components/private/InlineField/InlineField.tsx
> fix(Checkbox): Fix checkbox tick in IE11

- lib/components/Box/BackgroundContext.tsx
- lib/components/ButtonRenderer/ButtonRenderer.treat.ts
- lib/components/ButtonRenderer/ButtonRenderer.tsx
- lib/components/private/Field/Field.tsx
> fix(Button): Increase weak hover contrast on dark backgrounds

- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/BackgroundProvider/BackgroundProvider.docs.tsx
- lib/components/BackgroundProvider/BackgroundProvider.tsx
- lib/components/Box/BackgroundContext.tsx
- lib/components/Loader/Loader.tsx
- lib/components/index.ts
- lib/hooks/typography/typography.treat.ts
Also, fixes the `Loader` component style on some backgrounds.
> feat: Add BackgroundProvider for handling custom background colors

- lib/themes/jobsDb/tokens.ts
DB formAccent supposed to use link colour for checkbox/button background
> fix(jobsDB): Update formAccent colour

- generate-component-docs/__snapshots__/contract.test.ts.snap
- generate-component-docs/generate.ts
- site/src/App/Documentation/ComponentProps.tsx
- site/src/App/Documentation/ComponentRoute.tsx
- site/src/App/Documentation/Documentation.tsx
- site/src/types.d.ts
- site/src/undocumentedExports.json
- sku.routes.js
- (Very basic) support for hooks in contract tests
- Create single point of truth for undocumented exports
- Handle multiple exports from single file
- Support descriptions in doc pages
> docs: Clean up docs

- .changeset/rotten-plants-search.md
- lib/reset/reset.treat.ts
> fix(Reset): Hide search cancel button from input

- .changeset/khaki-ligers-mix.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/Autosuggest/Autosuggest.test.tsx
- lib/components/BraidTestProvider/BraidTestProvider.docs.tsx
- lib/components/BraidTestProvider/BraidTestProvider.tsx
- lib/components/MenuRenderer/testHelper.tsx
- lib/components/Stack/Stack.test.tsx
- lib/components/index.ts
- lib/components/useToast/useToast.test.tsx
> Add BraidTestProvider component

- .changeset/many-penguins-share.md
- .github/workflows/release.yml
See my [changesets fork](https://github.com/changesets/action/compare/master...mattsjones:configurable-user?expand=1) for details on the change.
> Use seek-oss-ci user for changeset action commits

- .changeset/five-peas-promise.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/Inline/Inline.docs.tsx
- lib/components/Inline/Inline.tsx
Add support for vertical alignment via the `alignY` prop. Supports responsive space values.
> Inline: Support vertical alignment

- .changeset/friendly-suns-chew.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/Divider/Divider.docs.tsx
- lib/components/Divider/Divider.treat.ts
- lib/components/Divider/Divider.tsx
- lib/components/Stack/Stack.docs.tsx
- lib/components/Stack/Stack.tsx
- lib/components/Tiles/Tiles.docs.tsx
- lib/components/Tiles/Tiles.tsx
> Divider: Add strong weight variant

- .changeset/pink-jokes-talk.md
- lib/components/Dropdown/Dropdown.tsx
- lib/components/MonthPicker/MonthPicker.test.tsx
- lib/components/MonthPicker/MonthPicker.tsx
- lib/components/private/buildDataAttributes.ts
Other PR tweaks
- Add some tests for MonthPicker
- Remove Dropdown child validation
> Remove lodash from MonthPicker and buildDataAttributes

- .changeset/eleven-cameras-impress.md
- .changeset/mighty-kangaroos-press.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/Actions/Actions.tsx
- lib/components/Column/Column.tsx
- lib/components/Columns/Columns.docs.tsx
- lib/components/Columns/Columns.tsx
- lib/components/Inline/Inline.docs.tsx
- lib/components/Inline/Inline.tsx
- lib/utils/collapsibleAlignmentProps.ts
- site/src/App/routes/foundations/layout/layout.tsx
> Add 'collapseBelow' and 'reverse' to Inline, 'align' to Columns

- .changeset/shiny-sloths-clean.md
- lib/components/Autosuggest/Autosuggest.test.tsx
- lib/components/Autosuggest/Autosuggest.tsx
> Autosuggest: Prevent automatic selection if input hasn't changed

- .changeset/pretty-seahorses-scream.md
- lib/components/AccordionItem/AccordionItem.test.tsx
- lib/components/AccordionItem/AccordionItem.tsx
> AccordionItem: Support 'onToggle' prop without 'expanded'

- .prettierignore
This is a generated file, so Prettier should ignore it.
> Add CHANGELOG.md to .prettierignore

- .changeset/calm-dragons-roll.md
- lib/components/Autosuggest/Autosuggest.docs.tsx
- lib/components/Autosuggest/Autosuggest.test.tsx
- lib/components/Autosuggest/Autosuggest.tsx
- lib/components/Autosuggest/createAccessbilityProps.ts
> Autosuggest: Support suggestion descriptions

- lib/components/Autosuggest/Autosuggest.migration.md
- lib/components/Autosuggest/Autosuggest.tsx
- lib/components/Dropdown/Dropdown.treat.ts
- lib/components/Dropdown/Dropdown.tsx
- lib/components/MonthPicker/MonthPicker.tsx
- lib/components/TextField/TextField.tsx
- lib/components/Textarea/Textarea.tsx
- lib/components/private/Field/ClearField.treat.ts
- lib/components/private/Field/ClearField.tsx
- lib/components/private/Field/Field.treat.ts
- lib/components/private/Field/Field.tsx
Refactor the internal `Field` to standardise the handling and formatting of field buttons containers.
> Standardise internal field icons

- .changeset/funny-foxes-tell.md
- lib/components/MonthPicker/MonthPicker.tsx
> MonthPicker: Fix internal <Hidden screen> deprecation warning

- .changeset/good-wolves-listen.md
- lib/components/Alert/Alert.docs.tsx
- lib/components/Alert/Alert.migration.md
- lib/components/Alert/Alert.tsx
- lib/components/Notice/Notice.docs.tsx
- lib/components/Notice/Notice.tsx
- lib/components/private/DefaultTextToneContext.ts
- lib/hooks/typography/index.ts
- lib/hooks/useTextAlignedToIcon/useTextAlignedToIcon.treat.ts
- lib/hooks/useTextAlignedToIcon/useTextAlignedToIcon.ts
> Alert, Notice: Support rich content

- .changeset/sweet-teachers-applaud.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/Inline/Inline.test.tsx
- lib/components/Inline/Inline.tsx
- lib/components/Stack/Stack.tsx
Also, updated the Stack error message to be more detailed.
> Inline: Add semantic list support

- .changeset/rude-lizards-promise.md
- lib/components/Autosuggest/Autosuggest.tsx
> Autosuggest: Fix suggestion double tap bug on iOS

- .changeset/eight-seas-add.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/MonthPicker/MonthPicker.docs.tsx
- lib/components/MonthPicker/MonthPicker.tsx
> MonthPicker: Support custom month and year labels

- .changeset/twelve-beds-float.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/Accordion/Accordion.docs.tsx
- lib/components/Actions/Actions.docs.tsx
- lib/components/Button/Button.docs.tsx
- lib/components/ButtonLink/ButtonLink.docs.tsx
- lib/components/ButtonRenderer/ButtonRenderer.docs.tsx
- lib/components/Link/Link.docs.tsx
- lib/components/MenuRenderer/MenuRenderer.docs.tsx
- lib/components/TextLink/TextLink.docs.tsx
- lib/components/TextLinkButton/TextLinkButton.docs.tsx
- lib/components/TextLinkButton/TextLinkButton.test.tsx
- lib/components/TextLinkButton/TextLinkButton.tsx
- lib/components/TextLinkRenderer/TextLinkRenderer.docs.tsx
- lib/components/TextLinkRenderer/TextLinkRenderer.tsx
- lib/components/index.ts
> Add TextLinkButton component

- .changeset/late-tables-smoke.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/TextLinkButton/TextLinkButton.test.tsx
- lib/components/TextLinkButton/TextLinkButton.tsx
> TextLinkButton: Pass click event object to onClick handler

- lib/components/BraidProvider/BraidProvider.tsx
> Fix test environment detection

- .changeset/forty-eyes-lick.md
- .changeset/wise-snails-mix.md
- lib/components/TextLinkRenderer/TextLinkRenderer.tsx
Also fixed the formatting of another changeset for consistency.
> TextLink: Default weight prop to regular inside secondary text

- .changeset/shiny-jars-suffer.md
- lib/themes/seekBusiness/tokens.ts
This PR is following a review of the snapshots from the UI tests.
> Change SEEK Business formAccent token to match Seek ANZ

- .changeset/violet-boxes-talk.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/ContentBlock/ContentBlock.docs.tsx
- lib/components/useToast/Toast.treat.ts
- lib/components/useToast/Toast.tsx
- lib/themes/baseTokens/apac.ts
- lib/themes/baseTokens/seekAsia.ts
- lib/themes/catho/tokens.ts
- lib/themes/docs/tokens.ts
- lib/themes/makeBraidTheme.ts
- lib/themes/occ/tokens.ts
- lib/themes/seekAnz/tokens.ts
- lib/themes/seekUnifiedBeta/tokens.ts
- lib/themes/wireframe/tokens.ts
**ContentBlock:** Add support for xsmall & small widths
**EXAMPLE USAGE**
```jsx
<ContentBlock width="small">
...
</ContentBlock>
```
> ContentBlock: Add support for xsmall & small widths

- .changeset/clever-stingrays-compete.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/Badge/Badge.docs.tsx
- lib/components/Badge/Badge.treat.ts
- lib/components/Badge/Badge.tsx
- lib/components/Tabs/Tab.tsx
- site/src/App/ComponentDoc/ComponentDoc.treat.ts
- site/src/App/ComponentDoc/ComponentDoc.tsx
- site/src/App/ComponentDoc/Navigation/Navigation.tsx
- site/src/App/SubNavigation/SubNavigation.treat.ts
- site/src/App/SubNavigation/SubNavigation.tsx
I've also refactored `Tabs` and the documentation site to make use of this new feature where we'd previously applied workarounds.
> Badge: Add 'bleedY' prop

- .changeset/modern-spies-grin.md
- lib/components/List/List.docs.tsx
- lib/components/List/List.tsx
> List, BulletList: Ensure list items are full width

- site/src/App/Navigation/Navigation.treat.ts
- site/src/App/Navigation/Navigation.tsx
Improving the use of space around the content and side nav, particularly on tablet.
Fixes https://github.com/seek-oss/braid-design-system/issues/750
> Improve docs site gutters

- lib/themes/makeBraidTheme.ts
- site/src/App/ComponentDoc/ComponentDoc.tsx
- site/src/App/Navigation/Navigation.tsx
- site/src/App/Seo/AppMeta.tsx
- site/src/App/routes/examples/basic-form/basic-form.tsx
- site/src/App/routes/examples/job-summary/job-summary.tsx
- site/src/App/routes/examples/marketing-banner/marketing-banner.tsx
- site/src/App/routes/foundations/iconography/iconography.tsx
- site/src/App/routes/foundations/layout/layout.tsx
- site/src/App/routes/foundations/tones/tones.tsx
- site/src/App/routes/guides/contribution.tsx
- site/src/App/routes/guides/design-workflow.tsx
- site/src/App/routes/guides/development-workflow.tsx
- site/src/App/routes/guides/testing-guide.tsx
- site/src/App/routes/home/index.tsx
Improved site semantics, ensuring every page has the correct `h1`, and addressed some validator issues:
- Unique titles
- Encoding web font query string params
- Visually hidden text for Braid logo
- Added meta description
> Docs site: Improved document semantics and page titles

- .changeset/lovely-socks-appear.md
- lib/components/MenuItemDivider/MenuItemDivider.tsx
- lib/components/MenuRenderer/MenuRenderer.tsx
- lib/components/MenuRenderer/MenuRendererContext.ts
> MenuRenderer, OverflowMenu: Fix circular dependency issue

- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/TextDropdown/TextDropdown.tsx
- site/src/App/routes/gallery/Gallery.tsx
- site/src/App/routes/gallery/GalleryPanel.tsx
- site/src/App/routes/gallery/gallery.treat.ts
- site/src/App/routes/gallery/index.tsx
Introduces a couple of key new features to Gallery:
&nbsp; 🏀  &nbsp;&nbsp; Adds jump to component feature
&nbsp; ⌨️ &nbsp;&nbsp; Support zooming with keyboard using cmd +/-
&nbsp; :100:  &nbsp;&nbsp; Support zooming to actual size by clicking the current zoom
> Add jump feature to Gallery

- .changeset/light-tables-repeat.md
- lib/components/ButtonRenderer/ButtonRenderer.treat.ts
- lib/components/ButtonRenderer/ButtonRenderer.tsx
- lib/components/Loader/Loader.treat.ts
**Loader,Button:** Performance improvement for loading animations
Adjust animations properties and values to reduce CPU recalculation overheads.
> Loader, Button: Improve performance of loading animations

- .changeset/hungry-spies-warn.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/List/List.docs.tsx
- lib/components/List/List.tsx
> List: Add support for Roman numerals

- .changeset/ten-dragons-whisper.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/Autosuggest/Autosuggest.test.tsx
- lib/components/Autosuggest/Autosuggest.tsx
> Autosuggest: Add 'hideSuggestionsOnSelection' prop

- .prettierignore
- scripts/versionComponentUpdates.ts
- site/src/componentUpdates.json
This will make reviewing JSON updates in PRs a bit easier. Also adding it to `.prettierignore` so you can manually edit the file without reformatting everything.
> Pretty print component updates JSON file

- lib/components/Dialog/Dialog.docs.tsx
- lib/components/Drawer/Drawer.docs.tsx
- lib/playroom/playroomState.tsx
- lib/stories/all.stories.tsx
- lib/utils/useSourceFromExample.ts
- site/src/App/Code/Code.tsx
- site/src/App/ComponentDoc/ComponentDoc.tsx
- site/src/App/routes/gallery/Gallery.tsx
- site/src/types.d.ts
This is ultimately so that we can write type-safe stateful examples on the site using our new Playroom state API 🙌
> Support source macro in examples, fix Drawer and Dialog docs

- .changeset/bright-sloths-hope.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/Autosuggest/Autosuggest.test.tsx
- lib/components/Autosuggest/Autosuggest.tsx
Leaving this undocumented for now since the docs overhaul is currently in progress.
> Autosuggest: Support messages when no suggestions are available

- .changeset/dull-otters-listen.md
- .changeset/six-tables-end.md
- .changeset/thin-apricots-argue.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/Box/useBoxStyles.treat.ts
- lib/components/Button/Button.docs.tsx
- lib/components/Button/Button.gallery.tsx
- lib/components/Button/Button.screenshots.tsx
- lib/components/Button/Button.snippets.tsx
- lib/components/Button/Button.tsx
- lib/components/ButtonLink/ButtonLink.docs.tsx
- lib/components/ButtonLink/ButtonLink.screenshots.tsx
- lib/components/ButtonLink/ButtonLink.tsx
- lib/components/ButtonRenderer/ButtonRenderer.tsx
- lib/themes/makeBraidTheme.ts
> Button, ButtonLink, ButtonRenderer: Add support for critical tone

- .changeset/little-seals-attend.md
- .changeset/sixty-cameras-fry.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/MenuItem/MenuItem.docs.tsx
- lib/components/MenuItem/MenuItem.tsx
- lib/components/MenuItem/MenuItemLink.tsx
- lib/components/MenuItem/useMenuItem.tsx
- lib/components/MenuItemCheckbox/MenuItemCheckbox.tsx
- lib/components/MenuItemDivider/MenuItemDivider.tsx
- lib/components/MenuRenderer/MenuRenderer.docs.tsx
- lib/components/MenuRenderer/MenuRenderer.tsx
- lib/components/OverflowMenu/OverflowMenu.docs.tsx
> MenuItem, MenuItemLink: Add support for critical tone

- .changeset/small-jeans-bow.md
- lib/components/Autosuggest/Autosuggest.test.tsx
- lib/components/Autosuggest/Autosuggest.tsx
> Autosuggest: Fix bug where async suggestions may not be visible

- .changeset/spicy-pillows-bathe.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/Tabs/Tab.tsx
- lib/components/Tabs/TabListContext.ts
- lib/components/Tabs/Tabs.docs.tsx
- lib/components/Tabs/Tabs.gallery.tsx
- lib/components/Tabs/Tabs.screenshots.tsx
- lib/components/Tabs/Tabs.tsx
> Tabs: Add 'divider' prop, support 'full' and 'none'

- .changeset/slow-gifts-pretend.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/Tabs/TabPanels.tsx
- lib/components/Tabs/Tabs.test.tsx
- lib/components/Tabs/Tabs.tsx
> Tabs: Support fragments and null/undefined as children

- .changeset/fuzzy-cups-breathe.md
- .changeset/metal-pans-breathe.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/Box/useBoxStyles.treat.ts
- lib/components/TooltipRenderer/TooltipRenderer.docs.tsx
- lib/components/TooltipRenderer/TooltipRenderer.treat.ts
- lib/components/TooltipRenderer/TooltipRenderer.tsx
> Add 'placement' to TooltipRenderer, add 'cursor="default"' to Box

- .changeset/fair-hotels-yell.md
- .changeset/perfect-buckets-boil.md
- .changeset/rude-bats-attack.md
- .changeset/smooth-insects-explain.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/Box/useBoxStyles.treat.ts
- lib/components/Box/useBoxStyles.ts
- lib/components/Card/Card.docs.tsx
- lib/components/Card/Card.gallery.tsx
- lib/components/Card/Card.screenshots.tsx
- lib/components/Card/Card.snippets.tsx
- lib/components/Card/Card.treat.ts
- lib/components/Card/Card.tsx
> Card: Add support for tone and radius

- site/src/App/Markdown/Markdown.tsx
Supports deep linking to a specific release on the docs site.
> Docs: Make versions deep linkable on releases

- .changeset/happy-maps-pay.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- generate-component-docs/generate.ts
- lib/components/Accordion/AccordionItem.tsx
- lib/components/Disclosure/Disclosure.tsx
- lib/components/Stack/Stack.tsx
- lib/utils/responsiveProp.ts
- package.json
- yarn.lock
There was also a little bit of churn in the type snapshotting, unfortunately—and the ResponsiveSpace type comes out a little awkwardly (among a few other minor ones) but not sure how much we can control this.
> Fix type errors in TypeScript v4.2.2

- .changeset/few-buckets-compare.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/Accordion/Accordion.docs.tsx
- lib/components/Accordion/Accordion.gallery.tsx
- lib/components/Accordion/Accordion.playroom.tsx
- lib/components/Accordion/Accordion.screenshots.tsx
- lib/components/Accordion/Accordion.snippets.tsx
- lib/components/Accordion/Accordion.tsx
- lib/components/Accordion/AccordionContext.ts
- lib/components/Accordion/AccordionItem.playroom.tsx
- lib/components/Accordion/AccordionItem.tsx
- lib/playroom/components.ts
> Accordion: Add size, tone, space and dividers props

- lib/components/TooltipRenderer/TooltipRenderer.snippets.tsx
Since TooltipRenderer is hard to write by hand it would be useful to have a Snippet in playroom
> Add TooltipRenderer snippet

- lib/components/TextLinkButton/TextLinkButton.docs.tsx
> Docs: fix internal link

- .changeset/clean-fishes-jump.md
- css/index.ts
- css/vars.docs.tsx
- lib/components/Button/Button.docs.tsx
Expose `contentWidth` theme tokens
(Also fixes typo in Button docs)
> vars: Expose the contentWidth tokens

- .changeset/poor-teachers-enjoy.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/Accordion/AccordionItem.tsx
- lib/components/Actions/Actions.docs.tsx
- lib/components/Actions/Actions.gallery.tsx
- lib/components/Actions/Actions.snippets.tsx
- lib/components/Badge/Badge.tsx
- lib/components/Button/Button.docs.tsx
- lib/components/Button/Button.gallery.tsx
- lib/components/Button/Button.screenshots.tsx
- lib/components/Button/Button.test.tsx
- lib/components/Button/Button.tsx
- lib/components/ButtonIcon/ButtonIcon.test.tsx
- lib/components/ButtonLink/ButtonLink.screenshots.tsx
- lib/components/ButtonLink/ButtonLink.test.tsx
- lib/components/ButtonLink/ButtonLink.tsx
- lib/components/Tag/Tag.tsx
- lib/components/useToast/useToast.docs.tsx
- lib/components/useToast/useToast.gallery.tsx
Note: Also tweaking the `Badge` element type and a few recently added (unreleased) error messages.
> Button, ButtonLink: Add icon support

- codemod/src/codemod.ts
- codemod/src/plugin-deprecate/deprecationMaps/v31.ts
- codemod/src/plugin-deprecate/helpers.ts
- codemod/src/plugin-deprecate/plugin-deprecate-atoms.test.ts
- codemod/src/plugin-deprecate/plugin-deprecate-atoms.ts
- codemod/src/plugin-deprecate/plugin-deprecate-props.test.ts
- codemod/src/plugin-deprecate/plugin-deprecate-props.ts
- codemod/src/plugin-deprecate/plugin-deprecate-vars.test.ts
- codemod/src/plugin-deprecate/plugin-deprecate-vars.ts
- codemod/src/plugin-deprecate/subVisitor.ts
Parameterise deprecations to support the `upgrade` command providing different deprecations for different versions.
> upgrade: Make deprecations configurable by version

- lib/components/Button/Button.tsx
- lib/hooks/useIcon/index.ts
> Fix variable typos

- .changeset/famous-nails-run.md
- .changeset/grumpy-garlics-smoke.md
- .changeset/light-actors-sing.md
- .changeset/mean-wolves-yawn.md
- lib/components/Autosuggest/Autosuggest.tsx
- lib/components/MenuItem/MenuItem.screenshots.tsx
- lib/components/MenuItemCheckbox/MenuItemCheckbox.screenshots.tsx
- lib/components/MenuItemDivider/MenuItemDivider.screenshots.tsx
- lib/components/MenuRenderer/MenuRenderer.css.ts
- lib/components/MenuRenderer/MenuRenderer.screenshots.tsx
- lib/components/MenuRenderer/MenuRenderer.tsx
- lib/components/TooltipRenderer/TooltipRenderer.tsx
- lib/components/private/Announcement/Announcement.tsx
- lib/components/private/Modal/Modal.css.ts
- lib/components/private/Modal/Modal.tsx
- lib/components/private/ModalPortal/ModalPortal.css.ts
- lib/components/private/ModalPortal/ModalPortal.tsx
- site/src/App/DocNavigation/DocDetails.tsx
> Make Autosuggest list and MenuRenderer menu modal

- .changeset/slow-numbers-marry.md
- .changeset/thirty-apricots-fix.md
- generate-component-docs/__snapshots__/contract.test.ts.snap
- lib/components/Stepper/Step.tsx
- lib/components/Stepper/Stepper.css.ts
- lib/components/Stepper/Stepper.docs.tsx
- lib/components/Stepper/Stepper.gallery.tsx
- lib/components/Stepper/Stepper.screenshots.tsx
- lib/components/Stepper/Stepper.snippets.tsx
- lib/components/Stepper/Stepper.tsx
- lib/components/Stepper/StepperContext.tsx
- scripts/writeBraidFrontMatter.js
Provide the `align` prop which now includes support for `left` alignment.
```jsx
<Stepper align="left">
...
</Stepper>
```
> Stepper: Add align prop

- .github/workflows/snapshot.yml
This is a leftover from when we first tried to get it working, just never changed the name.
> Change job name

- package.json
- pnpm-lock.yaml
Fix site deployment by running npm script instead of built in pnpm command.
> Fix site deployment

- site/src/App/routes/guides/testing-guide.tsx
- Added a link to the [Common mistakes with React Testing Library blog post](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library)
- Added a test example that uses the `user-event` library. Wanted to show how you might use it to test some kind of accessibility flow while keeping the example as simple as possible.
> Testing guide update

- packages/braid-design-system/lib/components/Notice/Notice.docs.tsx
- site/src/App/DocNavigation/DocProps.tsx
https://braid-design-system--8a7832b820b0e22ab2fcc8cfa768df105b5adbf4.surge.sh/
> site: Fix broken prop source and migration links

- packages/braid-design-system/lib/components/Heading/Heading.gallery.tsx
- packages/braid-design-system/lib/components/Heading/Heading.screenshots.tsx
- packages/braid-design-system/lib/components/Text/Text.screenshots.tsx
Improving screenshot testing and gallery examples for both `Heading` and `Text` components
> Improve typography screenshots and gallery examples

- .changeset/thin-penguins-wave.md
- packages/braid-design-system/lib/components/Accordion/AccordionItem.css.ts
- packages/braid-design-system/lib/components/Accordion/AccordionItem.tsx
- packages/braid-design-system/lib/components/Button/Button.tsx
- packages/braid-design-system/lib/components/FieldMessage/FieldMessage.tsx
- packages/braid-design-system/lib/components/Notice/Notice.tsx
- packages/braid-design-system/lib/components/Tabs/Tab.tsx
- packages/braid-design-system/lib/components/Tabs/Tabs.css.ts
- packages/braid-design-system/lib/components/Tag/Tag.tsx
Removes custom icon sizing and layout in favour of new typography icon sizes and layout.
> Migrate icon slot custom sizing to typography based layouts

- .changeset/shaggy-tools-trade.md
Fixup to conform the the usual changeset format that looks nicer in the release notes.
> Changeset fixup

- .changeset/breezy-fireants-yawn.md
- .changeset/new-cheetahs-build.md
- .changeset/twelve-starfishes-talk.md
Refining some of the changesets in preparation for release
> Update changesets for release

- packages/braid-design-system/package.json
- pnpm-lock.yaml
- site/package.json
We need to get these vital efficiency gains out asap
> Upgrade playroom

- renovate.json
This gives us a faster feedback loop (to see if things break in compilation) and an easy way to create Braid snapshots for testing in apps
> Adding Crackle to renovate config

- .changeset/happy-plums-clean.md
- packages/braid-design-system/src/lib/components/Stepper/Stepper.css.ts
Refine the design of `Step` indicators by reducing their size.
> Stepper: Reduce size of `Step` indicators

- .changeset/young-kings-nail.md
- packages/braid-design-system/src/lib/components/MonthPicker/MonthPicker.tsx
Reduce the space between the month and year fields.
> MonthPicker: Reduce space between fields

- .changeset/wicked-lies-allow.md
- packages/braid-design-system/icons/message.svg
- packages/braid-design-system/src/lib/components/icons/IconMessage/IconMessage.docs.tsx
- packages/braid-design-system/src/lib/components/icons/IconMessage/IconMessage.migration.md
- packages/braid-design-system/src/lib/components/icons/IconMessage/IconMessage.tsx
- packages/braid-design-system/src/lib/components/icons/__snapshots__/icons.test.ts.snap
- packages/braid-design-system/src/lib/components/icons/index.ts
- packages/generate-component-docs/src/__snapshots__/contract.test.ts.snap
Add new `IconMessage` component.
```jsx
<IconMessage />
```
> IconMessage: Add component

- .github/workflows/validate.yml
Using https://github.com/marketplace/actions/skip-duplicate-actions
> Run validate workflow on `push` and `pull_request`, but skip duplicate runs

- .changeset/green-owls-run.md
- .changeset/quiet-keys-dance.md
- .changeset/smooth-files-tell.md
- .changeset/tidy-ladybugs-help.md
- .changeset/tidy-waves-yawn.md
- packages/braid-design-system/src/lib/components/TooltipRenderer/TooltipRenderer.tsx
- packages/braid-design-system/src/lib/components/private/Modal/Modal.css.ts
- packages/braid-design-system/src/lib/components/private/Modal/Modal.tsx
- packages/braid-design-system/src/lib/components/private/Modal/ModalContent.tsx
A suite of related changes to `Drawer`.
Aligning the horizontal gutter with `PageBlock` gutters to ensure content on mobile has the same available space both in and outside a `Drawer`.
With the above comes some other minor fixes/updates. See changesets for details.
> Drawer updates

- packages/braid-design-system/src/lib/components/Heading/Heading.screenshots.tsx
- packages/braid-design-system/src/lib/components/Text/Text.screenshots.tsx
Adding Thai samples to the typography screenshot tests in advance of improving the handling of font weights.
> Add Thai samples to typography screenshots

- .changeset/serious-moons-invite.md
- packages/codemod/package.json
- packages/generate-component-docs/bin.js
- packages/generate-component-docs/package.json
- pnpm-lock.yaml
Fixes the codemod not working after https://github.com/seek-oss/braid-design-system/pull/1339
> Bump esbuild in codemod and generate-component-docs

- .depcheckrc.yaml
- package.json
- packages/braid-design-system/package.json
- pnpm-lock.yaml
Attempting to fix the Chromatic issue (latest build on master not being recognised as latest).
> Upgrade depcheck and Chromatic to latest

- fixtures/consumer/__snapshots__/build.test.ts.snap
- fixtures/consumer/build.test.ts
- fixtures/consumer/package.json
- pnpm-lock.yaml
> Add a test for Vanilla Extract files imported as side-effects

- .changeset/bright-kids-divide.md
Add missing changeset for https://github.com/seek-oss/braid-design-system/pull/1449
> Add changeset for updating Capsize dependencies PR

- .changeset/thin-melons-glow.md
- packages/braid-design-system/src/lib/components/Checkbox/resolveCheckedGroup.test.ts
- packages/braid-design-system/src/lib/components/Checkbox/resolveCheckedGroup.ts
- packages/braid-design-system/src/lib/components/private/InlineField/StyledInput.tsx
**Checkbox:** Improve tri-state handling
Fixes a bug in [tri-state] `Checkbox` where transitioning from `mixed` to `checked` could result in the visual presentation being out of sync with the desired state.
- [Before] (production)
- [After]
Repro steps:
- "Select all"
- Uncheck one of the other checkboxes ("Select all" should be mixed now)
- "Select all" again
- Expect "Select all" to be checked
[Before]: https://braid-design-system--951f5a7d19e94ca3ae931c5005fc17d6972c6d93.surge.sh/playroom/#?code=N4Igxg9gJgpiBcIA8ARATgQwO4zQAgBcBLAgGxgF4AdEdbXGvCABxgDsLgC0BXGAXwB8VNnjxIAygQxgA1ngDOzGZRoBbGFCI81jLQDcisNAuGix4gMIALGHIBGEAB4iLF0hnsxS1EBO92BHgYpKQ0rm6KRABeqiAKaiFhIBFuYLZympwA2gDmMARSGAQwABQ0EGwwNACUADR4%2BYXSJeUgBFgQtQ1NRa00BNZoMNUgNQC6-KkWlTYYbPmcpcB4YDxow2wEACoYaE3weCvpdrKaePwXNXgUgkfTbgoF …
> Checkbox: Improve tri-state handling

- .changeset/little-pans-join.md
- packages/braid-design-system/package.json
- pnpm-lock.yaml
Update to latest Capsize packages
> Update Capsize dependencies

- packages/braid-design-system/src/lib/components/Actions/Actions.docs.tsx
- packages/braid-design-system/src/lib/components/Bleed/Bleed.docs.tsx
- packages/braid-design-system/src/lib/components/Bleed/Bleed.gallery.tsx
- packages/braid-design-system/src/lib/components/Columns/Columns.docs.tsx
- packages/braid-design-system/src/lib/components/Columns/Columns.gallery.tsx
- packages/braid-design-system/src/lib/components/Columns/Columns.snippets.tsx
- packages/braid-design-system/src/lib/components/Tiles/Tiles.docs.tsx
Part of a wave of PRs to improve and update the documentation. Goals for this include:
- Align snippets, examples, etc to spacing guidelines
- Improve quality & consistency of Playroom snippets
- Pull in relevant guidance from internal "Pattern Guides"
> site: Update Bleed and Columns docs and examples

- packages/braid-design-system/src/lib/components/Columns/Columns.docs.tsx
- packages/braid-design-system/src/lib/components/Inline/Inline.docs.tsx
- packages/braid-design-system/src/lib/components/Inline/Inline.gallery.tsx
- packages/braid-design-system/src/lib/components/Inline/Inline.snippets.tsx
- packages/braid-design-system/src/lib/components/Tiles/Tiles.docs.tsx
- packages/braid-design-system/src/lib/components/Tiles/Tiles.snippets.tsx
Part of a wave of PRs to improve and update the documentation. Goals for this include:
Align snippets, examples, etc to spacing guidelines
Improve quality & consistency of Playroom snippets
Pull in relevant guidance from internal "Pattern Guides"
> site: Update Tiles & Inline documentation and examples

- packages/braid-design-system/src/lib/components/Stack/Stack.docs.tsx
- packages/braid-design-system/src/lib/components/Stack/Stack.snippets.tsx
Part of a wave of PRs to improve and update the documentation. Goals for this include:
Align snippets, examples, etc to spacing guidelines
Improve quality & consistency of Playroom snippets
Pull in relevant guidance from internal "Pattern Guides"
> site: Update Stack snippets

- .changeset/big-pugs-greet.md
- .changeset/nice-mangos-hug.md
- packages/braid-design-system/src/lib/components/Autosuggest/Autosuggest.screenshots.tsx
- packages/braid-design-system/src/lib/components/Checkbox/Checkbox.screenshots.tsx
- packages/braid-design-system/src/lib/components/Checkbox/CheckboxStandalone.screenshots.tsx
- packages/braid-design-system/src/lib/components/Dropdown/Dropdown.screenshots.tsx
- packages/braid-design-system/src/lib/components/MonthPicker/MonthPicker.screenshots.tsx
- packages/braid-design-system/src/lib/components/PasswordField/PasswordField.screenshots.tsx
- packages/braid-design-system/src/lib/components/Radio/Radio.screenshots.tsx
- packages/braid-design-system/src/lib/components/TextField/TextField.screenshots.tsx
- packages/braid-design-system/src/lib/components/Textarea/Textarea.screenshots.tsx
- packages/braid-design-system/src/lib/components/private/Field/Field.tsx
- packages/braid-design-system/src/lib/components/private/FieldGroup/FieldGroup.tsx
- packages/braid-design-system/src/lib/components/private/InlineField/InlineField.css.ts
- packages/braid-design-system/src/lib/components/private/InlineField/InlineField.tsx
- packages/braid-design-system/src/lib/components/private/InlineField/StyledInput.tsx
Standardise `disabled` & `critical` state across form fields
Improves the consistency of form fields when combining both `disabled` and `critical` tone, which includes:
- Hiding `critical` borders
- Hiding `message` and not reserving space for it unless explicitly providing the `reserveMessageSpace` prop.
Playroom Previews: [Before] / [After]
[Before]: https://braid-design-system--80d6b5ffc3282878a12077aeedeb4084293db412.surge.sh/playroom/#?code=N4Igxg9gJgpiBcIA8AhCAPABABwIZSgEsA7AcwF4AdEAZwFtcAbR6gPkuM0yQGEJGArnWI1MNPGBhVaDZmw5cuwYjADumAIIAnLbgCeACgDMASgB0AM0LMD1auYbYDBwgBcYdADSYSsdCcxyVkxgBUUuSBFXTEg6OghiAAUtCGxRchCw8K5GXAAjGEZ4TGoAGXzC6k8s7KIafMYYKGLXLQEYas5srlcEmGLqMC03QjAmKprwuhgaetJ%2Bn2I-TGCABkwAfhKQABUZ12pMYoElmCsVKE7uri0ZmC0ANxgAWRm5mABlCQXfGCxyAGYABMV2yAF8ANwcSaYW6uARaTi2LrdXj8IT …
> Standardise `disabled` & `critical` state across form fields

- docs/Removing dividers support from layout components.md
Fix formatting and add conditional example.
> docs: Update dividers migration guide

- site/src/App/routes/guides/testing-guide.tsx
Minor update to the testing guide to:
* Remove endorsement for Enzyme
* Add more helpful links for appropriate testing strategies, including benefits of React Testing Library and guide for how to test React Hooks
* Fix typo in “accessibility”
> docs: Update testing guide

- .changeset/gentle-apricots-attend.md
- packages/braid-design-system/src/lib/components/List/List.screenshots.tsx
- packages/braid-design-system/src/lib/components/List/List.tsx
Applies left alignment to text within list items, to ensure consistent alignment even when inside centered layout containers.
> List: Ensure list item text is left aligned

- .changeset/gentle-apricots-attend.md
- packages/braid-design-system/src/lib/components/Alert/Alert.screenshots.tsx
- packages/braid-design-system/src/lib/components/Alert/Alert.tsx
- packages/braid-design-system/src/lib/components/Card/Card.screenshots.tsx
- packages/braid-design-system/src/lib/components/Card/Card.tsx
- packages/braid-design-system/src/lib/components/Checkbox/Checkbox.screenshots.tsx
- packages/braid-design-system/src/lib/components/Dialog/Dialog.screenshots.tsx
- packages/braid-design-system/src/lib/components/Drawer/Drawer.screenshots.tsx
- packages/braid-design-system/src/lib/components/FieldLabel/FieldLabel.screenshots.tsx
- packages/braid-design-system/src/lib/components/FieldLabel/FieldLabel.tsx
- packages/braid-design-system/src/lib/components/FieldMessage/FieldMessage.screenshots.tsx
- packages/braid-design-system/src/lib/components/FieldMessage/FieldMessage.tsx
- packages/braid-design-system/src/lib/components/Notice/Notice.screenshots.tsx
- packages/braid-design-system/src/lib/components/Notice/Notice.tsx
- packages/braid-design-system/src/lib/components/RadioGroup/RadioGroup.screenshots.tsx
- packages/braid-design-system/src/lib/components/Toggle/Toggle.screenshots.tsx
- packages/braid-design-system/src/lib/components/Toggle/Toggle.tsx
- packages/braid-design-system/src/lib/components/private/InlineField/InlineField.tsx
- packages/braid-design-system/src/lib/components/private/Modal/ModalContent.tsx
Applies left alignment to content, to ensure consistent alignment even when inside centered layout containers.
> Ensure content is left aligned by default

- site/src/App/routes/foundations/iconography/IconsDetails.tsx
> Fix doco typo

- site/src/App/Navigation/Navigation.css.ts
Fixes side nav being clickable when closed on mobile
> site: Fix side nav in mobile, disable pointerEvents when menu is closed

- packages/source.macro/README.md
[The source macro is going 1.0](https://github.com/seek-oss/braid-design-system/pull/1740), so I wrote a readme for it.
> Add a README to the source macro package

- packages/braid-design-system/package.json
- packages/braid-design-system/src/lib/stories/all.stories.tsx
- pnpm-lock.yaml
Also configured chromatic to capture in WebKit, Chromium and Firefox. Looks like all screenshots pass 😮‍💨
> Update dependency chromatic to v12.2.0

- packages/braid-design-system/src/lib/components/Accordion/Accordion.screenshots.tsx
- packages/braid-design-system/src/lib/components/Actions/Actions.screenshots.tsx
- packages/braid-design-system/src/lib/components/Alert/Alert.screenshots.tsx
- packages/braid-design-system/src/lib/components/Badge/Badge.screenshots.tsx
- packages/braid-design-system/src/lib/components/Bleed/Bleed.screenshots.tsx
- packages/braid-design-system/src/lib/components/Button/Button.screenshots.tsx
- packages/braid-design-system/src/lib/components/ButtonIcon/ButtonIcon.screenshots.tsx
- packages/braid-design-system/src/lib/components/ButtonLink/ButtonLink.screenshots.tsx
- packages/braid-design-system/src/lib/components/Card/Card.screenshots.tsx
- packages/braid-design-system/src/lib/components/Checkbox/Checkbox.screenshots.tsx
- packages/braid-design-system/src/lib/components/Checkbox/CheckboxStandalone.screenshots.tsx
- packages/braid-design-system/src/lib/components/Column/Column.screenshots.tsx
- packages/braid-design-system/src/lib/components/Columns/Columns.screenshots.tsx
- packages/braid-design-system/src/lib/components/ContentBlock/ContentBlock.screenshots.tsx
- packages/braid-design-system/src/lib/components/MenuRenderer/MenuRenderer.screenshots.tsx
- packages/braid-design-system/src/lib/components/MonthPicker/MonthPicker.screenshots.tsx
- packages/braid-design-system/src/lib/components/Notice/Notice.screenshots.tsx
- packages/braid-design-system/src/lib/components/Page/Page.screenshots.tsx
- packages/braid-design-system/src/lib/components/PasswordField/PasswordField.screenshots.tsx
- packages/braid-design-system/src/lib/components/RadioGroup/RadioGroup.screenshots.tsx
- packages/braid-design-system/src/lib/components/Rating/Rating.screenshots.tsx
- packages/braid-design-system/src/lib/components/Secondary/Secondary.screenshots.tsx
- packages/braid-design-system/src/lib/components/Spread/Spread.screenshots.tsx
- packages/braid-design-system/src/lib/components/Stepper/Stepper.screenshots.tsx
- packages/braid-design-system/src/lib/components/Table/Table.screenshots.tsx
- packages/braid-design-system/src/lib/components/Tag/Tag.screenshots.tsx
- packages/braid-design-system/src/lib/components/TextDropdown/TextDropdown.screenshots.tsx
- packages/braid-design-system/src/lib/components/TextLink/TextLink.screenshots.tsx
- packages/braid-design-system/src/lib/components/useToast/useToast.screenshots.tsx
In my opinion, these names need a bit of work. But fixing the worst issue first
> Fix screenshot story const name casing

- .changeset/good-suits-check.md
- packages/braid-design-system/src/lib/themes/baseTokens/nvl.ts
[Playroom](https://seek-oss.github.io/braid-design-system/playroom/#?code=N4Igxg9gJgpiBcIA8AhCAPABABwIZSgEsA7AcwF4AdEUgVwBd6YAnagPkuM0yQBUJSpADYxMQ3ACMYQqiAByMAO6YAzgAt8ERSuqr6uJnNwBbGLOJLdAeg7EkVtOluckK%2BgE8RmAFYqnwAANObgASYFIYegBlfSYACmoLRWoASkwAfkxqADoIAAZjADY84jzdeCyQagBfTGBg7kwAWiaAfQAmY1whb3aAViF4BsbMZlIJXDj2gA4AGkwAZj75gBY5zDzsvOm0vOwsPawV-Y392eHGsYmp9aXV9c3t3ZPjrGmTpvb9gG4Llo6uj1%2BsYhlwRqNxpMZvM7pg1vNHjtTgcTu8UehzmCRlcobdlnCHlskYdMGjMABGQofV6-LHNNqdbq9PrEUHgiHXaGLfHwjZE57oilfdGY9k4m4wnmEp7IoUndqvZpU9C07jVTgBar2NyeGDOOwABVwERQQggYAA1rZuEgYrhLao8GAzNR0OhxGMYOwLrb9A6VE6XSAPRFvXTuMAANrUFSAoTUebUUxEWjGBOVENekAAXWyXWwcTiKjS5DYmAS4caqAwF3ZE0tpGYEFoxCgshUtGYADN7Vna%2BCJBBmLBmAAlfCEWgqdv6Vu4YfUfsjPAEEikACa5GAKnVleX%2BCIZAAGrI6IwWIu941B%2BgohooFotzul5hreyq7wYOh6GwFMomnUO72J%2B35vuy9iOGBjQp …
> seekJobs, seekBusiness: Updated drop shadow palette

- packages/braid-design-system/src/lib/components/PageBlock/PageBlock.docs.tsx
- packages/braid-design-system/src/lib/components/PageBlock/PageBlock.tsx
- packages/braid-design-system/src/lib/components/PageBlock/pageBlockGutters.ts
- packages/braid-design-system/src/lib/components/private/Modal/ModalContent.tsx
- packages/braid-design-system/src/lib/components/useToast/Toast.tsx
- packages/braid-design-system/src/lib/components/useToast/Toaster.css.ts
- packages/braid-design-system/src/lib/components/useToast/Toaster.tsx
- packages/braid-design-system/src/lib/components/useToast/useToast.docs.tsx
- packages/braid-design-system/src/lib/components/useToast/useToast.screenshots.tsx
No changeset because `Toast` update hasn't released yet.
> useToast: Fix layout, ensure X padding on mobile

- .github/workflows/release.yml
I guess when you specify no permissions you get all of the permissions??
Resolves: https://github.com/seek-oss/braid-design-system/actions/runs/18298725796/job/52102360303
> Add `contents: write` permission
